DEFINE

	VAR __BaseTable = SUMMARIZE(
		'ASER CIV Data',
		'ASER CIV Data'[School ID],
		'ASER CIV Data'[Period],
		"@Progress in Literacy from BL to EL", [pp Of Literacy Improvement From BL to EL],
		"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvement From BL to EL]
	)
	
	VAR __Table = SELECTCOLUMNS(
		__BaseTable,
		"@School ID", 'ASER CIV Data'[School ID],
		"@Period", 'ASER CIV Data'[Period],
		"@Literacy Status", SWITCH( TRUE(),
							[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
							[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
							[@Progress in Literacy from BL to EL] < 0.25, "Yellow school (10-25pp)",
							"Green school (>25pp)" ),
		"@Numeracy Status", SWITCH( TRUE(),
							[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
							[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
							[@Progress in Numeracy from BL to EL] < 0.25, "Yellow school (10-25pp)",
							"Green school (>25pp)" )
	)
									


EVALUATE FILTER(__BaseTable, 'ASER CIV Data'[Period] = "2025-2026" )
EVALUATE FILTER(__Table, [@Period] = "2025-2026" )