DEFINE

VAR __BaseTable =
    SUMMARIZE(
        'ASER Data CIV',
        'ASER Data CIV'[School ID],
        'ASER Data CIV'[Grade ID],
        'ASER Data CIV'[Cycle ID],
        "@Effectif", MAX( 'ASER Data CIV'[Students In Class] )
    )


VAR __EffectifParEcoleParCycle =
    SUMMARIZE(
        __BaseTable,
        'ASER Data CIV'[School ID],
        'ASER Data CIV'[Cycle ID],
        "@EffectifCycle", SUMX(
            FILTER( __BaseTable, 
                'ASER Data CIV'[School ID] = EARLIER('ASER Data CIV'[School ID] ) &&
                'ASER Data CIV'[Cycle ID]  = EARLIER( 'ASER Data CIV'[Cycle ID] )
            ),
            [@Effectif]
        )
    )

EVALUATE FILTER( __BaseTable, 'ASER Data CIV'[School ID] = 1 && 'ASER Data CIV'[Cycle ID] = 1)
EVALUATE __EffectifParEcoleParCycle ORDER BY 'ASER Data CIV'[School ID] ASC