DEFINE
VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
		'ASER CIV Data',
		"@Grade ID", 'ASER CIV Data'[Grade ID],
		"@Cycle ID", 'ASER CIV Data'[Cycle ID],
		"@Students In Class", 'ASER CIV Data'[Students In Class]
	))


EVALUATE FILTER(__BaseTable, [@Grade ID] = 10 && [@Cycle ID] = 2)