DEFINE

	VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
		'ASER Cycles Data',
		"@Cycle ID", 'ASER Cycles Data'[Cycle ID],
		"@School ID", 'ASER Cycles Data'[School ID],
		"@Students In School", 'ASER Cycles Data'[Students In School]
	))



EVALUATE
	FILTER(
		__BaseTable,
		[@School ID] = 312 && [@Cycle ID] = 3
	)