table Cycles
	lineageTag: 2dc2b491-cd42-4119-9a49-bf55e1235237

	column 'Cycle ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 49860b4c-a29f-4ee8-95b2-a4bcc7b08489
		summarizeBy: none
		sourceColumn: Cycle ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cycle
		dataType: string
		lineageTag: 0ee720e5-5240-4f6a-9fa0-0fba5811fa37
		summarizeBy: none
		sourceColumn: Cycle
		sortByColumn: 'Cycle Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: 54bef491-3e23-4eed-8f45-95ec5713191a
		summarizeBy: none
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column 'Cycle Name'
		dataType: string
		lineageTag: dfef2b3a-3e1f-4690-bb57-9750c145c4e1
		summarizeBy: none
		sourceColumn: Cycle Name
		sortByColumn: 'Cycle ID'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Cycle Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d68d0fc-353c-4699-b1a4-5fe0ea19c5eb
		summarizeBy: none
		sourceColumn: Cycle Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Cycles = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Old Data", #"New Data"}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(Source,{"Period"}),
				    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
				    #"Lignes triées" = Table.Sort(#"Doublons supprimés",{{"Period", Order.Ascending}}),
				    #"Index ajouté" = Table.AddIndexColumn(#"Lignes triées", "Index", 1, 1, Int64.Type),
				    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "Period Sort"}}),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Colonnes renommées", "Cycle", each #"Cycles List"[Cycle]),
				    #"Cycle développé" = Table.ExpandListColumn(#"Personnalisée ajoutée", "Cycle"),
				    #"Type modifié" = Table.TransformColumnTypes(#"Cycle développé",{{"Cycle", type text}}),
				    #"Requêtes fusionnées" = Table.NestedJoin(#"Type modifié", {"Cycle"}, #"Cycles List", {"Cycle"}, "Cycles List", JoinKind.LeftOuter),
				    #"Cycles List développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "Cycles List", {"Cycle Sort"}, {"Cycle Sort"}),
				    #"Personnalisée ajoutée1" = Table.AddColumn(#"Cycles List développé", "Cycle ID", each ([Period Sort] -1 ) * 3 + [Cycle Sort], Int64.Type),
				    #"Personnalisée ajoutée2" = Table.AddColumn(#"Personnalisée ajoutée1", "Cycle Name", each [Period] & " " & [Cycle], type text),
				    #"Autres colonnes supprimées1" = Table.SelectColumns(#"Personnalisée ajoutée2",{"Period", "Cycle", "Cycle Sort", "Cycle ID", "Cycle Name"})
				in
				    #"Autres colonnes supprimées1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

