table 'Levels in Subjects'
	lineageTag: 228a31b4-63b6-4a56-af45-4169c3054e5f

	column 'Subject ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dc5913eb-5109-4b12-b722-125ccbd657b9
		summarizeBy: none
		sourceColumn: Subject ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Group Level Sort' =
			
			SWITCH( TRUE(),
			        'Levels in Subjects'[Level Sort] <= 2, 1,
			        'Levels in Subjects'[Level Sort] = 3, 2,
			        'Levels in Subjects'[Level Sort] <= 6, 3,
			        'Levels in Subjects'[Level Sort] <= 12, 4,
			        'Levels in Subjects'[Level Sort] = 13, 5,
			        'Levels in Subjects'[Level Sort] <= 15, 6,
			        BLANK() )
		isHidden
		formatString: 0
		lineageTag: ed270a33-723a-4a8e-b238-e61fcac9f99a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 13616aec-13da-4333-8315-c1de70d971ab
		summarizeBy: none
		sourceColumn: Level
		sortByColumn: 'Level Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Levels in Subjects","TableItemName":"Grouped Level","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Subject
		dataType: string
		lineageTag: 98a04a38-6d90-4ea8-bdf8-2c7e3f9c1559
		summarizeBy: none
		sourceColumn: Subject

		annotation SummarizationSetBy = Automatic

	column 'Level ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 41493d22-4abd-471f-b644-6594ca5d0fc4
		summarizeBy: none
		sourceColumn: Level ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Level Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c40a7215-0eea-41a6-b491-d741cb5fa133
		summarizeBy: none
		sourceColumn: Level Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Grouped Level' =
			SWITCH(
				TRUE,
				ISBLANK('Levels in Subjects'[Level]),
				"(Vide)",
				'Levels in Subjects'[Level] IN {"2-Digit"},
				"2-Digit",
				'Levels in Subjects'[Level] IN {"Paragraph",
					"Story",
					"Comprehension"},
				"Can read at least a simple paragraph",
				'Levels in Subjects'[Level] IN {"Substraction",
					"Division"},
				"Can solve at least 2x2 subtraction operation",
				'Levels in Subjects'[Level] IN {"Beginner L",
					"Letter"},
				"Cannot read words",
				'Levels in Subjects'[Level] IN {"Beginner N",
					"1-Digit"},
				"Cannot recognize 2-digit",
				'Levels in Subjects'[Level] IN {"Word"},
				"Word",
				'Levels in Subjects'[Level]
			)
		lineageTag: 412e89ff-3482-4024-8046-4196cbf45b0a
		summarizeBy: none
		sortByColumn: 'Group Level Sort'

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Levels in Subjects"
				          }
				        },
				        "Property": "Level"
				      }
				    }
				  ]
				}

		changedProperty = SortByColumn

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"l","Entity":"Levels in Subjects"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"GroupItems":[{"DisplayName":"(Vide)","BlankDefaultPlaceholder":true},{"DisplayName":"2-Digit","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'2-Digit'"}}]]}}},{"DisplayName":"Can read at least a simple paragraph","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Paragraph'"}}],[{"Literal":{"Value":"'Story'"}}],[{"Literal":{"Value":"'Comprehension'"}}]]}}},{"DisplayName":"Can solve at least 2x2 subtraction operation","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Substraction'"}}],[{"Literal":{"Value":"'Division'"}}]]}}},{"DisplayName":"Cannot read words","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Beginner L'"}}],[{"Literal":{"Value":"'Letter'"}}]]}}},{"DisplayName":"Cannot recognize 2-digit","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Beginner N'"}}],[{"Literal":{"Value":"'1-Digit'"}}]]}}},{"DisplayName":"Word","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Word'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	hierarchy 'Subject Hierarchy'
		lineageTag: 1c08e0fb-1ab4-4532-bc83-87adbc0abf99

		level Subject
			lineageTag: ca4f66dc-ba0e-4c55-ac69-c82957e17645
			column: Subject

		level 'Grouped Level'
			lineageTag: e05ebebe-8a91-41ff-8795-a3b5a4387fe0
			column: 'Grouped Level'

		level Level
			lineageTag: 12841276-c4f1-43c0-ad30-0658a5432ab9
			column: Level

	partition 'Levels in Subjects' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Old Data", #"New Data"}),
				    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Valeur remplacée",{{"Beginner L", "Beginner L - L"}, {"Letter", "Letter - L"}, {"Word", "Word - L"}, {"Paragraph", "Paragraph - L"}, {"Story", "Story - L"}, {"Beginner N", "Beginner N - N"}, {"1-Digit", "1-Digit - N"}, {"2-Digit", "2-Digit - N"}, {"Substraction", "Substraction - N"}, {"Division", "Division - N"}, {"Comprehension", "Comprehension - L"}}),
				    #"Tableau croisé dynamique des colonnes supprimé" = Table.UnpivotOtherColumns(#"Colonnes renommées", {"DRENAET", "IEPP", "School", "Cycle", "Grade", "Students In Class", "Boys Tested", "Girls Tested", "Entry Date", "Region", "Sector", "Students Tested", "Period", "Teacher Male", "Teacher Female"}, "Attribut", "Valeur"),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Tableau croisé dynamique des colonnes supprimé",{{"Valeur", "Number Of Students"}}),
				    #"Fractionner la colonne par délimiteur" = Table.SplitColumn(#"Colonnes renommées1", "Attribut", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Attribut.1", "Attribut.2"}),
				    #"Colonnes renommées2" = Table.RenameColumns(#"Fractionner la colonne par délimiteur",{{"Attribut.1", "Level"}, {"Attribut.2", "Subject"}}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Colonnes renommées2","L","Literacy",Replacer.ReplaceText,{"Subject"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","N","Numeracy",Replacer.ReplaceText,{"Subject"}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Valeur remplacée2",{"Level", "Subject"}),
				    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
				    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 0, 1, Int64.Type),
				    #"Colonnes renommées3" = Table.RenameColumns(#"Index ajouté",{{"Index", "Level ID"}}),
				    #"Colonne conditionnelle ajoutée" = Table.AddColumn(#"Colonnes renommées3", "Subject ID", each if [Subject] = "Literacy" then 1 else if [Subject] = "Numeracy" then 2 else null),
				    #"Type modifié" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée",{{"Subject ID", Int64.Type}}),
				    #"Colonne conditionnelle ajoutée1" = Table.AddColumn(#"Type modifié", "Level Sort", each if [Level] = "Beginner L" then 1 else if [Level] = "Letter" then 2 else if [Level] = "Word" then 3 else if [Level] = "Paragraph" then 4 else if [Level] = "Story" then 5 else if [Level] = "Comprehension" then 6 else if [Level] = "Beginner N" then 11 else if [Level] = "1-Digit" then 12 else if [Level] = "2-Digit" then 13 else if [Level] = "Substraction" then 14 else if [Level] = "Division" then 15 else null),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée1",{{"Level Sort", Int64.Type}})
				in
				    #"Type modifié1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

