table Mesures
	lineageTag: 88d328ed-b1e1-4ef2-a3ac-aee29dcb536c

	measure '# Of DRENAETs' = DISTINCTCOUNT( 'Grades'[DRENAET] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 18a3d325-e8d5-453f-b685-22788919c997

	measure '# Of IEPPs' = DISTINCTCOUNT( 'Grades'[IEPP] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: cf5d988b-65aa-4447-9c26-9f74f6fda9a7

	measure '# Of Schools' = DISTINCTCOUNT( 'Grades'[School ID] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: cb9668aa-733c-44e6-aa9e-f06733f64b35

	measure '# Of Schools Reached' = DISTINCTCOUNT( 'ASER CIV Data'[School ID] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 067b1b3d-1b52-4e22-bc96-5aaa63df3ad2

	measure '# Of Students In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Students In Class", 'ASER CIV Data'[Students In Class]
				))
			
			    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle )
			
			RETURN SUMX( __FilteredTable, [@Students In Class] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 32a8b5ca-4fd8-4f29-8e78-d208d54298d1

	measure '# Of Students Tested In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Level ID", 'ASER CIV Data'[Level ID],
					"@Subject ID", 'ASER CIV Data'[Subject ID],
					"@Students At Level", 'ASER CIV Data'[Students At Level]
				))
			
			VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Subject ID] = __CurrentSubject)
			
			RETURN SUMX( __FilteredTable, [@Students At Level] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 4589fda1-cd39-43d9-8eb0-b4e3ad2e6e2f

	measure '_# Of Students Reached In Program' =
			
			VAR __BaseTable =
			    SUMMARIZE (
			        'ASER CIV Data',
			        Cycles[Period],
			        'ASER CIV Data'[Cycle ID],
			        'ASER CIV Data'[School ID],
			        'ASER CIV Data'[Grade ID],
			        "@Effectif", MAX ( 'ASER CIV Data'[Students In Class] )
			    )
			
			VAR __TotalParCycle =
			    GROUPBY (
			        __BaseTable,
			        Cycles[Period],
			        'ASER CIV Data'[Cycle ID],
			        "@TotalCycle", SUMX ( CURRENTGROUP (), [@Effectif] )
			    )
			
			RETURN
			    MAXX ( __TotalParCycle, [@TotalCycle] )
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 24fd0b70-42c6-4753-ba54-2d4d41e7d508

	measure '% Change Rate Of Students Tested' =
			
			
			VAR __CurrentNumberOfStudents = [# Of Students Tested In Cycle]
			VAR __PreviousNumberOfStudents = [# Of Students Tested In Previous Cycle]
			VAR __NumberChange = __CurrentNumberOfStudents - __PreviousNumberOfStudents
			VAR __PercentageChange = DIVIDE( __NumberChange, __PreviousNumberOfStudents )
			RETURN __PercentageChange
		displayFolder: 0. Overall KPIs
		lineageTag: 20bfb364-664a-4ff1-be41-a72bc3ddca38

		formatStringDefinition = "+0 %;-0 %;0 %"

	measure '# Of Students Tested In Previous Cycle' =
			
			VAR __NumberOfCycles = 'Cycles interval'[Valeur Cycles Interval]
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] ) - 'Cycles interval'[Valeur Cycles Interval]
			VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
			
			VAR __BaseTable =
			    DISTINCT(
			        SELECTCOLUMNS(
			            CALCULATETABLE(
			                'ASER CIV Data',
			                ALL( Cycles )
			            ),
			            "@Cycle ID",        'ASER CIV Data'[Cycle ID],
			            "@School ID",       'ASER CIV Data'[School ID],
			            "@Subject ID",      'ASER CIV Data'[Subject ID],
			            "@Students Tested", 'ASER CIV Data'[Students At Level]
			        )
			    )
			
			VAR __FilteredTable =
			    FILTER(
			        __BaseTable,
			        [@Cycle ID] = __CurrentCycle &&
			        [@Subject ID] = __CurrentSubject
			    )
			
			RETURN
			    SUMX( __FilteredTable, [@Students Tested] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 450a8c52-7905-4a81-9a13-73e707afd5b8

	measure '# Of Boys Tested In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Boys Tested In Class", 'ASER CIV Data'[Boys Tested In Class]
				))
			
			    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle)
			
			RETURN SUMX( __FilteredTable, [@Boys Tested In Class] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 38384916-df62-49fd-9dae-93494f57aa80

	measure '# Of Girls Tested In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Girls Tested In Class", 'ASER CIV Data'[Girls Tested In Class]
				))
			
			    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle )
			
			RETURN SUMX( __FilteredTable, [@Girls Tested In Class] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: bc504718-b829-4160-adbb-0d4caa6c15d6

	measure '% Of Students With High Literacy In Cycle' = ```
			
			DIVIDE( 
			    [# Of Students With High Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 1d3c5cd4-246e-4480-8b48-63d56ff14838

	measure '# Of Students With High Literacy In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
				VAR __GradesData =
				SELECTCOLUMNS(
					'ASER CIV Data',
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Grade", RELATED( Grades[Grade] ),
			        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
					"@Students At Level", 'ASER CIV Data'[Students At Level]
				)
			
			    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 3)
			
			RETURN SUMX( __FilteredTable, [@Students At Level] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 3f415c52-f7fc-4d20-993a-6cfa641ab613

	measure '% Of Students With High Literacy At BL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With High Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "BL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 80db46d6-8cbf-4667-b72f-4c291d6825be

	measure '% Of Students With High Literacy At EL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With High Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "EL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: fcbfe87e-5312-417d-b542-0b17a4dfb42b

	measure 'pp Of Literacy Improvemnt From BL to EL' =
			
			VAR __EL = [% Of Students With High Literacy At EL]
			VAR __BL = [% Of Students With High Literacy At BL]
			VAR __Result = __EL - __BL
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 2. Program specific KPIs
		lineageTag: 420efd55-0b13-43f0-9e12-93ef15d1dfd1

	measure '# Of Students With Low Literacy In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
					"@Students At Level", 'ASER CIV Data'[Students At Level]
				))
			
			    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 1)
			
			RETURN SUMX( __FilteredTable, [@Students At Level] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 211d6b35-41e0-40ab-b4f4-aa8ae078e2af

	measure 'pp Of Literacy Difficulty Reduction From BL to EL' =
			
			VAR __EL = [% Of Students With Low Literacy At EL]
			VAR __BL = [% Of Students With Low Literacy At BL]
			VAR __Result = __BL - __EL
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 2. Program specific KPIs
		lineageTag: 92710847-def6-4456-92ca-92e25a8d0deb

	measure '% Of Students With Low Literacy At EL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With Low Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "EL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 0152dfa5-ae6d-484a-8ae0-bc918afaca61

	measure '% Of Students With Low Literacy At BL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With Low Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "BL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: a36eda9a-1aaa-41d6-913e-4ebcc7e571b2

	measure '# Of Students With High Numeracy In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
				VAR __GradesData =
				SELECTCOLUMNS(
					'ASER CIV Data',
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Grade", RELATED( Grades[Grade] ),
			        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
					"@Students At Level", 'ASER CIV Data'[Students At Level]
				)
			
			    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 6)
			
			RETURN SUMX( __FilteredTable, [@Students At Level] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: a2cf9272-e7db-4400-87ff-c1009e77cb46

	measure '% Of Students With High Numeracy At BL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With High Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "BL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 001a5102-7096-4460-89e3-c4da2e95658c

	measure '% Of Students With High Numeracy At EL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With High Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "EL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: e6cafb5c-b178-462a-a3b5-f3942aab4247

	measure 'pp Of Numeracy Improvemnt From BL to EL' =
			
			VAR __EL = [% Of Students With High Numeracy At EL]
			VAR __BL = [% Of Students With High Numeracy At BL]
			VAR __Result = __EL - __BL
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 2. Program specific KPIs
		lineageTag: 90bd8cc0-78a0-4549-8af0-9020b7347640

	measure '% Of Students With High Numeracy In Cycle' = ```
			
			DIVIDE( 
			    [# Of Students With High Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 4661b9a4-6f23-4856-83d9-27f15acd5bb0

	measure '# Of Students With Low Numeracy In Cycle' =
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			
			VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
					'ASER CIV Data',
					"@Grade ID", 'ASER CIV Data'[Grade ID],
					"@Cycle ID", 'ASER CIV Data'[Cycle ID],
					"@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
					"@Students At Level", 'ASER CIV Data'[Students At Level]
				))
			
			    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 4)
			
			RETURN SUMX( __FilteredTable, [@Students At Level] )
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 7b8873f5-05ca-4796-a7b1-9fdb4f258ba0

	measure '% Of Students With Low Numeracy In Cycle' = ```
			
			DIVIDE( 
			    [# Of Students With Low Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 6d2a5faa-4cf3-46a7-bd1d-41d31d8b4a13

	measure '% Of Students With Low Numeracy At BL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With Low Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "BL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: c03f20e5-6c17-498f-bf5c-16f5b2cee833

	measure '% Of Students With Low Numeracy At EL' = ```
			
			CALCULATE (DIVIDE( 
			    [# Of Students With Low Numeracy In Cycle],
			    [# Of Students Tested In Cycle]
			    ), Cycles[Cycle] = "EL" )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 3f005491-75a7-4af6-994a-abfd439986c8

	measure 'pp Of Numeracy Difficulty Reduction From BL to EL' =
			
			VAR __EL = [% Of Students With Low Numeracy At EL]
			VAR __BL = [% Of Students With Low Numeracy At BL]
			VAR __Result = __BL - __EL
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 2. Program specific KPIs
		lineageTag: aa0fab98-392c-4b0c-93a3-e07b66114535

	measure '% Of Students With Low Literacy In Cycle' = ```
			
			DIVIDE( 
			    [# Of Students With Low Literacy In Cycle],
			    [# Of Students Tested In Cycle]
			    )
			```
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 16eb3db3-45d0-4e40-b785-cc7aad0904e1

	measure 'Selected Cycle' = MAX( Cycles[Cycle Name] )
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 825df335-d53b-4f76-ba13-9c005806ccdd

	measure 'Compared To Cycle' =
			
			VAR __CurrentCycleID = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycle = MAX( Cycles[Cycle Name] )
			VAR __ComparedToID = __CurrentCycleID - 'Cycles interval'[Valeur Cycles Interval]
			VAR __ComparedToName = LOOKUPVALUE( Cycles[Cycle Name], Cycles[Cycle ID], __ComparedToID)
			
			RETURN __ComparedToName
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 063a0961-39b6-44c8-8f64-9217198fd396

	measure '# Of Boys and Girls Tested In Cycle' = [# Of Boys Tested In Cycle] + [# Of Girls Tested In Cycle]
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 5e9db005-b7fb-4ae9-806a-8bb9cf9df357

	measure '# Of DRENAETs Reached' = DISTINCTCOUNT( 'ASER CIV Data'[DRENAET ID] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 5b030cf3-e886-45ad-b49a-4d2e953a1225

	measure '# Of IEPPs Reached' = DISTINCTCOUNT( 'ASER CIV Data'[IEPP ID] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 70672695-dd88-4a1c-986e-42126c156b3c

	measure '% Of Schools That Submitted Their data' =
			
			DIVIDE( [# Of Schools Reached], [# Of Schools] )
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: 0. Overall KPIs
		lineageTag: cd4870d4-ea1e-4ef7-b073-db5a7effc9de

	measure 'Home Page Title' = "Endline Assessment Results"
		lineageTag: 461d8922-0f4d-4b22-ac4e-87a1f7386f05

	measure 'Home Page SubTitle' =
			
			VAR __Period = MAX( Cycles[Period] )
			VAR __SubTitle = "Academic year " & __Period & ", Côte d'Ivoire"
			RETURN __SubTitle
		lineageTag: faf5ccdc-df33-4320-9e5e-0c02df24d6ad

	measure 'Reach Stats Title' =
			
			VAR __Period = MAX( Cycles[Period] )
			RETURN "Reach in " & __Period
		lineageTag: 97560163-30b3-4ee3-be3b-c833e8051136

	measure '# Of Red schools for Literacy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Literacy Status", SWITCH(
						TRUE(),
						[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Literacy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Literacy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Literacy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Red_Schools = FILTER(
					__Table,
					[@Literacy Status] = "Red school (0-10pp)"
				)
			
			    VAR __Result = COUNTROWS( __Red_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 72502e7f-3519-41b2-93bc-4d0c974d0f74

	measure '# Of Lower Yellow schools for Literacy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Literacy Status", SWITCH(
						TRUE(),
						[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Literacy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Literacy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Literacy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Literacy Status] = "Lower Yellow school (10-15pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 5502c1f4-9cb7-4468-a3d5-231b47291a89

	measure '# Of Green schools for Literacy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Literacy Status", SWITCH(
						TRUE(),
						[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Literacy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Literacy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Literacy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Green_Schools = FILTER(
					__Table,
					[@Literacy Status] = "Green school (>25pp)"
				)
			
			    VAR __Result = COUNTROWS( __Green_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 63b96d07-c17d-46f5-ac60-2c0e483a7d2c

	measure '# Of Lower Yellow schools for Numeracy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Numeracy Status", SWITCH(
						TRUE(),
						[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Numeracy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Numeracy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Numeracy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Numeracy Status] = "Lower Yellow school (10-15pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 3b6661d8-c428-4571-ac1d-47548f4b3a09

	measure '# Of Red schools for Numeracy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Numeracy Status", SWITCH(
						TRUE(),
						[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Numeracy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Numeracy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Numeracy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Red_Schools = FILTER(
					__Table,
					[@Numeracy Status] = "Red school (0-10pp)"
				)
			
			    VAR __Result = COUNTROWS( __Red_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 16265274-fda3-42d0-9bff-9c9f5a267232

	measure '# Of Green schools for Numeracy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Numeracy Status", SWITCH(
						TRUE(),
						[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Numeracy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Numeracy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Numeracy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Green_Schools = FILTER(
					__Table,
					[@Numeracy Status] = "Green school (>25pp)"
				)
			
			    VAR __Result = COUNTROWS( __Green_Schools )
			
			    RETURN __Result
		formatString: #,0
		displayFolder: 2. Program specific KPIs
		lineageTag: 2e009ffe-a9a3-45a7-a2f0-fc1156e0f611

	measure '# Of Schools Visited' = DISTINCTCOUNT( 'Mentoring Visits'[School ID] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 92100cbd-3a25-4528-90f6-65eb70b2d0b6

	measure 'Average Number Of Mentoring School Visits' = DIVIDE( [# Of Visits], [# Of Schools Visited] )
		formatString: #,0.00
		displayFolder: 0. Overall KPIs
		lineageTag: 1db5c8e7-3c12-4876-867d-45e06d2cb988

	measure '# Of Visits' = SUM( 'Mentoring Visits'[Visits Count] )
		formatString: #,0
		displayFolder: 0. Overall KPIs
		lineageTag: 1ca65ee9-e048-4a1a-b1f9-277f20c83eab

	measure '# Of Schools with 0 mentor visit' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] = 0 && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 8622d5a7-f261-4323-a41f-de60c6c177fd

	measure '# Of Schools with 1-3 mentor visits' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] IN {1,2,3} && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: 0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 752948f8-3ba9-4b3a-9761-63eff3c522ff

	measure '# Of Schools with 4-6 mentor visits' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] IN {4,5,6} && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 80a48a80-9ca5-494a-8a5d-0a10e5aa66b7

	measure '# Of Schools with 7+ mentor visits' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] >= 7 && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: #,0
		displayFolder: 1. Cycle specific KPIs
		lineageTag: 0aef0678-cc26-4def-847c-134ff7b34da3

	measure '# Of Schools where verification was done' =
			
			DISTINCTCOUNT( 'ASER Verification'[School ID] )
		formatString: 0
		lineageTag: a9949aad-d8fb-4dbc-ba40-7216ac0f02ab

	measure '% Of Schools where verification was done' =
			
			DIVIDE( [# Of Schools where verification was done], [# Of Schools Reached] )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 2671ca01-18dd-467d-bcb2-4d1ea11267b9

	measure '# Of Students reassessed' =
			
			COUNTROWS( 'ASER Verification' )
		formatString: #,0
		lineageTag: 51ed8e21-621e-43bc-9bb6-a8ec2ae78dfe

	measure '% Of Students reassessed' =
			
			DIVIDE( [# Of Students reassessed], [_# Of Students Reached In Program] )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 98d11783-c7b1-4d1e-b365-a601b6a9a1ae

	measure 'Title Overall cross-cheking' =
			
			"Overall Cross-Checking for " & MAX( 'Cross-Check Type'[Cross-Check Type] )
		lineageTag: 778f65d9-2e68-4c81-9c71-558bc5998706

	measure 'pp Of Literacy Difficulty Reduction From BL to EL (formated)' =
			
			VAR __EL = [% Of Students With Low Literacy At EL]
			VAR __BL = [% Of Students With Low Literacy At BL]
			VAR __Result = 100*(__BL - __EL)
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		displayFolder: 2. Program specific KPIs
		lineageTag: 609cc8da-c97a-40e9-aae2-6845e77e4453

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'pp Of Literacy Improvemnt From BL to EL (formated)' =
			
			VAR __EL = [% Of Students With High Literacy At EL]
			VAR __BL = [% Of Students With High Literacy At BL]
			VAR __Result = 100*(__EL - __BL)
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		displayFolder: 2. Program specific KPIs
		lineageTag: be186f14-99ea-401c-b04e-f8f2ef3041a2

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'pp Of Numeracy Difficulty Reduction From BL to EL (formated)' =
			
			VAR __EL = [% Of Students With Low Numeracy At EL]
			VAR __BL = [% Of Students With Low Numeracy At BL]
			VAR __Result = 100*(__BL - __EL)
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		displayFolder: 2. Program specific KPIs
		lineageTag: 9a531d57-9e7b-4599-bafa-083b57a73e21

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'pp Of Numeracy Improvemnt From BL to EL (formated)' =
			
			VAR __EL = [% Of Students With High Numeracy At EL]
			VAR __BL = [% Of Students With High Numeracy At BL]
			VAR __Result = 100*(__EL - __BL)
			RETURN IF( ISBLANK( __EL ), BLANK(), __Result )
		displayFolder: 2. Program specific KPIs
		lineageTag: 6291cc44-fee3-402f-8354-f9ea78b1debc

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'pp Of Subject Improvemnt From BL to EL (formated)' =
			
			// Doit etre filtree dans le rapport par Subject pour avoir du sens
			[pp Of Literacy Improvemnt From BL to EL (formated)] + [pp Of Numeracy Improvemnt From BL to EL (formated)]
		lineageTag: 870ed57b-23f9-4886-9011-3ea09b2faf25

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'Subject Improvemnt comment' =
			
			
			VAR __Subject = SELECTEDVALUE( 'Levels in Subjects'[Subject] )
			VAR __pp = [pp Of Subject Improvemnt From BL to EL (formated)]
			VAR __pp_formated =
			SWITCH( SIGN(__pp),
			        1, FORMAT( __pp, "+0 pp" ) & " increase",
			        -1, FORMAT( __pp, "-0 pp" ) & " decrease",
			        BLANK() )
			
			VAR __Comment = __pp_formated & " in number of students with high " & __Subject &  " from BL to EL"
			RETURN IF( ISBLANK( __pp ), BLANK(), __Comment )
		lineageTag: 68824b62-0ba2-4658-a203-95a6d0c4ad99

	measure 'Comment - Higher Levels across cycles' = ```
			
			
			VAR __Subject = SELECTEDVALUE( 'Levels in Subjects'[Subject ID] )
			
			VAR __BL =
			SWITCH( __Subject,
			        1, [% Of Students With High Literacy At BL],
			        2, [% Of Students With High Numeracy At BL],
			        BLANK() )
			        
			VAR __EL =
			SWITCH( __Subject,
			        1, [% Of Students With High Literacy At EL],
			        2, [% Of Students With High Numeracy At EL],
			        BLANK() )
			
			VAR __pp = [pp Of Subject Improvemnt From BL to EL (formated)]
			
			VAR __pp_target = 20
			
			VAR __pp_gap = __pp - __pp_target
			
			VAR __pp_formated =
			SWITCH( SIGN(__pp),
			        1, FORMAT( __pp, "+0 pp" ),
			        -1, FORMAT( __pp, "-0 pp" ),
			        BLANK() )
			
			VAR __Level = 
			SWITCH( __Subject,
			        1, "could read sentences",
			        2, "could solve at least a 2x2 substraction operation",
			        BLANK() )
			
			// Comment for higher levels improvment
			VAR __Line1 =
			UNICHAR(10) & "• " & FORMAT( __BL, "0%" ) & " of students " & __Level & " at Baseline"
			
			VAR __Line2 =
			SWITCH( TRUE(),
			        __EL > __BL, UNICHAR(10) & "• Increased to " & FORMAT( __EL, "0%" ) & " at Endline",
			        __EL < __BL, UNICHAR(10) & "• Decreased to " & FORMAT( __EL, "0%" ) & " at Endline",
			        __EL = __BL, UNICHAR(10) & "• Remain stable at Endline",
			        BLANK() )
			
			VAR __Line3 =
			UNICHAR(10) & "• The change in students who " & __Level & " was " & __pp_formated
			
			VAR __Line4 = 
			SWITCH( SIGN(__pp_gap),
			        1, UNICHAR(10) & "• The change was " & FORMAT( __pp_gap, "0 pp" ) & " more than the target, which was set as " & __pp_target & " pp",
			        -1, UNICHAR(10) & "• The change was " & FORMAT( __pp_gap, "0 pp" ) & " less than the target, which was set as " & __pp_target & " pp",
			        BLANK() )
			
			VAR Comment = __Line1 & __Line2 & __Line3 & __Line4
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year",
			   Comment )
			```
		lineageTag: f59347b9-e053-4716-aff7-c73a60e21741

	measure 'pp Of Subject Difficulty Reduction From BL to EL (formated)' =
			
			// Doit etre filtree dans le rapport par Subject pour avoir du sens
			[pp Of Literacy Difficulty Reduction From BL to EL (formated)] + [pp Of Numeracy Difficulty Reduction From BL to EL (formated)]
		lineageTag: 0ae81150-e0d4-4fd3-8c15-5849ef789e8c

		formatStringDefinition = "+0 pp;-0 pp;0 pp"

	measure 'Comment - High Literacy Progress across grades' = ```
			
			
			VAR __EL = [pp Of Literacy Improvemnt From BL to EL (formated)]
			VAR __Top_Grade = [Grade With Highest Literacy Improvement At EL]
			VAR __Bottom_Grade = [Grade With Lowest Literacy Improvement At EL]
			VAR __Top_Grade_Performance = [Highest Literacy Improvement across grades at EL]
			VAR __Bottom_Grade_Performance = [Lowest Literacy Improvement across grades at EL]
			VAR __Top_Grade_Performance_formated = FORMAT( 100 * __Top_Grade_Performance, "0 pp" )
			VAR __Bottom_Grade_Performance_formated = FORMAT( 100 * __Bottom_Grade_Performance, "0 pp" )
			VAR __List_Grades_Over_Target = [Grades With Literacy Improvement over 20pp]
			VAR __List_Grades_Under_Target = [Grades With Literacy Improvement under 20pp]
			VAR __Count_Grades = DISTINCTCOUNT( Grades[Grade] )
			VAR __Count_Grades_Over_Target = [# Of Grades With Literacy Improvement over 20pp]
			VAR __Count_Grades_Under_Target = [# Of Grades With Literacy Improvement under 20pp]
			
			VAR __Comment_Part1 = UNICHAR(10) & "• The best performance was seen in the " &  __Top_Grade & " class with " & __Top_Grade_Performance_formated & ". " & __Bottom_Grade & " was the class which performed the least with " & __Bottom_Grade_Performance_formated
			
			VAR __Comment_Part2 = 
			IF( __Count_Grades_Under_Target = 0,
			UNICHAR(10) & "• All grades meet the change target of 20 pp",
			UNICHAR(10) & "• " & __Count_Grades_Under_Target & " grade(s) out of " & __Count_Grades & " did not meet the change target of 20 pp : " & __List_Grades_Under_Target )
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
			```
		lineageTag: 5396fc62-6e58-4f31-8fb2-1d74e5080aae

	measure 'Grade With Highest Literacy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Literacy At EL] = __MaxValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: a883e1ce-cfe8-4cad-9078-ea9419c18e20

	measure 'Highest Literacy Improvement across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Literacy At EL] )
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 61e84125-c724-45ce-b2e2-3053d75a9a7e

	measure 'Grade With Lowest Literacy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Literacy At EL] = __MinValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 99e0ee6e-fe1b-4c8d-ae4c-1f593b9c5744

	measure 'Lowest Literacy Improvement across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Literacy At EL] )
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: afa6eb18-d658-4b2c-99bc-87a953c3665b

	measure 'Grades With Literacy Improvement over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: a7c4bf23-2c21-4bdf-8f87-7854d84b4988

	measure '# Of Grades With Literacy Improvement over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 60159c08-0255-42e2-88e4-324265b06447

	measure '# Of Grades With Literacy Improvement under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: ee312a97-900c-4b1e-b319-c6d103aa1c15

	measure 'Grades With Literacy Improvement under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: 50fe9205-e571-49b7-bdad-df46df2d0e41

	measure 'Comment - Low Literacy Reduction across grades' = ```
			
			
			VAR __EL = [pp Of Literacy Difficulty Reduction From BL to EL (formated)]
			VAR __Top_Grade = [Grade With Highest Literacy Difficulty Reduction At EL]
			VAR __Bottom_Grade = [Grade With Lowest Literacy Difficulty Reduction At EL]
			VAR __Top_Grade_Performance = [Highest Literacy Difficulty Reduction across grades at EL]
			VAR __Bottom_Grade_Performance = [Lowest Literacy Difficulty Reduction across grades at EL]
			VAR __Top_Grade_Performance_formated = FORMAT( 100 * __Top_Grade_Performance, "0 pp" )
			VAR __Bottom_Grade_Performance_formated = FORMAT( 100 * __Bottom_Grade_Performance, "0 pp" )
			VAR __List_Grades_Over_Target = [Grades With Subject Difficulty Reduction over 20pp]
			VAR __List_Grades_Under_Target = [Grades With Subject Difficulty Reduction under 20pp]
			VAR __Count_Grades = DISTINCTCOUNT( Grades[Grade] )
			VAR __Count_Grades_Over_Target = [# Of Grades With Subject Difficulty Reduction over 20pp]
			VAR __Count_Grades_Under_Target = [# Of Grades With Subject Difficulty Reduction under 20pp]
			
			
			VAR __Comment_Part1 = UNICHAR(10) & "• The best performance was seen in the " &  __Top_Grade & " class with " & __Top_Grade_Performance_formated & ". " & __Bottom_Grade & " was the class which performed the least with " & __Bottom_Grade_Performance_formated
			
			VAR __Comment_Part2 = 
			IF( __Count_Grades_Under_Target = 0,
			UNICHAR(10) & "• All grades meet the change target of 20 pp",
			UNICHAR(10) & "• " & __Count_Grades_Under_Target & " grade(s) out of " & __Count_Grades & " did not meet the change target of 20 pp : " & __List_Grades_Under_Target )
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
			```
		lineageTag: 1649d2ab-8e1d-442a-8494-96e898283f5a

	measure 'Grades With Subject Difficulty Reduction over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: b2c95dac-7827-438c-86cb-2741e2886d0c

	measure 'Grades With Subject Difficulty Reduction under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: eb2ce588-e304-4e18-b5a8-f1e67261eaa5

	measure '# Of Grades With Subject Difficulty Reduction over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 258476c6-58fd-4ec9-9bf1-bd4ae147d45b

	measure '# Of Grades With Subject Difficulty Reduction under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 1
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 3d36f290-fd1d-42b7-ada5-1768b6665c19

	measure 'Lowest Literacy Difficulty Reduction across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Literacy At EL] )
		lineageTag: 9ab600b1-bdf5-4a60-8d59-c428ff4f3de1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Literacy Difficulty Reduction across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Literacy At EL] )
		lineageTag: 9fea5c71-c3ae-4159-9d8c-0b3391a330fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Grade With Highest Literacy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Literacy At EL] = __MaxValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: 2c2a52c6-4ebd-4736-92e1-aed213aebf98

	measure 'Grade With Lowest Literacy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Literacy At EL] = __MinValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 8736e068-f679-4376-bfd6-6707a58dcb40

	measure 'Comment - High Numeracy Progress across grades' = ```
			
			
			VAR __EL = [pp Of Numeracy Improvemnt From BL to EL (formated)]
			VAR __Top_Grade = [Grade With Highest Numeracy Improvement At EL]
			VAR __Bottom_Grade = [Grade With Lowest Numeracy Improvement At EL]
			VAR __Top_Grade_Performance = [Highest Numeracy Improvement across grades at EL]
			VAR __Bottom_Grade_Performance = [Lowest Numeracy Improvement across grades at EL]
			VAR __Top_Grade_Performance_formated = FORMAT( 100 * __Top_Grade_Performance, "0 pp" )
			VAR __Bottom_Grade_Performance_formated = FORMAT( 100 * __Bottom_Grade_Performance, "0 pp" )
			VAR __List_Grades_Over_Target = [Grades With Numeracy Improvement over 20pp]
			VAR __List_Grades_Under_Target = [Grades With Numeracy Improvement under 20pp]
			VAR __Count_Grades = DISTINCTCOUNT( Grades[Grade] )
			VAR __Count_Grades_Over_Target = [# Of Grades With Numeracy Improvement over 20pp]
			VAR __Count_Grades_Under_Target = [# Of Grades With Numeracy Improvement under 20pp]
			
			VAR __Comment_Part1 = UNICHAR(10) & "• The best performance was seen in the " &  __Top_Grade & " class with " & __Top_Grade_Performance_formated & ". " & __Bottom_Grade & " was the class which performed the least with " & __Bottom_Grade_Performance_formated
			
			VAR __Comment_Part2 = 
			IF( __Count_Grades_Under_Target = 0,
			UNICHAR(10) & "• All grades meet the change target of 20 pp",
			UNICHAR(10) & "• " & __Count_Grades_Under_Target & " grade(s) out of " & __Count_Grades & " did not meet the change target of 20 pp : " & __List_Grades_Under_Target )
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
			```
		lineageTag: 30c66462-f369-438c-bf13-34f5030e838f

	measure 'Comment - Low Numeracy Reduction across grades' = ```
			
			
			VAR __EL = [pp Of Numeracy Difficulty Reduction From BL to EL (formated)]
			VAR __Top_Grade = [Grade With Highest Numeracy Difficulty Reduction At EL]
			VAR __Bottom_Grade = [Grade With Lowest Numeracy Difficulty Reduction At EL]
			VAR __Top_Grade_Performance = [Highest Numeracy Difficulty Reduction across grades at EL]
			VAR __Bottom_Grade_Performance = [Lowest Numeracy Difficulty Reduction across grades at EL]
			VAR __Top_Grade_Performance_formated = FORMAT( 100 * __Top_Grade_Performance, "0 pp" )
			VAR __Bottom_Grade_Performance_formated = FORMAT( 100 * __Bottom_Grade_Performance, "0 pp" )
			VAR __List_Grades_Over_Target = [Grades With Numeracy Difficulty Reduction over 20pp]
			VAR __List_Grades_Under_Target = [Grades With Numeracy Difficulty Reduction under 20pp]
			VAR __Count_Grades = DISTINCTCOUNT( Grades[Grade] )
			VAR __Count_Grades_Over_Target = [# Of Grades With Numeracy Difficulty Reduction over 20pp]
			VAR __Count_Grades_Under_Target = [# Of Grades With Numeracy Difficulty Reduction under 20pp]
			
			
			VAR __Comment_Part1 = UNICHAR(10) & "• The best performance was seen in the " &  __Top_Grade & " class with " & __Top_Grade_Performance_formated & ". " & __Bottom_Grade & " was the class which performed the least with " & __Bottom_Grade_Performance_formated
			
			VAR __Comment_Part2 = 
			IF( __Count_Grades_Under_Target = 0,
			UNICHAR(10) & "• All grades meet the change target of 20 pp",
			UNICHAR(10) & "• " & __Count_Grades_Under_Target & " grade(s) out of " & __Count_Grades & " did not meet the change target of 20 pp : " & __List_Grades_Under_Target )
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
			```
		lineageTag: 0f760bd5-5149-4c74-8d32-2d90e19fe72d

	measure 'Grade With Highest Numeracy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Numeracy At EL] = __MaxValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: cfe826e1-07e8-471e-9941-c6c40bbf3642

	measure 'Grade With Lowest Numeracy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Numeracy At EL] = __MinValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 99e325e3-581c-4ab3-8ab9-037218343888

	measure 'Highest Numeracy Improvement across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Numeracy At EL] )
		lineageTag: c4a513a8-e889-494d-b6a6-98dd49d94cfb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lowest Numeracy Improvement across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Numeracy At EL] )
		lineageTag: 87fa689e-b923-4374-ab04-d1f8866fab60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Grades With Numeracy Improvement over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: 56fedcdb-5cc4-404e-89bf-b7dd4c438b93

	measure '# Of Grades With Numeracy Improvement over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 84a83c4d-217a-4b8d-ba11-8f268410a3db

	measure 'Grades With Numeracy Improvement under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: c07ab8d9-824e-4aac-ae4b-c51aa11a48f6

	measure '# Of Grades With Numeracy Improvement under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Improvemnt From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 1f649957-f677-4518-8cf2-ab88fad8eca1

	measure 'Grade With Highest Numeracy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Numeracy At EL] = __MaxValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: 3bd6c467-ada8-485f-b915-c4aec2e8f956

	measure 'Grade With Lowest Numeracy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Numeracy At EL] = __MinValue ),
			        Grades[Grade]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: c41c1bb0-e843-42f1-8e1d-7bde301b534f

	measure 'Highest Numeracy Difficulty Reduction across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Numeracy At EL] )
		lineageTag: 1c5a6e48-44cf-47f5-8074-c611f3ea32ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lowest Numeracy Difficulty Reduction across grades at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[Grade] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Numeracy At EL] )
		lineageTag: af418b80-c4c5-460e-b5e1-192605a90880

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Grades With Numeracy Difficulty Reduction over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: 0e805c53-7471-4a23-8d13-6953b27c8fcf

	measure '# Of Grades With Numeracy Difficulty Reduction over 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] >= 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 72159a40-3b0f-4e69-9076-926321f9b2c3

	measure 'Grades With Numeracy Difficulty Reduction under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubject = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubject
			            )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX( __FilteredTable, Grades[Grade], ", ", Grades[Grade Sort], ASC )
			    )
		lineageTag: b3267ae7-772c-4078-ace1-68a87b62b0a6

	measure '# Of Grades With Numeracy Difficulty Reduction under 20pp' =
			
			VAR __CurrentPeriod = SELECTEDVALUE( Cycles[Period] )
			VAR __CurrentSubjectID = 2
			VAR __Table =
			    ADDCOLUMNS(
			        SUMMARIZE( Grades, Grades[Grade], Grades[Grade Sort] ),
			        "@pp Improvement",
			            CALCULATE(
			                [pp Of Subject Difficulty Reduction From BL to EL (formated)],
			                Cycles[Period] = __CurrentPeriod,
			                'Levels in Subjects'[Subject ID] = __CurrentSubjectID
			            )
			    )
			VAR __FilteredTable =
			    FILTER(
			        __Table,
			        NOT ISBLANK( [@pp Improvement] ) && [@pp Improvement] < 20
			    )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 4ce45ea8-081b-4493-825d-a03dbefa22e6

	measure 'Comment - Lower Levels across cycles' = ```
			
			
			VAR __Subject = SELECTEDVALUE( 'Levels in Subjects'[Subject ID] )
			
			VAR __BL2 =
			SWITCH( __Subject,
			        1, [% Of Students With Low Literacy At BL],
			        2, [% Of Students With Low Numeracy At BL],
			        BLANK() )
			
			VAR __EL2 =
			SWITCH( __Subject,
			        1, [% Of Students With Low Literacy At EL],
			        2, [% Of Students With Low Numeracy At EL],
			        BLANK() )
			
			VAR __pp2 = [pp Of Subject Difficulty Reduction From BL to EL (formated)]
			
			VAR __pp_target2 = -20
			
			VAR __pp_gap2 = __pp_target2 + __pp2
			
			VAR __pp_formated2 =
			SWITCH( SIGN(__pp2),
			        1, FORMAT( ABS(__pp2), "-0 pp" ),
			        -1, FORMAT( ABS(__pp2), "+0 pp" ),
			        BLANK() )
			
			VAR __Level2 = 
			SWITCH( __Subject,
			        1, "could not read words",
			        2, "could not recognise 2-digit numbers",
			        BLANK() )
			
			// Comment for lower levels reduction
			
			VAR __Line1_2 =
			UNICHAR(10) & "• " & FORMAT( __BL2, "0%" ) & " of students " & __Level2 & " at Baseline"
			
			VAR __Line2_2 =
			SWITCH( TRUE(),
			        __EL2 > __BL2, UNICHAR(10) & "• Increased to " & FORMAT( __EL2, "0%" ) & " at Endline",
			        __EL2 < __BL2, UNICHAR(10) & "• Reduced to " & FORMAT( __EL2, "0%" ) & " at Endline",
			        __EL2 = __BL2, UNICHAR(10) & "• Remain stable at Endline",
			        BLANK() )
			
			VAR __Line3_2 =
			UNICHAR(10) & "• The change in students who " & __Level2 & " was " & __pp_formated2
			
			VAR __Line4_2 = 
			SWITCH( SIGN(__pp_gap2),
			        1, UNICHAR(10) & "• The change was " & FORMAT( __pp_gap2, "0 pp" ) & " more than the target, which was set as " & __pp_target2 & " pp",
			        -1, UNICHAR(10) & "• The change was " & FORMAT( __pp_gap2, "0 pp" ) & " less than the target, which was set as " & __pp_target2 & " pp",
			        BLANK() )
			
			VAR Comment = __Line1_2 & __Line2_2 & __Line3_2 & __Line4_2
			
			RETURN IF( ISBLANK(__EL2),
			   "Endline data not available for the current year",
			   Comment )
			```
		lineageTag: 95384443-db47-47ac-b99a-67c4870924e2

	measure 'DRENAET With Highest Literacy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Literacy At EL] = __MaxValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: f44de116-2af6-4038-b9d1-7df3e6dec080

	measure 'DRENAET With Highest Literacy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Literacy At EL] = __MaxValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: 2e7cc223-853f-45ab-b193-398245b21b05

	measure 'DRENAET With Highest Numeracy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Numeracy At EL] = __MaxValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: 6eb7d96d-7bb2-43d4-be59-7cc462cc645c

	measure 'DRENAET With Highest Numeracy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			VAR __MaxValue =
			    MAXX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MAXX(
			        FILTER( __Table, [@Numeracy At EL] = __MaxValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MaxValue ), BLANK(), __Result )
		lineageTag: ca7e52cd-0d7f-4c72-b051-a1e498ba297e

	measure 'DRENAET With Lowest Literacy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Literacy At EL] = __MinValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 69a6e241-76b0-46e7-9860-b849a9072c00

	measure 'DRENAET With Lowest Literacy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Literacy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Literacy At EL] = __MinValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: cf2396df-40d9-4297-80d1-dab9d8278b69

	measure 'DRENAET With Lowest Numeracy Difficulty Reduction At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Numeracy At EL] = __MinValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 9bc9db32-0669-47bf-96dd-83864f60e391

	measure 'DRENAET With Lowest Numeracy Improvement At EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			VAR __MinValue =
			    MINX( __Table, [@Numeracy At EL] )
			VAR __Result =
			    MINX(
			        FILTER( __Table, [@Numeracy At EL] = __MinValue ),
			        Grades[DRENAET]
			    )
			RETURN
			    IF( ISBLANK( __MinValue ), BLANK(), __Result )
		lineageTag: 1fc16ba5-4f78-43d7-be4a-fd355db754be

	measure 'Highest Literacy Difficulty Reduction across DRENAETs at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Literacy At EL] )
		lineageTag: 1955ea6a-7745-49f4-9aa9-0fb4bff10ab6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Literacy Improvement across DRENAETs at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Literacy At EL] )
		lineageTag: 82fdd2de-d172-4577-86eb-6f7d96f403f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Numeracy Difficulty Reduction across DRENAETs at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Numeracy At EL] )
		lineageTag: 1fa7b635-c404-4f9c-b352-d5fa68681426

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highest Numeracy Improvement across DRENAETs at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			RETURN
			    MAXX( __Table, [@Numeracy At EL] )
		lineageTag: e2e27c4d-ce58-4888-8800-c655bc7e77a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Comment - Literacy Improvement across DRENAETs' =
			
			
			VAR __EL = [pp Of Literacy Improvemnt From BL to EL (formated)]
			VAR __Top_DRENAET = [DRENAET With Highest Literacy Improvement At EL]
			VAR __Bottom_DRENAET = [DRENAET With Lowest Literacy Improvement At EL]
			VAR __Top_DRENAET_Performance =  [Highest Literacy Improvement across DRENAETs at EL]
			VAR __Bottom_DRENAET_Performance = [Lowest Literacy Improvement across DRENAET at EL]
			VAR __Top_DRENAET_Performance_formated = FORMAT( 100 * __Top_DRENAET_Performance, "0 pp" )
			VAR __Bottom_DRENAET_Performance_formated = FORMAT( 100 * __Bottom_DRENAET_Performance, "0 pp" )
			
			VAR __Comment_Part1 = UNICHAR(10) & "• " & __Top_DRENAET & " showed the greatest improvement with " & __Top_DRENAET_Performance_formated
			
			VAR __Comment_Part2 = UNICHAR(10) & "• " & __Bottom_DRENAET & " showed the smallest improvement with " & __Bottom_DRENAET_Performance_formated
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: 3ac66c90-172f-4070-857e-4ae8b6659003

	measure 'Lowest Numeracy Difficulty Reduction across DRENAET at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Numeracy At EL] )
		lineageTag: 81ddd333-2b05-4230-949f-75ec8b69a2fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lowest Numeracy Improvement across DRENAETs at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Numeracy At EL] )
		lineageTag: 6f1e2edf-7c55-4405-bc77-7e8a088da4dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lowest Literacy Difficulty Reduction across DRENAET at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Difficulty Reduction From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Literacy At EL] )
		lineageTag: d6ab6bc8-4487-4795-89cc-9140cfa195c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lowest Literacy Improvement across DRENAET at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Literacy At EL", CALCULATE( [pp Of Literacy Improvemnt From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Literacy At EL] )
		lineageTag: 795dac53-c7af-486d-bbc0-76f54962450e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Comment - Literacy Difficulty Reduction across DRENAETs' =
			
			
			VAR __EL = [pp Of Literacy Difficulty Reduction From BL to EL (formated)]
			VAR __Top_DRENAET = [DRENAET With Highest Literacy Difficulty Reduction At EL]
			VAR __Bottom_DRENAET = [DRENAET With Lowest Literacy Difficulty Reduction At EL]
			VAR __Top_DRENAET_Performance = [Highest Literacy Difficulty Reduction across DRENAETs at EL]
			VAR __Bottom_DRENAET_Performance = [Lowest Literacy Difficulty Reduction across DRENAET at EL]
			VAR __Top_DRENAET_Performance_formated = FORMAT( 100 * __Top_DRENAET_Performance, "0 pp" )
			VAR __Bottom_DRENAET_Performance_formated = FORMAT( 100 * __Bottom_DRENAET_Performance, "0 pp" )
			
			VAR __Comment_Part1 = UNICHAR(10) & "• " & __Top_DRENAET & " showed the greatest improvement with " & __Top_DRENAET_Performance_formated
			
			VAR __Comment_Part2 = UNICHAR(10) & "• " & __Bottom_DRENAET & " showed the smallest improvement with " & __Bottom_DRENAET_Performance_formated
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: b55b4e84-e89d-4a33-93a4-486855274a6c

	measure 'Comment - Numeracy Improvement across DRENAETs' =
			
			
			VAR __EL = [pp Of Numeracy Improvemnt From BL to EL (formated)]
			VAR __Top_DRENAET = [DRENAET With Highest Numeracy Improvement At EL]
			VAR __Bottom_DRENAET = [DRENAET With Lowest Numeracy Improvement At EL]
			VAR __Top_DRENAET_Performance =  [Highest Numeracy Improvement across DRENAETs at EL]
			VAR __Bottom_DRENAET_Performance = [Lowest Numeracy Improvement across DRENAET at EL]
			VAR __Top_DRENAET_Performance_formated = FORMAT( 100 * __Top_DRENAET_Performance, "0 pp" )
			VAR __Bottom_DRENAET_Performance_formated = FORMAT( 100 * __Bottom_DRENAET_Performance, "0 pp" )
			
			VAR __Comment_Part1 = UNICHAR(10) & "• " & __Top_DRENAET & " showed the greatest improvement with " & __Top_DRENAET_Performance_formated
			
			VAR __Comment_Part2 = UNICHAR(10) & "• " & __Bottom_DRENAET & " showed the smallest improvement with " & __Bottom_DRENAET_Performance_formated
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: 15828600-2dd5-468b-bf1d-2997e8fa0054

	measure 'Lowest Numeracy Improvement across DRENAET at EL' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Numeracy At EL", CALCULATE( [pp Of Numeracy Improvemnt From BL to EL] )
			    )
			RETURN
			    MINX( __Table, [@Numeracy At EL] )
		lineageTag: 9b4d19a8-2da3-477d-bc65-da3c06b4c9b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Comment - Numeracy Difficulty Reduction across DRENAETs' =
			
			
			VAR __EL = [pp Of Numeracy Difficulty Reduction From BL to EL (formated)]
			VAR __Top_DRENAET = [DRENAET With Highest Numeracy Difficulty Reduction At EL]
			VAR __Bottom_DRENAET = [DRENAET With Lowest Numeracy Difficulty Reduction At EL]
			VAR __Top_DRENAET_Performance = [Highest Numeracy Difficulty Reduction across DRENAETs at EL]
			VAR __Bottom_DRENAET_Performance = [Lowest Numeracy Difficulty Reduction across DRENAET at EL]
			VAR __Top_DRENAET_Performance_formated = FORMAT( 100 * __Top_DRENAET_Performance, "0 pp" )
			VAR __Bottom_DRENAET_Performance_formated = FORMAT( 100 * __Bottom_DRENAET_Performance, "0 pp" )
			
			VAR __Comment_Part1 = UNICHAR(10) & "• " & __Top_DRENAET & " showed the greatest improvement with " & __Top_DRENAET_Performance_formated
			
			VAR __Comment_Part2 = UNICHAR(10) & "• " & __Bottom_DRENAET & " showed the smallest improvement with " & __Bottom_DRENAET_Performance_formated
			
			VAR __Full_Comment = __Comment_Part1 & __Comment_Part2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: 8d405067-75b6-4c60-bef1-ca3cf6b295c5

	measure 'Comment - School Literacy Progress across DRENAETs' =
			
			
			VAR __EL = [pp Of Literacy Improvemnt From BL to EL (formated)]
			VAR __Top2_Lowest_Red_Schools = [Top 2 DRENAETs With Lowest % Of Red Schools For Literacy]
			VAR __Top2_Highest_Red_Schools = [Top 2 DRENAETs With Highest % Of Red Schools For Literacy]
			VAR __Overall_Red_Schools_Percentage = FORMAT( [% Of Red Schools For Literacy], "0%" )
			VAR __Overall_Lower_Yellow_Schools_Percentage = FORMAT( [% Of Lower Yellow Schools For Literacy], "0%" )
			VAR __Overall_Inter_Yellow_Schools_Percentage = FORMAT( [% Of Intermediate Yellow Schools For Literacy], "0%" )
			VAR __Overall_Upper_Yellow_Schools_Percentage = FORMAT( [% Of Upper Yellow Schools For Literacy], "0%" )
			VAR __Overall_Green_Schools_Percentage = FORMAT ( [% Of Green Schools For Literacy], "0%" )
			
			
			VAR __Comment_Line1 = UNICHAR(10) & "• " & __Top2_Lowest_Red_Schools & " are the DRENAETs with the fewest percentage of red schools"
			
			VAR __Comment_Line2 = UNICHAR(10) & "• " & __Top2_Highest_Red_Schools & " are the DRENAETs with the highest percentage of red schools"
			
			VAR __Comment_Line3 = UNICHAR(10) & UNICHAR(10) & "• Overall, there are " & __Overall_Red_Schools_Percentage & " red schools, " & __Overall_Lower_Yellow_Schools_Percentage & " lower yellow schools, " & __Overall_Inter_Yellow_Schools_Percentage & " intermediate yellow schools, " & __Overall_Upper_Yellow_Schools_Percentage & " upper yellow schools, and " & __Overall_Green_Schools_Percentage & " green schools"
			
			VAR __Full_Comment = __Comment_Line1 & __Comment_Line2 & __Comment_Line3
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: 610820a0-e509-42f2-a3a2-f9e51bd9484e

	measure 'Top 2 DRENAETs With Lowest % Of Red Schools For Literacy' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Red Schools For Literacy] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Pct], ASC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0%" ) & ")",
			            " and ",
			            [@Pct], ASC
			        )
			    )
		lineageTag: 9a810743-28bb-41a6-9f7f-3c3239904517

	measure '% Of Red Schools For Literacy' =
			
			DIVIDE( [# Of Red schools for Literacy],
			        [# Of Schools classified for Literacy Progress]  )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: f95cad89-ea00-4603-8ff2-df06e9992f34

	measure '% Of Lower Yellow Schools For Literacy' =
			
			DIVIDE( [# Of Lower Yellow schools for Literacy],
			        [# Of Schools classified for Literacy Progress]  )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: c155e824-12e2-43de-aa29-14842ebef9ab

	measure '% Of Green Schools For Literacy' =
			
			DIVIDE( [# Of Green schools for Literacy],
			        [# Of Schools classified for Literacy Progress]  )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: ffaf2665-5eca-4fb3-8c30-ae582cac8499

	measure '# Of Schools classified for Literacy Progress' = ```
			
			    [# Of Red schools for Literacy] +
			    [# Of Lower Yellow schools for Literacy] +
			    [# Of Intermediate Yellow schools for Literacy] +
			    [# Of Upper Yellow schools for Literacy] +
			    [# Of Green schools for Literacy]
			```
		formatString: 0
		lineageTag: 133b713a-265b-4152-8001-bf3ffc3cf790

	measure 'Top 2 DRENAETs With Highest % Of Red Schools For Literacy' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Red Schools For Literacy] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Pct], DESC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0%" ) & ")",
			            " and ",
			            [@Pct], DESC
			        )
			    )
		lineageTag: fd50aee3-9818-4753-adf1-6f938a05104d

	measure 'Comment - School Numeracy Progress across DRENAETs' =
			
			
			VAR __EL = [pp Of Numeracy Improvemnt From BL to EL (formated)]
			VAR __Top2_Lowest_Red_Schools = [Top 2 DRENAETs With Lowest % Of Red Schools For Numeracy]
			VAR __Top2_Highest_Red_Schools = [Top 2 DRENAETs With Highest % Of Red Schools For Numeracy]
			VAR __Overall_Red_Schools_Percentage = FORMAT( [% Of Red Schools For Numeracy], "0%" )
			VAR __Overall_Lower_Yellow_Schools_Percentage = FORMAT( [% Of Lower Yellow Schools For Numeracy], "0%" )
			VAR __Overall_Inter_Yellow_Schools_Percentage = FORMAT( [% Of Intermediate Yellow Schools For Numeracy], "0%" )
			VAR __Overall_Upper_Yellow_Schools_Percentage = FORMAT( [% Of Upper Yellow Schools For Numeracy], "0%" )
			VAR __Overall_Green_Schools_Percentage = FORMAT ( [% Of Green Schools For Numeracy], "0%" )
			
			
			VAR __Comment_Line1 = UNICHAR(10) & "• " & __Top2_Lowest_Red_Schools & " are the DRENAETs with the smallest percentage of red schools"
			
			VAR __Comment_Line2 = UNICHAR(10) & "• " & __Top2_Highest_Red_Schools & " are the DRENAETs with the highest percentage of red schools"
			
			VAR __Comment_Line3 = UNICHAR(10) & UNICHAR(10) & "• Overall, there are " & __Overall_Red_Schools_Percentage & " red schools, " & __Overall_Lower_Yellow_Schools_Percentage & " lower yellow schools, " & __Overall_Inter_Yellow_Schools_Percentage & " intermediate yellow schools, " & __Overall_Upper_Yellow_Schools_Percentage & " upper yellow schools, and " & __Overall_Green_Schools_Percentage & " green schools"
			
			VAR __Full_Comment = __Comment_Line1 & __Comment_Line2 & __Comment_Line3
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
		lineageTag: 95f5e865-9ac6-4390-982c-52fe8eb2afb7

	measure 'Top 2 DRENAETs With Lowest % Of Red Schools For Numeracy' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Red Schools For Numeracy] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Pct], ASC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0%" ) & ")",
			            " and ",
			            [@Pct], ASC
			        )
			    )
		lineageTag: 794f5b9e-393c-4a9e-a94d-213971190532

	measure '# Of Schools classified for Numeracy Progress' = ```
			
			    [# Of Red schools for Numeracy] +
			    [# Of Lower Yellow schools for Numeracy] +
			    [# Of Intermediate Yellow schools for Numeracy] +
			    [# Of Upper Yellow schools for Numeracy] +
			    [# Of Green schools for Numeracy]
			```
		formatString: 0
		lineageTag: 3bf89e1b-b204-41d7-b7ae-bd22aca4437b

	measure '% Of Red Schools For Numeracy' =
			
			DIVIDE( [# Of Red schools for Numeracy],
			        [# Of Schools classified for Numeracy Progress]  )
		lineageTag: d8e9960a-f61d-474f-9f85-566aa875446f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Of Green Schools For Numeracy' =
			
			DIVIDE( [# Of Green schools for Numeracy],
			        [# Of Schools classified for Numeracy Progress]  )
		lineageTag: 5caa680e-1b07-437d-8af2-b73230fade1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Of Lower Yellow Schools For Numeracy' =
			
			DIVIDE( [# Of Lower Yellow schools for Numeracy],
			        [# Of Schools classified for Numeracy Progress]  )
		lineageTag: 7ef8beb0-bccf-4148-8d26-55f2790cc940

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top 2 DRENAETs With Highest % Of Red Schools For Numeracy' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Red Schools For Numeracy] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Pct], DESC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0%" ) & ")",
			            " and ",
			            [@Pct], DESC
			        )
			    )
		lineageTag: 1c5bb673-576c-4ea2-a12e-67dc0c9f2f5b

	measure 'Average Number Of Mentoring School Visits BL-ML' =
			
			CALCULATE( [Average Number Of Mentoring School Visits], Cycles[Cycle] = "ML" )
		formatString: 0.00
		lineageTag: 8c3ef596-bc9d-4063-aa1d-6f20778b0aa6

	measure 'Average Number Of Mentoring School Visits ML-EL' =
			
			CALCULATE( [Average Number Of Mentoring School Visits], Cycles[Cycle] = "EL" )
		formatString: 0.00
		lineageTag: e88d5eb9-b8ea-4ac5-af5c-30e2d1122a3e

	measure 'Average Number Of Mentoring School Visits Change across cycles' =
			
			[Average Number Of Mentoring School Visits ML-EL] - [Average Number Of Mentoring School Visits BL-ML]
		formatString: 0.00
		lineageTag: 8a932011-af47-4723-8ad9-09ce647cca27

	measure 'Average Number Of Mentoring School Visits Gap across Group' =
			
			
			VAR __CPPP_Average =
			CALCULATE( [Average Number Of Mentoring School Visits],
			        'Mentoring Visits'[Visit Type] = "Mentoring Visit (CPPP)" )
			
			VAR __Other_Average =
			CALCULATE( [Average Number Of Mentoring School Visits],
			        'Mentoring Visits'[Visit Type] = "Other Mentoring Visit" )
			
			RETURN __CPPP_Average - __Other_Average
		formatString: 0.00
		lineageTag: e49e3c26-a01d-43cf-8cfb-a48fb81ca0f5

	measure 'Average Number Of Mentoring School Visits Gap across Group BL-ML' =
			
			CALCULATE( [Average Number Of Mentoring School Visits Gap across Group], Cycles[Cycle] = "ML" )
		formatString: 0.00
		lineageTag: 36d013f5-6a8e-4f0a-a31e-c8fb96e265a9

	measure 'Average Number Of Mentoring School Visits Gap across Group ML-EL' =
			
			CALCULATE( [Average Number Of Mentoring School Visits Gap across Group], Cycles[Cycle] = "EL" )
		formatString: 0.00
		lineageTag: 360beb1b-d746-4a6e-a52a-040a830ccc91

	measure 'Comment - Mentor Visits across Cycles' = ```
			
			
			VAR __EL = [Average Number Of Mentoring School Visits ML-EL]
			VAR __Gap_ML = [Average Number Of Mentoring School Visits Gap across Group BL-ML]
			VAR __Gap_EL = [Average Number Of Mentoring School Visits Gap across Group ML-EL]
			VAR __Change_CPPP = [Average Number Of Mentoring School Visits Change across cycles for CPPP]
			VAR __Change_Other_group = [Average Number Of Mentoring School Visits Change across cycles for Other group]
			VAR __Change_CPPP_formated = FORMAT( __Change_CPPP, "0.00" )
			VAR __Change_Other_group_formated = FORMAT( __Change_Other_group, "0.00" )
			
			VAR __Comment_Line1 = 
			SWITCH( TRUE(),
			       __Gap_ML > 0 && __Gap_EL > 0, UNICHAR(10) & "• Overall, the average number of visits is greater for CPPP group than other mentoring groups",
			
			       __Gap_ML > 0 && __Gap_EL < 0, UNICHAR(10) & "• The average number of visits was greater for CPPP group than other mentoring groups only in the first phase",
			
			       __Gap_ML < 0 && __Gap_EL > 0, UNICHAR(10) & "• The average number of visits was greater for CPPP group than other mentoring groups only in the second phase",
			
			       __Gap_ML < 0 && __Gap_EL < 0, UNICHAR(10) & "• Overall, the average number of visits is smaller for CPPP group than other mentoring groups",
			
			      BLANK()
			)
			
			VAR __Comment_Line2 = 
			SWITCH( TRUE(),
			       __Change_CPPP > 0 && __Change_Other_group > 0, UNICHAR(10) & "• Between the two phases, the average number of visits increased for both CPPP(+" & __Change_CPPP_formated  & ") and Other mentoring groups(+" & __Change_Other_group_formated & ")",
			
			       __Change_CPPP > 0 && __Change_Other_group < 0, UNICHAR(10) & "• Between the two phases, the average number of visits increased for CPPP(+" & __Change_CPPP_formated  & "), but not for Other mentoring groups(" & __Change_Other_group_formated & ")",
			
			       __Change_CPPP < 0 && __Change_Other_group > 0, UNICHAR(10) & "• Between the two phases, the average number of visits increased for Other mentoring groups(+" & __Change_Other_group_formated  & "), but not for CPPP (" & __Change_CPPP_formated & ")",
			
			       __Change_CPPP < 0 && __Change_Other_group < 0, UNICHAR(10) & "• Between the two phases, the average number of visits decreased for both CPPP(" & __Change_CPPP_formated  & ") and Other mentoring groups(" & __Change_Other_group_formated & ")",
			       
			      BLANK()
			)
			
			VAR __Full_Comment = __Comment_Line1 & __Comment_Line2
			
			RETURN IF( ISBLANK(__EL),
			   "Endline data not available for the current year", __Full_comment )
			```
		lineageTag: 72c9b9c1-096f-47f3-8060-aae6fb1a0873

	measure 'Average Number Of Mentoring School Visits Change across cycles for CPPP' =
			
			CALCULATE( [Average Number Of Mentoring School Visits Change across cycles],
			           'Mentoring Visits'[Visit Type] = "Mentoring Visit (CPPP)" )
		formatString: 0.00
		lineageTag: ab5946c5-aea2-4353-b82a-9aacf011a5e9

	measure 'Average Number Of Mentoring School Visits Change across cycles for Other group' =
			
			CALCULATE( [Average Number Of Mentoring School Visits Change across cycles],
			           'Mentoring Visits'[Visit Type] = "Other Mentoring Visit" )
		formatString: 0.00
		lineageTag: dad487a3-ee80-4ecf-9d4c-83eaca975deb

	measure 'DRENAETs With More Other Mentoring Visits than CPPP Visits' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Gap", CALCULATE( [Average Number Of Mentoring School Visits Gap across Group] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Gap] ) && [@Gap] < 0 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX(
			            __FilteredTable,
			            Grades[DRENAET] & " (" & FORMAT( -1 * [@Gap], "+0.00" ) & ")",
			            " and ",
			            [@Gap], ASC
			        )
			    )
		lineageTag: a6d23385-1df1-4538-8ee6-78009285a95a

	measure 'Comment - Mentor Visits across DRENAETs' = ```
			
			
			VAR __Avg = [Average Number Of Mentoring School Visits]
			VAR __Count_Other_Group_DRENAET = [# Of DRENAETs With More Other Mentoring Visits than CPPP Visits]
			VAR __List_Other_Group_DRENAET = [DRENAETs With More Other Mentoring Visits than CPPP Visits]
			VAR __Top2_CPPP_DRENAET = [Top 2 DRENAETs With Highest Average Number Of CPPP Visits]
			VAR __Top2_Other_Group_DRENAET = [Top 2 DRENAETs With Highest Average Number Of Other Mentoring Group Visits]
			
			VAR __Comment_Line1 = UNICHAR(10) & "• " & __Top2_CPPP_DRENAET & " stand out as the DRENAETs with the most intensive monitoring by CPPP group."
			
			VAR __Comment_Line2 = UNICHAR(10) & "• " & __Top2_Other_Group_DRENAET & " stand out as the DRENAETs with the most intensive monitoring by Other monitoring groups."
			
			VAR __Comment_Line3 = 
			SWITCH( TRUE(),
			     __Count_Other_Group_DRENAET = 1, UNICHAR(10) & "• There is 1 DRENAET where the average number of other mentoring visits is higher than CPPP visits: " & __List_Other_Group_DRENAET,
			     __Count_Other_Group_DRENAET > 1, UNICHAR(10) & "• There are " &  __Count_Other_Group_DRENAET & " DRENAETs where the average number of other mentoring visits is higher than CPPP visits: " & __List_Other_Group_DRENAET,
			    BLANK() )
			
			VAR __Full_Comment = __Comment_Line1 & __Comment_Line2 & __Comment_Line3
			
			RETURN IF( ISBLANK(__Avg),
			   "Data not available for the current cycle", __Full_comment )
			```
		lineageTag: fd557e82-73d0-452c-a179-a64b9b1d3129

	measure '# Of DRENAETs With More Other Mentoring Visits than CPPP Visits' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Gap", CALCULATE( [Average Number Of Mentoring School Visits Gap across Group] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Gap] ) && [@Gap] < 0 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 1d58472e-5a78-410f-b78a-521cd3dc1145

	measure 'Top 2 DRENAETs With Highest Average Number Of Mentoring School Visits' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Avg", CALCULATE( [Average Number Of Mentoring School Visits] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Avg] ) )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Avg], DESC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Avg], "0.00" ) & ")",
			            " and ",
			            [@Avg], DESC
			        )
			    )
		lineageTag: 4de99bb0-7339-47a8-b7e0-03d91574b632

	measure 'Top 2 DRENAETs With Highest Average Number Of CPPP Visits' =
			
			CALCULATE( [Top 2 DRENAETs With Highest Average Number Of Mentoring School Visits],
			            'Mentoring Visits'[Visit Type] = "Mentoring Visit (CPPP)" )
		lineageTag: 3ff2bba2-446c-44f3-af4c-84633287c58f

	measure 'Top 2 DRENAETs With Highest Average Number Of Other Mentoring Group Visits' =
			
			CALCULATE( [Top 2 DRENAETs With Highest Average Number Of Mentoring School Visits],
			            'Mentoring Visits'[Visit Type] = "Other Mentoring Visit" )
		lineageTag: 7be1ed0a-4a1b-49ae-ab73-89c48a0f24d4

	measure 'Comment - Mentor Visits per School across DRENAETs' = ```
			
			
			VAR __Visits = [# Of Visits]
			VAR __Zero_Visits_Pct = FORMAT( [% Of Schools with 0 mentor visit], "0%" )
			VAR __One_Or_More_Visits_DRENAET_Pct = FORMAT( [% Of Schools with at least 1 mentor visit], "0%" )
			VAR __Seven_Or_More_Visits_DRENAET = [# Of DRENAETs Where % Of Schools With At Least 7 Mentor Visits is greater than 0]
			VAR __List_Seven_Or_More_Visits_DRENAET = [DRENAETs Where % Of Schools With At Least 7 Mentor Visits is greater than 0]
			VAR __Top2_Seven_Or_More_Visits_DRENAET = [Top 2 DRENAETs With Highest % Of Schools With At Least 7 Mentor Visits]
			
			
			VAR __Comment_Line1 = UNICHAR(10) & "• Overall, " & __Zero_Visits_Pct & " of schools had 0 mentor visit, and " & __One_Or_More_Visits_DRENAET_Pct & " had at least 1"
			
			VAR __Comment_Line2 =
			SWITCH ( TRUE(),
			   __Seven_Or_More_Visits_DRENAET = 0,
			   UNICHAR(10) & "• There is no DRENAET where a school had at least 7 mentor visits",
			
			   __Seven_Or_More_Visits_DRENAET = 1, 
			   UNICHAR(10) & "• There only 1 DRENAET with schools which had at least 7 mentor visits: " & __List_Seven_Or_More_Visits_DRENAET,
			
			   __Seven_Or_More_Visits_DRENAET > 1,
			   UNICHAR(10) & "• There are " & __Seven_Or_More_Visits_DRENAET & " DRENAETs with schools which had at least 7 mentor visits, including " & __Top2_Seven_Or_More_Visits_DRENAET,
			
			   BLANK() )
			
			VAR __Full_Comment = __Comment_Line1 & __Comment_Line2
			
			RETURN 
			IF( ISBLANK(__Visits),
			   "No data available for the current cycle", __Full_comment )
			```
		lineageTag: 2d55023c-0632-4c5a-86e4-d7ecfd209989

	measure '# Of Schools with at least 1 mentor visit' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] >= 1 && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: 0
		lineageTag: d85dba7f-afc4-4e89-986b-651b53f78539

	measure '% Of Schools with 0 mentor visit' =
			
			DIVIDE( [# Of Schools with 0 mentor visit], [# Of Schools Reached] )
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: d110cbf0-e8aa-4ef8-8ae7-df4fe845f550

	measure '% Of Schools with at least 1 mentor visit' =
			
			DIVIDE( [# Of Schools with at least 1 mentor visit], [# Of Schools Reached] )
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 0ec64842-90fc-461d-9be4-9a87acc28ed6

	measure '# Of Schools with at least 7 mentor visits' = ```
			
			
			VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
			VAR __CurrentCycleSort = MAX( Cycles[Cycle Sort] )
			
			VAR __Visits =
			SUMMARIZE(
				'ASER CIV Data',
				'ASER CIV Data'[Cycle ID],
				'ASER CIV Data'[School ID],
				"@Visits", [# Of Visits]
			)
			
			VAR __Filtered_Visits = 
			FILTER( __Visits, [@Visits] >= 7 && 'ASER CIV Data'[Cycle ID] = __CurrentCycle )
			
			VAR __Result = COUNTROWS( __Filtered_Visits )
			RETURN IF( __CurrentCycleSort = 1, BLANK(), __Result )
			```
		formatString: 0
		lineageTag: bbd7a1cf-1b58-42e8-8faa-7e039068cf74

	measure '% Of Schools with at least 7 mentor visits' =
			
			DIVIDE( [# Of Schools with at least 7 mentor visits], [# Of Schools Reached] )
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 672cefb3-3a4b-49fa-a675-9df4e9893d22

	measure 'DRENAETs Where % Of Schools With At Least 7 Mentor Visits is greater than 0' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Schools with at least 7 mentor visits] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        CONCATENATEX(
			            __FilteredTable,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0.0%" ) & ")",
			            ", ",
			            [@Pct], DESC
			        )
			    )
		lineageTag: 1de9eb19-d4aa-48ad-be58-1dacf43b4942

	measure '# Of DRENAETs Where % Of Schools With At Least 7 Mentor Visits is greater than 0' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Schools with at least 7 mentor visits] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			RETURN
			    IF(
			        ISEMPTY( __FilteredTable ),
			        BLANK(),
			        COUNTROWS( __FilteredTable )
			    )
		formatString: 0
		lineageTag: 2d8c4d7a-cdd2-4286-97e3-3ba6527848b9

	measure 'Top 2 DRENAETs With Highest % Of Schools With At Least 7 Mentor Visits' =
			
			VAR __Table =
			    ADDCOLUMNS(
			        VALUES( Grades[DRENAET] ),
			        "@Pct", CALCULATE( [% Of Schools with at least 7 mentor visits] )
			    )
			VAR __FilteredTable =
			    FILTER( __Table, NOT ISBLANK( [@Pct] ) && [@Pct] > 0 )
			VAR __Top2 =
			    TOPN( 2, __FilteredTable, [@Pct], DESC )
			RETURN
			    IF(
			        ISEMPTY( __Top2 ),
			        BLANK(),
			        CONCATENATEX(
			            __Top2,
			            Grades[DRENAET] & " (" & FORMAT( [@Pct], "0%" ) & ")",
			            " and ",
			            [@Pct], DESC
			        )
			    )
		lineageTag: 9a9f9cc9-28e0-4f76-a16f-6907f903ac2f

	measure '# Of Intermediate Yellow schools for Literacy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Literacy Status", SWITCH(
						TRUE(),
						[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Literacy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Literacy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Literacy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Literacy Status] = "Intermediate Yellow school (15-20pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: 0
		lineageTag: 16eee632-640d-4d21-9176-fa82124e1c80

	measure '# Of Upper Yellow schools for Literacy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Literacy Status", SWITCH(
						TRUE(),
						[@Progress in Literacy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Literacy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Literacy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Literacy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Literacy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Literacy Status] = "Upper Yellow school (20-25pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: 0
		lineageTag: 537a0c8f-4fc8-425f-94d4-092dc83117e7

	measure '% Of Intermediate Yellow Schools For Literacy' =
			
			DIVIDE( [# Of Intermediate Yellow schools for Literacy],
			        [# Of Schools classified for Literacy Progress]  )
		lineageTag: 6dc5698f-9b77-4491-8994-8769c0af89e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Of Upper Yellow Schools For Literacy' =
			
			DIVIDE( [# Of Upper Yellow schools for Literacy],
			        [# Of Schools classified for Literacy Progress]  )
		lineageTag: 60560e70-4362-4895-a09f-26fe976b2677

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# Of Intermediate Yellow schools for Numeracy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Numeracy Status", SWITCH(
						TRUE(),
						[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Numeracy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Numeracy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Numeracy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Numeracy Status] = "Intermediate Yellow school (15-20pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: 0
		lineageTag: e18e86df-3197-48f8-a6fd-057925351060

	measure '# Of Upper Yellow schools for Numeracy' =
			
				VAR __BaseTable = SUMMARIZE(
					'ASER CIV Data',
					'ASER CIV Data'[School ID],
					'ASER CIV Data'[Period],
					"@Progress in Literacy from BL to EL", [pp Of Literacy Improvemnt From BL to EL],
					"@Progress in Numeracy from BL to EL", [pp Of Numeracy Improvemnt From BL to EL]
				)
			
				VAR __Table = SELECTCOLUMNS(
					__BaseTable,
					"@School ID", 'ASER CIV Data'[School ID],
					"@Period", 'ASER CIV Data'[Period],
					"@Numeracy Status", SWITCH(
						TRUE(),
						[@Progress in Numeracy from BL to EL] = BLANK(), BLANK(),
						[@Progress in Numeracy from BL to EL] < 0.1, "Red school (0-10pp)",
						[@Progress in Numeracy from BL to EL] < 0.15, "Lower Yellow school (10-15pp)",
						[@Progress in Numeracy from BL to EL] < 0.20, "Intermediate Yellow school (15-20pp)",
						[@Progress in Numeracy from BL to EL] < 0.25, "Upper Yellow school (20-25pp)",
						"Green school (>25pp)"
					)
				)
			
				VAR __Yellow_Schools = FILTER(
					__Table,
					[@Numeracy Status] = "Upper Yellow school (20-25pp)"
				)
			
			    VAR __Result = COUNTROWS( __Yellow_Schools )
			
			    RETURN __Result
		formatString: 0
		lineageTag: bfb40fc9-3ad8-4475-aa5a-620afb059931

	measure '% Of Intermediate Yellow Schools For Numeracy' =
			
			DIVIDE( [# Of Intermediate Yellow schools for Numeracy],
			        [# Of Schools classified for Numeracy Progress]  )
		lineageTag: b8548ee9-ecc1-4a6f-8814-3f650e6693c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Of Upper Yellow Schools For Numeracy' =
			
			DIVIDE( [# Of Upper Yellow schools for Numeracy],
			        [# Of Schools classified for Numeracy Progress]  )
		lineageTag: 78d09007-eb10-417b-8259-66a4ef47b9cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Mesures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Colonnes supprimées" = Table.RemoveColumns(Source,{"Colonne 1"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

