createOrReplace

	model Model
		culture: fr-FR
		defaultPowerBIDataSourceVersion: powerBI_V3
		discourageImplicitMeasures
		sourceQueryCulture: fr-FR
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table 'ASER CIV Data'
			lineageTag: 2271c66e-66ce-4fa7-a6bc-86fce794e533

			column 'Students In Class'
				dataType: int64
				formatString: 0
				lineageTag: c0c0f07e-57ed-4395-a1a3-9d914446917a
				summarizeBy: sum
				sourceColumn: Students In Class

				annotation SummarizationSetBy = Automatic

			column 'Boys Tested In Class'
				dataType: int64
				formatString: 0
				lineageTag: 7b691fbe-bd2d-45ed-a82f-bcf0078af5c2
				summarizeBy: sum
				sourceColumn: Boys Tested In Class

				annotation SummarizationSetBy = Automatic

			column 'Girls Tested In Class'
				dataType: int64
				formatString: 0
				lineageTag: ff503c80-a725-42d3-8949-ae2c77ba76e5
				summarizeBy: sum
				sourceColumn: Girls Tested In Class

				annotation SummarizationSetBy = Automatic

			column 'Students Tested In Class'
				dataType: int64
				formatString: 0
				lineageTag: 4c788f5a-a377-4a3b-b867-1f2291cc30c0
				summarizeBy: sum
				sourceColumn: Students Tested In Class

				annotation SummarizationSetBy = Automatic

			column 'Teacher Male In School'
				dataType: int64
				formatString: 0
				lineageTag: 2b9779c5-cf30-4062-9cfc-6c2cda370ff5
				summarizeBy: sum
				sourceColumn: Teacher Male In School

				annotation SummarizationSetBy = Automatic

			column 'Teacher Female In School'
				dataType: int64
				formatString: 0
				lineageTag: 8a4e7a0b-fe18-4ea2-bccc-36697874f991
				summarizeBy: sum
				sourceColumn: Teacher Female In School

				annotation SummarizationSetBy = Automatic

			column 'Students At Level'
				dataType: int64
				formatString: 0
				lineageTag: 99971a1a-6f6a-4972-a065-83b58b2b625f
				summarizeBy: sum
				sourceColumn: Students At Level

				annotation SummarizationSetBy = Automatic

			column 'Grade ID'
				dataType: int64
				formatString: 0
				lineageTag: 667b7477-273a-49ab-84e7-72d986743ab3
				summarizeBy: none
				sourceColumn: Grade ID

				annotation SummarizationSetBy = Automatic

			column 'Cycle ID'
				dataType: int64
				formatString: 0
				lineageTag: 52b5df66-7fdd-4091-ba55-7092d9fc1f52
				summarizeBy: none
				sourceColumn: Cycle ID

				annotation SummarizationSetBy = Automatic

			column 'Level ID'
				dataType: int64
				formatString: 0
				lineageTag: 544caaf8-e433-43fa-9b24-141d70464cea
				summarizeBy: none
				sourceColumn: Level ID

				annotation SummarizationSetBy = Automatic

			column 'Entry Date'
				dataType: dateTime
				formatString: Short Date
				lineageTag: 689ce407-92c9-4739-bfd9-0e123c388b49
				summarizeBy: none
				sourceColumn: Entry Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column 'School ID'
				dataType: int64
				formatString: 0
				lineageTag: 6bb538e5-d574-4891-a5bd-0529f5e9151b
				summarizeBy: none
				sourceColumn: School ID

				annotation SummarizationSetBy = User

			column 'DRENAET ID'
				dataType: int64
				formatString: 0
				lineageTag: 13e63cc0-d761-4923-98e3-1c0411c51893
				summarizeBy: count
				sourceColumn: DRENAET ID

				annotation SummarizationSetBy = Automatic

			column 'IEPP ID'
				dataType: int64
				formatString: 0
				lineageTag: 9d8473a5-a469-4722-bdec-25a101d71736
				summarizeBy: count
				sourceColumn: IEPP ID

				annotation SummarizationSetBy = Automatic

			column test = 'ASER CIV Data'[Students At Level] - 'ASER CIV Data'[Students Tested In Class]
				formatString: 0
				lineageTag: 857cbf59-6c09-4bec-b556-0fe9f54621c4
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			column Period
				dataType: string
				lineageTag: 39e78b8d-381c-468f-b4ed-a92e259a53bc
				summarizeBy: none
				sourceColumn: Period

				annotation SummarizationSetBy = Automatic

			column 'Subject ID'
				dataType: int64
				formatString: 0
				lineageTag: 1abcfcd1-7179-46f4-b90e-85716d718fd3
				summarizeBy: count
				sourceColumn: Subject ID

				annotation SummarizationSetBy = Automatic

			partition 'ASER CIV Data' = m
				mode: import
				source =
						let
						    Source = Table.Combine({#"Old Data", #"New Data"}),
						    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
						    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
						    #"Colonnes renommées" = Table.RenameColumns(#"Valeur remplacée",{{"Beginner L", "Beginner L - L"}, {"Letter", "Letter - L"}, {"Word", "Word - L"}, {"Paragraph", "Paragraph - L"}, {"Story", "Story - L"}, {"Beginner N", "Beginner N - N"}, {"1-Digit", "1-Digit - N"}, {"2-Digit", "2-Digit - N"}, {"Substraction", "Substraction - N"}, {"Division", "Division - N"}, {"Comprehension", "Comprehension - L"}}),
						    #"Tableau croisé dynamique des colonnes supprimé" = Table.UnpivotOtherColumns(#"Colonnes renommées", {"DRENAET", "IEPP", "School", "Cycle", "Grade", "Students In Class", "Boys Tested", "Girls Tested", "Entry Date", "Region", "Sector", "Students Tested", "Period", "Teacher Male", "Teacher Female"}, "Attribut", "Valeur"),
						    #"Colonnes renommées1" = Table.RenameColumns(#"Tableau croisé dynamique des colonnes supprimé",{{"Valeur", "Number Of Students"}}),
						    #"Fractionner la colonne par délimiteur" = Table.SplitColumn(#"Colonnes renommées1", "Attribut", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Attribut.1", "Attribut.2"}),
						    #"Colonnes renommées2" = Table.RenameColumns(#"Fractionner la colonne par délimiteur",{{"Attribut.1", "Level"}, {"Attribut.2", "Subject"}}),
						    #"Valeur remplacée1" = Table.ReplaceValue(#"Colonnes renommées2","L","Literacy",Replacer.ReplaceText,{"Subject"}),
						    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","N","Numeracy",Replacer.ReplaceText,{"Subject"}),
						    #"Requêtes fusionnées" = Table.NestedJoin(#"Valeur remplacée2", {"DRENAET", "IEPP", "School", "Grade"}, Grades, {"DRENAET", "IEPP", "School", "Grade"}, "Grades in DRENAETs", JoinKind.LeftOuter),
						    #"Grades in DRENAETs développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "Grades in DRENAETs", {"DRENAET ID", "Grade ID", "IEPP ID", "School ID"}, {"DRENAET ID", "Grade ID", "IEPP ID", "School ID"}),
						    #"Requêtes fusionnées1" = Table.NestedJoin(#"Grades in DRENAETs développé", {"Cycle", "Period"}, Cycles, {"Cycle", "Period"}, "Cycles", JoinKind.LeftOuter),
						    #"Cycles développé" = Table.ExpandTableColumn(#"Requêtes fusionnées1", "Cycles", {"Cycle ID"}, {"Cycle ID"}),
						    #"Requêtes fusionnées2" = Table.NestedJoin(#"Cycles développé", {"Level", "Subject"}, #"Levels in Subjects", {"Level", "Subject"}, "Levels in Subjects", JoinKind.LeftOuter),
						    #"Levels in Subjects développé" = Table.ExpandTableColumn(#"Requêtes fusionnées2", "Levels in Subjects", {"Level ID", "Subject ID"}, {"Level ID", "Subject ID"}),
						    #"Autres colonnes supprimées" = Table.SelectColumns(#"Levels in Subjects développé",{"Students In Class", "Boys Tested", "Girls Tested", "Entry Date", "Students Tested", "Period", "Teacher Male", "Teacher Female", "Number Of Students", "DRENAET ID", "Grade ID", "IEPP ID", "School ID", "Cycle ID", "Subject ID", "Level ID"}),
						    #"Colonnes renommées3" = Table.RenameColumns(#"Autres colonnes supprimées",{{"Boys Tested", "Boys Tested In Class"}, {"Girls Tested", "Girls Tested In Class"}, {"Students Tested", "Students Tested In Class"}, {"Teacher Male", "Teacher Male In School"}, {"Teacher Female", "Teacher Female In School"}, {"Number Of Students", "Students At Level"}})
						in
						    #"Colonnes renommées3"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Grades
			lineageTag: 13bbfd5a-984c-40ec-9f96-fa9cfa5ec28a

			column DRENAET
				dataType: string
				lineageTag: 6f0e51c7-fb57-4292-9077-02e07ef95652
				summarizeBy: none
				sourceColumn: DRENAET

				annotation SummarizationSetBy = Automatic

			column IEPP
				dataType: string
				lineageTag: 4c6cbf21-1004-4a32-8b1b-35b45803b526
				summarizeBy: none
				sourceColumn: IEPP

				annotation SummarizationSetBy = Automatic

			column School
				dataType: string
				lineageTag: 56f34723-637d-4fc7-b586-5fc7c3ad94c0
				summarizeBy: none
				sourceColumn: School

				annotation SummarizationSetBy = Automatic

			column Grade
				dataType: string
				lineageTag: a3dbe4fb-9206-4d72-88c9-2f38a61d2c6f
				summarizeBy: none
				sourceColumn: Grade
				sortByColumn: 'Grade Sort'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Grade ID'
				dataType: int64
				formatString: 0
				lineageTag: 8c41e4f7-9423-4b0c-807a-b9f4c5c9f8a1
				summarizeBy: none
				sourceColumn: Grade ID

				annotation SummarizationSetBy = Automatic

			column Donor
				dataType: string
				lineageTag: 2d2c5a62-fbce-4e40-9c3b-6d8d8cbfdd2b
				summarizeBy: none
				sourceColumn: Donor

				annotation SummarizationSetBy = Automatic

			column 'School ID'
				dataType: int64
				formatString: 0
				lineageTag: 69f67ef1-b50d-44e8-a33b-e1e355a2f5a2
				summarizeBy: none
				sourceColumn: School ID

				annotation SummarizationSetBy = Automatic

			column 'DRENAET ID'
				dataType: int64
				formatString: 0
				lineageTag: d0ae80a6-f981-4f7c-b7b0-8e163a7d65f4
				summarizeBy: none
				sourceColumn: DRENAET ID

				annotation SummarizationSetBy = Automatic

			column 'IEPP ID'
				dataType: int64
				formatString: 0
				lineageTag: eee5a45d-56ba-4191-bc74-cbef16b4c645
				summarizeBy: none
				sourceColumn: IEPP ID

				annotation SummarizationSetBy = Automatic

			column 'Grade Sort'
				dataType: int64
				formatString: 0
				lineageTag: cab31000-fbca-41c0-aa3c-4a4d8931fc30
				summarizeBy: none
				sourceColumn: Grade Sort

				annotation SummarizationSetBy = Automatic

			partition Grades = m
				mode: import
				source =
						let
						    Source = Table.Combine({#"Old Data", #"New Data"}),
						    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
						    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
						    #"Autres colonnes supprimées" = Table.SelectColumns(#"Valeur remplacée",{"DRENAET", "IEPP", "School", "Grade"}),
						    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
						    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 0, 1, Int64.Type),
						    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "Grade ID"}}),
						    #"Requêtes fusionnées" = Table.NestedJoin(#"Colonnes renommées", {"DRENAET"}, #"DRENAETs and Donors", {"DRENAET"}, "DRENAETs and Donors", JoinKind.LeftOuter),
						    #"DRENAETs and Donors développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "DRENAETs and Donors", {"Donor", "DRENAET ID"}, {"Donor", "DRENAET ID"}),
						    #"Requêtes fusionnées1" = Table.NestedJoin(#"DRENAETs and Donors développé", {"DRENAET", "IEPP", "School"}, Schools, {"DRENAET", "IEPP", "School"}, "Schools", JoinKind.LeftOuter),
						    #"Schools développé" = Table.ExpandTableColumn(#"Requêtes fusionnées1", "Schools", {"School ID"}, {"School ID"}),
						    #"Requêtes fusionnées2" = Table.NestedJoin(#"Schools développé", {"DRENAET", "IEPP"}, IEPPs, {"DRENAET", "IEPP"}, "IEPPs", JoinKind.LeftOuter),
						    #"IEPPs développé" = Table.ExpandTableColumn(#"Requêtes fusionnées2", "IEPPs", {"IEPP ID"}, {"IEPP ID"}),
						    #"Colonne conditionnelle ajoutée" = Table.AddColumn(#"IEPPs développé", "Grade Sort", each if [Grade] = "CE1" then 3 else if [Grade] = "CE2" then 4 else if [Grade] = "CM1" then 5 else if [Grade] = "CM2" then 6 else null),
						    #"Type modifié" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée",{{"Grade Sort", Int64.Type}})
						in
						    #"Type modifié"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Cycles
			lineageTag: 2dc2b491-cd42-4119-9a49-bf55e1235237

			column 'Cycle ID'
				dataType: int64
				formatString: 0
				lineageTag: 49860b4c-a29f-4ee8-95b2-a4bcc7b08489
				summarizeBy: none
				sourceColumn: Cycle ID

				annotation SummarizationSetBy = Automatic

			column Cycle
				dataType: string
				lineageTag: 0ee720e5-5240-4f6a-9fa0-0fba5811fa37
				summarizeBy: none
				sourceColumn: Cycle
				sortByColumn: 'Cycle Sort'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column Period
				dataType: string
				lineageTag: 54bef491-3e23-4eed-8f45-95ec5713191a
				summarizeBy: none
				sourceColumn: Period

				annotation SummarizationSetBy = Automatic

			column 'Cycle Name'
				dataType: string
				lineageTag: dfef2b3a-3e1f-4690-bb57-9750c145c4e1
				summarizeBy: none
				sourceColumn: Cycle Name
				sortByColumn: 'Cycle ID'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

			column 'Cycle Sort'
				dataType: int64
				formatString: 0
				lineageTag: 8d68d0fc-353c-4699-b1a4-5fe0ea19c5eb
				summarizeBy: sum
				sourceColumn: Cycle Sort

				annotation SummarizationSetBy = Automatic

			partition Cycles = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Zcw7CsAgEADRu2xtwF01nzaQLjmBeP9rZDUEBmymeMXUKipBzttj0XTxmLRQxVyemZPLNXPGxDqnwQUT8IoJeMMkdc6Dd0zAByZgjbjk7uVzxYZu+PzeXg==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Cycle ID" = _t, Cycle = _t, Period = _t]),
						    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Cycle ID", Int64.Type}, {"Cycle", type text}, {"Period", type text}}),
						    #"Personnalisée ajoutée" = Table.AddColumn(#"Type modifié", "Cycle Name", each [Period] & " " & [Cycle]),
						    #"Colonne conditionnelle ajoutée" = Table.AddColumn(#"Personnalisée ajoutée", "Cycle Sort", each if [Cycle] = "BL" then 1 else if [Cycle] = "ML" then 2 else if [Cycle] = "EL" then 3 else null),
						    #"Type modifié1" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée",{{"Cycle Name", type text}, {"Cycle Sort", Int64.Type}})
						in
						    #"Type modifié1"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table 'Levels in Subjects'
			lineageTag: 228a31b4-63b6-4a56-af45-4169c3054e5f

			column Level
				dataType: string
				lineageTag: 13616aec-13da-4333-8315-c1de70d971ab
				summarizeBy: none
				sourceColumn: Level
				sortByColumn: 'Level Sort'

				changedProperty = SortByColumn

				annotation SummarizationSetBy = Automatic

				annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Levels in Subjects","TableItemName":"Grouped Level","ObjectType":4},"LinkType":"UsedInGroup"}]

			column Subject
				dataType: string
				lineageTag: 98a04a38-6d90-4ea8-bdf8-2c7e3f9c1559
				summarizeBy: none
				sourceColumn: Subject

				annotation SummarizationSetBy = Automatic

			column 'Level ID'
				dataType: int64
				formatString: 0
				lineageTag: 41493d22-4abd-471f-b644-6594ca5d0fc4
				summarizeBy: none
				sourceColumn: Level ID

				annotation SummarizationSetBy = Automatic

			column 'Subject ID'
				dataType: int64
				formatString: 0
				lineageTag: dc5913eb-5109-4b12-b722-125ccbd657b9
				summarizeBy: count
				sourceColumn: Subject ID

				annotation SummarizationSetBy = Automatic

			column 'Level Sort'
				dataType: int64
				formatString: 0
				lineageTag: c40a7215-0eea-41a6-b491-d741cb5fa133
				summarizeBy: sum
				sourceColumn: Level Sort

				annotation SummarizationSetBy = Automatic

			column 'Grouped Level' =
					SWITCH(
						TRUE,
						ISBLANK('Levels in Subjects'[Level]),
						"(Vide)",
						'Levels in Subjects'[Level] IN {"2-Digit"},
						"2-Digit",
						'Levels in Subjects'[Level] IN {"Paragraph",
							"Story",
							"Comprehension"},
						"Can read at least a simple paragraph",
						'Levels in Subjects'[Level] IN {"Substraction",
							"Division"},
						"Can solve at least 2x2 subtraction operation",
						'Levels in Subjects'[Level] IN {"Beginner L",
							"Letter"},
						"Cannot read words",
						'Levels in Subjects'[Level] IN {"Beginner N",
							"1-Digit"},
						"Cannot recognize 2-digit",
						'Levels in Subjects'[Level] IN {"Word"},
						"Word",
						'Levels in Subjects'[Level]
					)
				lineageTag: 412e89ff-3482-4024-8046-4196cbf45b0a
				summarizeBy: none
				sortByColumn: 'Group Level Sort'

				extendedProperty GroupingMetadata = {"version":0,"groupedColumns":[{"Column":{"Expression":{"SourceRef":{"Entity":"Levels in Subjects"}},"Property":"Level"}}]}

				changedProperty = SortByColumn

				annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"l","Entity":"Levels in Subjects"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"GroupItems":[{"DisplayName":"(Vide)","BlankDefaultPlaceholder":true},{"DisplayName":"2-Digit","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'2-Digit'"}}]]}}},{"DisplayName":"Can read at least a simple paragraph","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Paragraph'"}}],[{"Literal":{"Value":"'Story'"}}],[{"Literal":{"Value":"'Comprehension'"}}]]}}},{"DisplayName":"Can solve at least 2x2 subtraction operation","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Substraction'"}}],[{"Literal":{"Value":"'Division'"}}]]}}},{"DisplayName":"Cannot read words","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Beginner L'"}}],[{"Literal":{"Value":"'Letter'"}}]]}}},{"DisplayName":"Cannot recognize 2-digit","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Beginner N'"}}],[{"Literal":{"Value":"'1-Digit'"}}]]}}},{"DisplayName":"Word","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"l"}},"Property":"Level"}}],"Values":[[{"Literal":{"Value":"'Word'"}}]]}}}]}

				annotation SummarizationSetBy = Automatic

			column 'Group Level Sort' =
					
					SWITCH( TRUE(),
					        'Levels in Subjects'[Level Sort] <= 2, 1,
					        'Levels in Subjects'[Level Sort] = 3, 2,
					        'Levels in Subjects'[Level Sort] <= 6, 3,
					        'Levels in Subjects'[Level Sort] <= 12, 4,
					        'Levels in Subjects'[Level Sort] = 13, 5,
					        'Levels in Subjects'[Level Sort] <= 15, 6,
					        BLANK() )
				formatString: 0
				lineageTag: ed270a33-723a-4a8e-b238-e61fcac9f99a
				summarizeBy: sum

				annotation SummarizationSetBy = Automatic

			hierarchy 'Subject Hierarchy'
				lineageTag: 87fb0bcb-2de7-41e5-b182-182214434fef

				level Subject
					lineageTag: e74e6b05-2147-4dac-81a7-6f1a0370bcb9
					column: Subject

				level 'Grouped Level'
					lineageTag: 6ca84d86-8feb-40df-99a1-43d1dd13f486
					column: 'Grouped Level'

				level Level
					lineageTag: cbef60f4-f8a7-4b4d-8ddd-dcaf4eb6bbfd
					column: Level

			partition 'Levels in Subjects' = m
				mode: import
				source =
						let
						    Source = Table.Combine({#"Old Data", #"New Data"}),
						    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
						    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
						    #"Colonnes renommées" = Table.RenameColumns(#"Valeur remplacée",{{"Beginner L", "Beginner L - L"}, {"Letter", "Letter - L"}, {"Word", "Word - L"}, {"Paragraph", "Paragraph - L"}, {"Story", "Story - L"}, {"Beginner N", "Beginner N - N"}, {"1-Digit", "1-Digit - N"}, {"2-Digit", "2-Digit - N"}, {"Substraction", "Substraction - N"}, {"Division", "Division - N"}, {"Comprehension", "Comprehension - L"}}),
						    #"Tableau croisé dynamique des colonnes supprimé" = Table.UnpivotOtherColumns(#"Colonnes renommées", {"DRENAET", "IEPP", "School", "Cycle", "Grade", "Students In Class", "Boys Tested", "Girls Tested", "Entry Date", "Region", "Sector", "Students Tested", "Period", "Teacher Male", "Teacher Female"}, "Attribut", "Valeur"),
						    #"Colonnes renommées1" = Table.RenameColumns(#"Tableau croisé dynamique des colonnes supprimé",{{"Valeur", "Number Of Students"}}),
						    #"Fractionner la colonne par délimiteur" = Table.SplitColumn(#"Colonnes renommées1", "Attribut", Splitter.SplitTextByDelimiter(" - ", QuoteStyle.Csv), {"Attribut.1", "Attribut.2"}),
						    #"Colonnes renommées2" = Table.RenameColumns(#"Fractionner la colonne par délimiteur",{{"Attribut.1", "Level"}, {"Attribut.2", "Subject"}}),
						    #"Valeur remplacée1" = Table.ReplaceValue(#"Colonnes renommées2","L","Literacy",Replacer.ReplaceText,{"Subject"}),
						    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","N","Numeracy",Replacer.ReplaceText,{"Subject"}),
						    #"Autres colonnes supprimées" = Table.SelectColumns(#"Valeur remplacée2",{"Level", "Subject"}),
						    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
						    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 0, 1, Int64.Type),
						    #"Colonnes renommées3" = Table.RenameColumns(#"Index ajouté",{{"Index", "Level ID"}}),
						    #"Colonne conditionnelle ajoutée" = Table.AddColumn(#"Colonnes renommées3", "Subject ID", each if [Subject] = "Literacy" then 1 else if [Subject] = "Numeracy" then 2 else null),
						    #"Type modifié" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée",{{"Subject ID", Int64.Type}}),
						    #"Colonne conditionnelle ajoutée1" = Table.AddColumn(#"Type modifié", "Level Sort", each if [Level] = "Beginner L" then 1 else if [Level] = "Letter" then 2 else if [Level] = "Word" then 3 else if [Level] = "Paragraph" then 4 else if [Level] = "Story" then 5 else if [Level] = "Comprehension" then 6 else if [Level] = "Beginner N" then 11 else if [Level] = "1-Digit" then 12 else if [Level] = "2-Digit" then 13 else if [Level] = "Substraction" then 14 else if [Level] = "Division" then 15 else null),
						    #"Type modifié1" = Table.TransformColumnTypes(#"Colonne conditionnelle ajoutée1",{{"Level Sort", Int64.Type}})
						in
						    #"Type modifié1"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table 'Entry Calendar'
			lineageTag: 7b0eec92-c670-4601-908e-d5e6855a918a
			dataCategory: Time

			column Date
				isKey
				formatString: Short Date
				lineageTag: 2ca7011e-05c1-4021-b7d1-2fa8413314b8
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = Automatic

			partition 'Entry Calendar' = calculated
				mode: import
				source =
						
						VAR Date_Debut = DATE(2021, 1, 1)
						VAR Date_Fin = LASTDATE( 'ASER CIV Data'[Entry Date] )
						RETURN CALENDAR( Date_Debut, Date_Fin)

			annotation PBI_Id = 844ba9c1cc9f475d911851b5514f3aba

		table Mesures
			lineageTag: 88d328ed-b1e1-4ef2-a3ac-aee29dcb536c

			measure 'Number Of DRENAETs' = DISTINCTCOUNT( 'Grades'[DRENAET] )
				formatString: #,0
				lineageTag: 18a3d325-e8d5-453f-b685-22788919c997

			measure 'Number Of IEPPs' = DISTINCTCOUNT( 'Grades'[IEPP] )
				formatString: #,0
				lineageTag: cf5d988b-65aa-4447-9c26-9f74f6fda9a7

			measure 'Number Of Schools' = DISTINCTCOUNT( 'Grades'[School ID] )
				formatString: #,0
				lineageTag: cb9668aa-733c-44e6-aa9e-f06733f64b35

			measure 'Number Of Schools Tested' = DISTINCTCOUNT( 'ASER CIV Data'[School ID] )
				formatString: #,0
				lineageTag: 067b1b3d-1b52-4e22-bc96-5aaa63df3ad2

			measure 'Number Of Students' = ```
					
					VAR __NbDistinctCycles =
					    COUNTROWS( VALUES( Cycles[Cycle ID] ) )
					
					-- Table dédupliquée : une ligne par (School, Grade, Cycle)
					-- MAX sert uniquement à dédupliquer les lignes Level ID
					-- La table ramène l'effectif de chaque classe pour à chaque cycle
					VAR __BaseTable =
					    SUMMARIZE(
					        'ASER CIV Data',
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        "@Effectif", MAX( 'ASER CIV Data'[Students In Class] )
					    )
					
					-- ── CAS 1 : Cycle unique
					VAR __SingleCycle =
					    SUMX( __BaseTable, [@Effectif] )
					
					-- ── CAS 2 : Multi-cycles
					-- Étape 1 : effectif de chaque école pour chaque cycle (somme des classes)
					VAR __EffectifParEcoleParCycle =
					    SUMMARIZE(
					        __BaseTable,
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Cycle ID],
					        "@EffectifCycle",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            VAR __CurCycle  = 'ASER CIV Data'[Cycle ID]
					            RETURN
					                SUMX(
					                    FILTER( __BaseTable,
					                        'ASER CIV Data'[School ID] = __CurSchool &&
					                        'ASER CIV Data'[Cycle ID]  = __CurCycle
					                    ),
					                    [@Effectif]
					                )
					    )
					
					-- Étape 2 : pour chaque école, MAX des effectifs sur les cycles
					VAR __MaxParEcole =
					    SUMMARIZE(
					        __EffectifParEcoleParCycle,
					        'ASER CIV Data'[School ID],
					        "@MaxEffectif", 
					        VAR __CurSchool = 'ASER CIV Data'[School ID]
					        RETURN
					            MAXX(
					                FILTER( __EffectifParEcoleParCycle,
					                    'ASER CIV Data'[School ID] = __CurSchool
					                ),
					                [@EffectifCycle]
					        )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxEffectif] )
					
					RETURN
					    IF( __NbDistinctCycles = 1, __SingleCycle, __MultiCycle )
					```
				formatString: #,0
				lineageTag: 28e7e4e6-4db9-4fc4-8331-6a5e36e5d623

			measure '_Number Of Students' = ```
					
					VAR __NbDistinctCycles =
					    COUNTROWS( VALUES( Cycles[Cycle ID] ) )
					
					-- Table dédupliquée : une ligne par (School, Grade, Cycle)
					-- MAX sert uniquement à dédupliquer les lignes Level ID
					-- La table ramène l'effectif de chaque classe pour à chaque cycle
					VAR __BaseTable =
					    SUMMARIZE(
					        'ASER CIV Data',
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        "@Effectif", MAX( 'ASER CIV Data'[Students In Class] )
					    )
					
					-- ── CAS 1 : Cycle unique
					VAR __SingleCycle =
					    SUMX( __BaseTable, [@Effectif] )
					
					-- ── CAS 2 : Multi-cycles
					-- Étape 1 : effectif de chaque école pour chaque cycle (somme des classes)
					VAR __EffectifParEcoleParCycle =
					    SUMMARIZE(
					        __BaseTable,
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Cycle ID],
					        "@EffectifCycle", SUMX(
					            FILTER( __BaseTable, 
					                'ASER CIV Data'[School ID] = EARLIER('ASER CIV Data'[School ID] ) &&
					                'ASER CIV Data'[Cycle ID]  = EARLIER( 'ASER CIV Data'[Cycle ID] )
					            ),
					            [@Effectif]
					        )
					    )
					
					-- Étape 2 : pour chaque école, MAX des effectifs sur les cycles
					VAR __MaxParEcole =
					    SUMMARIZE(
					        __EffectifParEcoleParCycle,
					        'ASER CIV Data'[School ID],
					        "@MaxEffectif", MAXX(
					            FILTER( __EffectifParEcoleParCycle,
					                'ASER CIV Data'[School ID] = EARLIER( 'ASER CIV Data'[School ID] )
					            ),
					            [@EffectifCycle]
					        )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxEffectif] )
					
					RETURN
					    IF( __NbDistinctCycles = 1, __SingleCycle, __MultiCycle )
					```
				formatString: #,0
				lineageTag: 821e1453-e481-4b5a-83d3-0887dd2612b7

			measure 'Percentage Of Students' =
					
					VAR __NumberOfStudents = [Number Of Students]
					VAR __AllStudents = CALCULATE( [Number Of Students], ALLSELECTED( 'ASER CIV Data' ) )
					RETURN DIVIDE( __NumberOfStudents, __AllStudents )
				formatString: 0.00\ %;-0.00\ %;0.00\ %
				lineageTag: 232a6920-d951-4ee3-ac74-157357889af6

			measure 'Number Of Students Tested' = ```
					
					VAR __NbDistinctCycles =
					    COUNTROWS( VALUES( Cycles[Cycle ID] ) )
					
					-- Table dédupliquée : une ligne par (School, Grade, Cycle)
					-- La table ramène le nombre d'élèves testés de chaque classe à chaque cycle
					VAR __BaseTable =
					    SUMMARIZE(
					        'ASER CIV Data',
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        'ASER CIV Data'[Level ID],
					        "@StudentsTested", MAX( 'ASER CIV Data'[Students At Level] )
					    )
					
					-- ── CAS 1 : Cycle unique
					VAR __SingleCycle =
					    SUMX( __BaseTable, [@StudentsTested] )
					
					-- ── CAS 2 : Multi-cycles
					-- Étape 1 : Nombre d'élèves testés de chaque école pour chaque cycle
					VAR __NombreParEcoleParCycle =
					    SUMMARIZE(
					        __BaseTable,
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Cycle ID],
					        'ASER CIV Data'[Level ID],
					        "@NbTestedCycle",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            VAR __CurCycle  = 'ASER CIV Data'[Cycle ID]
					            VAR __CurLevel = 'ASER CIV Data'[Level ID]
					            RETURN
					                SUMX(
					                    FILTER( __BaseTable,
					                        'ASER CIV Data'[School ID] = __CurSchool &&
					                        'ASER CIV Data'[Cycle ID]  = __CurCycle &&
					                        'ASER CIV Data'[Level ID] = __CurLevel
					                    ),
					                    [@StudentsTested]
					                )
					    )
					
					-- Étape 2 : pour chaque école, MAX des nombre d'élèves testés sur les cycles
					VAR __MaxParEcole =
					    SUMMARIZE(
					        __NombreParEcoleParCycle,
					        'ASER CIV Data'[School ID],
					        "@MaxTested", 
					        VAR __CurSchool = 'ASER CIV Data'[School ID]
					        RETURN
					            MAXX(
					                FILTER( __NombreParEcoleParCycle,
					                    'ASER CIV Data'[School ID] = __CurSchool
					                ),
					                [@NbTestedCycle]
					        )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxTested] )
					
					RETURN
					    IF( __NbDistinctCycles = 1, __SingleCycle, __MultiCycle )
					```
				formatString: #,0
				lineageTag: c8508836-87c2-4342-895c-9515020a5074

			measure 'Number Of Students In Cycle' =
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					
						VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
							'ASER Cycles Data',
							"@Cycle ID", 'ASER Cycles Data'[Cycle ID],
							"@School ID", 'ASER Cycles Data'[School ID],
							"@Students In School", 'ASER Cycles Data'[Students In School]
						))
					
					    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle )
					
					RETURN SUMX( __FilteredTable, [@Students In School] )
				formatString: #,0
				lineageTag: 32a8b5ca-4fd8-4f29-8e78-d208d54298d1

			measure 'Number Of Students Tested BL' =
					
					VAR __BLTable = FILTER( 'ASER CIV Data', RELATED( Cycles[Cycle] ) = "BL" )
					VAR __BaseTable =
					    SUMMARIZECOLUMNS(
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'Levels in Subjects'[Level],
					        Cycles[Cycle],
					        "@StudentsTested", MAX( 'ASER CIV Data'[Students At Level] )
					    )
					
					VAR __NbOfStudents =
					    SUMX( __BaseTable, [@StudentsTested] )
					
					RETURN __NbOfStudents
				formatString: 0
				lineageTag: bda3caf2-2bf6-466f-bb2a-391585069ed7

			measure 'Number Of Students v2' =
					
					VAR __CyclesActifs =
					    VALUES( Cycles[Cycle ID] )
					
					VAR __LevelsActifs =
					    VALUES( 'Levels in Subjects'[Level ID] )
					
					VAR __NbDistinctCycles =
					    COUNTROWS( __CyclesActifs )
					
					-- Table dédupliquée filtrée par Cycle et Level du contexte
					VAR __BaseTable =
					    SUMMARIZE(
					        FILTER(
					            'ASER CIV Data',
					            'ASER CIV Data'[Cycle ID] IN __CyclesActifs &&
					            'ASER CIV Data'[Level ID] IN __LevelsActifs
					        ),
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        "@Effectif", MAX( 'ASER CIV Data'[Students In Class] )
					    )
					
					-- ── CAS 1 : Cycle unique ────────────────────────────────────────────────────
					VAR __SingleCycle =
					    SUMX( __BaseTable, [@Effectif] )
					
					-- ── CAS 2 : Multi-cycles ────────────────────────────────────────────────────
					-- Étape 1 : effectif de chaque école pour chaque cycle (somme des classes)
					VAR __EffectifParEcoleParCycle =
					    ADDCOLUMNS(
					        SUMMARIZE( __BaseTable,
					            'ASER CIV Data'[School ID],
					            'ASER CIV Data'[Cycle ID]
					        ),
					        "@EffectifCycle",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            VAR __CurCycle  = 'ASER CIV Data'[Cycle ID]
					            RETURN
					                SUMX(
					                    FILTER( __BaseTable,
					                        'ASER CIV Data'[School ID] = __CurSchool &&
					                        'ASER CIV Data'[Cycle ID]  = __CurCycle
					                    ),
					                    [@Effectif]
					                )
					    )
					
					-- Étape 2 : pour chaque école, MAX des effectifs sur les cycles
					VAR __MaxParEcole =
					    ADDCOLUMNS(
					        SUMMARIZE( __EffectifParEcoleParCycle,
					            'ASER CIV Data'[School ID]
					        ),
					        "@MaxEffectif",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            RETURN
					                MAXX(
					                    FILTER( __EffectifParEcoleParCycle,
					                        'ASER CIV Data'[School ID] = __CurSchool
					                    ),
					                    [@EffectifCycle]
					                )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxEffectif] )
					
					RETURN
					    IF( __NbDistinctCycles = 1, __SingleCycle, __MultiCycle )
				formatString: 0
				lineageTag: 924e9b8e-7660-4c52-aa6c-ec513cbf541e

			measure 'Number Of Students Tested v2' =
					
					VAR __CyclesActifs =
					    VALUES( Cycles[Cycle ID] )
					
					VAR __LevelsActifs =
					    VALUES( 'Levels in Subjects'[Level ID] )
					
					VAR __NbDistinctCycles =
					    COUNTROWS( __CyclesActifs )
					
					-- Table dédupliquée filtrée par Cycle et Level du contexte
					VAR __BaseTable =
					    SUMMARIZE(
					        FILTER(
					            'ASER CIV Data',
					            'ASER CIV Data'[Cycle ID] IN __CyclesActifs &&
					            'ASER CIV Data'[Level ID] IN __LevelsActifs
					        ),
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        "@Effectif", MAX( 'ASER CIV Data'[Students Tested In Class] )
					    )
					
					-- ── CAS 1 : Cycle unique ────────────────────────────────────────────────────
					VAR __SingleCycle =
					    SUMX( __BaseTable, [@Effectif] )
					
					-- ── CAS 2 : Multi-cycles ────────────────────────────────────────────────────
					-- Étape 1 : effectif de chaque école pour chaque cycle (somme des classes)
					VAR __EffectifParEcoleParCycle =
					    ADDCOLUMNS(
					        SUMMARIZE( __BaseTable,
					            'ASER CIV Data'[School ID],
					            'ASER CIV Data'[Cycle ID]
					        ),
					        "@EffectifCycle",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            VAR __CurCycle  = 'ASER CIV Data'[Cycle ID]
					            RETURN
					                SUMX(
					                    FILTER( __BaseTable,
					                        'ASER CIV Data'[School ID] = __CurSchool &&
					                        'ASER CIV Data'[Cycle ID]  = __CurCycle
					                    ),
					                    [@Effectif]
					                )
					    )
					
					-- Étape 2 : pour chaque école, MAX des effectifs sur les cycles
					VAR __MaxParEcole =
					    ADDCOLUMNS(
					        SUMMARIZE( __EffectifParEcoleParCycle,
					            'ASER CIV Data'[School ID]
					        ),
					        "@MaxEffectif",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            RETURN
					                MAXX(
					                    FILTER( __EffectifParEcoleParCycle,
					                        'ASER CIV Data'[School ID] = __CurSchool
					                    ),
					                    [@EffectifCycle]
					                )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxEffectif] )
					
					RETURN
					    IF( __NbDistinctCycles = 1, __SingleCycle, __MultiCycle )
				formatString: 0
				lineageTag: 70291f2b-8b11-443c-9d41-b9b7366f22d5

			measure Mesure
				lineageTag: ef9bf2cc-ec3f-4f5f-ab1a-1f98f65a1cae

				annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

			measure 'Number Of Students Tested In Cycle' =
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
					
						VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
							'ASER Cycles Data',
							"@Cycle ID", 'ASER Cycles Data'[Cycle ID],
							"@School ID", 'ASER Cycles Data'[School ID],
					        "@Subject ID", 'ASER Cycles Data'[Subject ID],
							"@Students Tested", 'ASER Cycles Data'[Students At Level]
						))
					
					    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Subject ID] = __CurrentSubject)
					
					RETURN SUMX( __FilteredTable, [@Students Tested] )
				formatString: #,0
				lineageTag: 4589fda1-cd39-43d9-8eb0-b4e3ad2e6e2f

			measure 'Number Of Students Reached In Program' = ```
					
					VAR __NbDistinctCycles =
					    COUNTROWS( VALUES( Cycles[Cycle ID] ) )
					
					VAR __BaseTable =
					    SUMMARIZE(
					        'ASER CIV Data',
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Grade ID],
					        'ASER CIV Data'[Cycle ID],
					        "@Effectif", MAX( 'ASER CIV Data'[Students In Class] )
					    )
					
					VAR __EffectifParEcoleParCycle =
					    SUMMARIZE(
					        __BaseTable,
					        'ASER CIV Data'[School ID],
					        'ASER CIV Data'[Cycle ID],
					        "@EffectifCycle",
					            VAR __CurSchool = 'ASER CIV Data'[School ID]
					            VAR __CurCycle  = 'ASER CIV Data'[Cycle ID]
					            RETURN
					                SUMX(
					                    FILTER( __BaseTable,
					                        'ASER CIV Data'[School ID] = __CurSchool &&
					                        'ASER CIV Data'[Cycle ID]  = __CurCycle
					                    ),
					                    [@Effectif]
					                )
					    )
					
					-- Étape 2 : pour chaque école, MAX des effectifs sur les cycles
					VAR __MaxParEcole =
					    SUMMARIZE(
					        __EffectifParEcoleParCycle,
					        'ASER CIV Data'[School ID],
					        "@MaxEffectif", 
					        VAR __CurSchool = 'ASER CIV Data'[School ID]
					        RETURN
					            MAXX(
					                FILTER( __EffectifParEcoleParCycle,
					                    'ASER CIV Data'[School ID] = __CurSchool
					                ),
					                [@EffectifCycle]
					        )
					    )
					
					-- Étape 3 : somme des maximums
					VAR __MultiCycle =
					    SUMX( __MaxParEcole, [@MaxEffectif] )
					
					RETURN __MultiCycle
					```
				formatString: #,0
				lineageTag: 24fd0b70-42c6-4753-ba54-2d4d41e7d508

			measure 'Percentage Change Rate Of Students Tested' =
					
					
					VAR __CurrentNumberOfStudents = [Number Of Students Tested In Cycle]
					VAR __PreviousNumberOfStudents = [Number Of Students Tested In Previous Cycle]
					VAR __NumberChange = __CurrentNumberOfStudents - __PreviousNumberOfStudents
					VAR __PercentageChange = DIVIDE( __NumberChange, __PreviousNumberOfStudents )
					RETURN __PercentageChange
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 20bfb364-664a-4ff1-be41-a72bc3ddca38

			measure 'Number Of Students Tested In Previous Cycle' =
					
					
					VAR __NumberOfCycles = 'Cycles interval'[Valeur Cycles Interval]
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] ) - 'Cycles interval'[Valeur Cycles Interval]
					--VAR __CurrentCycle = MAX( 'Compared To Cycles'[Cycle ID] )
					VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
					
					VAR __BaseTable =
					    DISTINCT(
					        SELECTCOLUMNS(
					            CALCULATETABLE(
					                'ASER Cycles Data',
					                ALL( Cycles )
					            ),
					            "@Cycle ID",        'ASER Cycles Data'[Cycle ID],
					            "@School ID",       'ASER Cycles Data'[School ID],
					            "@Subject ID",      'ASER Cycles Data'[Subject ID],
					            "@Students Tested", 'ASER Cycles Data'[Students At Level]
					        )
					    )
					
					VAR __FilteredTable =
					    FILTER(
					        __BaseTable,
					        [@Cycle ID] = __CurrentCycle &&
					        [@Subject ID] = __CurrentSubject
					    )
					
					RETURN
					    SUMX( __FilteredTable, [@Students Tested] )
				formatString: #,0
				lineageTag: 450a8c52-7905-4a81-9a13-73e707afd5b8

			measure 'Cycles Compared' =
					
					VAR __CurrentCycleID = MAX( Cycles[Cycle ID] )
					VAR __CurrentCycle = MAX( Cycles[Cycle Name] )
					VAR __ComparedToID = __CurrentCycleID - 'Cycles interval'[Valeur Cycles Interval]
					VAR __ComparedToName = LOOKUPVALUE( Cycles[Cycle Name], Cycles[Cycle ID], __ComparedToID)
					
					RETURN "You are comparing " & __CurrentCycle & " To " & __ComparedToName
				lineageTag: 8cb7e011-ca4d-48ba-adc4-e4c523580a8e

			measure 'Boys Tested In Cycle' =
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
					
						VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
							'ASER Cycles Data',
							"@Cycle ID", 'ASER Cycles Data'[Cycle ID],
							"@School ID", 'ASER Cycles Data'[School ID],
					        "@Subject ID", 'ASER Cycles Data'[Subject ID],
							"@Boys Tested", 'ASER Cycles Data'[Boys Tested In School]
						))
					
					    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Subject ID] = __CurrentSubject)
					
					RETURN SUMX( __FilteredTable, [@Boys Tested] )
				formatString: #,0
				lineageTag: 38384916-df62-49fd-9dae-93494f57aa80

			measure 'Girls Tested In Cycle' =
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
					
						VAR __BaseTable = DISTINCT(SELECTCOLUMNS(
							'ASER Cycles Data',
							"@Cycle ID", 'ASER Cycles Data'[Cycle ID],
							"@School ID", 'ASER Cycles Data'[School ID],
					        "@Subject ID", 'ASER Cycles Data'[Subject ID],
							"@Girls Tested", 'ASER Cycles Data'[Girls Tested In School]
						))
					
					    VAR __FilteredTable = FILTER( __BaseTable, [@Cycle ID] = __CurrentCycle  && [@Subject ID] = __CurrentSubject)
					
					RETURN SUMX( __FilteredTable, [@Girls Tested] )
				formatString: #,0
				lineageTag: bc504718-b829-4160-adbb-0d4caa6c15d6

			measure 'Percentage Of Students Tested With High Literacy In Cycle' =
					
					VAR __AllStudentsTested =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    ALLSELECTED( 'ASER Cycles Data' ),
					    'ASER Cycles Data'[Subject ID] = 1
					    )
					VAR __NumberOfSudentsTestedHL =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    'Levels in Subjects'[Group Level Sort] = 3
					    )
					VAR __Percentage = DIVIDE( __NumberOfSudentsTestedHL, __AllStudentsTested )
					RETURN __Percentage
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: ddf94863-a75d-46fa-abe5-7dad33d68110

			measure 'Percentage Of Students Tested With High Literacy In Grade' = ```
					
					DIVIDE( 
					    [Number Of Students Tested with High Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 1d3c5cd4-246e-4480-8b48-63d56ff14838

			measure 'Number Of Students Tested In Grade' =
					
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					VAR __CurrentSubject = MAX( 'ASER CIV Data'[Subject ID] )
					
						VAR __GradesData =
						SELECTCOLUMNS(
							'ASER CIV Data',
							"@Cycle ID", 'ASER CIV Data'[Cycle ID],
							"@Grade", RELATED( Grades[Grade] ),
							"@Level ID", 'ASER CIV Data'[Level ID],
							"@Subject ID", 'ASER CIV Data'[Subject ID],
							"@Students At Level", 'ASER CIV Data'[Students At Level]
						)
					
					    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Subject ID] = __CurrentSubject)
					
					RETURN SUMX( __FilteredTable, [@Students At Level] )
				formatString: #,0
				lineageTag: b728bcdf-95f1-4924-af22-8830ae4fb7a6

			measure 'Number Of Students Tested with High Literacy In Grade' =
					
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					
						VAR __GradesData =
						SELECTCOLUMNS(
							'ASER CIV Data',
							"@Cycle ID", 'ASER CIV Data'[Cycle ID],
							"@Grade", RELATED( Grades[Grade] ),
					        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
							"@Students At Level", 'ASER CIV Data'[Students At Level]
						)
					
					    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 3)
					
					RETURN SUMX( __FilteredTable, [@Students At Level] )
				formatString: #,0
				lineageTag: 3f415c52-f7fc-4d20-993a-6cfa641ab613

			measure 'Percentage Of Students Tested With High Literacy In Grade BL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with High Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "BL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 80db46d6-8cbf-4667-b72f-4c291d6825be

			measure 'Percentage Of Students Tested With High Literacy In Grade EL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with High Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "EL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: fcbfe87e-5312-417d-b542-0b17a4dfb42b

			measure 'Literacy Improvement BL to EL (PP)' =
					
					VAR __EL = [Percentage Of Students Tested With High Literacy In Grade EL]
					VAR __BL = [Percentage Of Students Tested With High Literacy In Grade BL]
					RETURN __EL - __BL
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 420efd55-0b13-43f0-9e12-93ef15d1dfd1

			measure 'Number Of Students Tested with Low Literacy In Grade' =
					
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					
						VAR __GradesData =
						SELECTCOLUMNS(
							'ASER CIV Data',
							"@Cycle ID", 'ASER CIV Data'[Cycle ID],
							"@Grade", RELATED( Grades[Grade] ),
					        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
							"@Students At Level", 'ASER CIV Data'[Students At Level]
						)
					
					    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 1)
					
					RETURN SUMX( __FilteredTable, [@Students At Level] )
				formatString: 0
				lineageTag: 211d6b35-41e0-40ab-b4f4-aa8ae078e2af

			measure 'Literacy Difficulty Reduction BL to EL (PP)' =
					
					VAR __EL = [Percentage Of Students Tested With Low Literacy In Grade EL]
					VAR __BL = [Percentage Of Students Tested With Low Literacy In Grade BL]
					RETURN __BL - __EL
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 92710847-def6-4456-92ca-92e25a8d0deb

			measure 'Percentage Of Students Tested With Low Literacy In Grade ML' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with High Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "ML" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 060f822a-45e5-4051-a19a-f28b22b6a81b

			measure 'Percentage Of Students Tested With Low Literacy In Grade EL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with Low Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "EL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 0152dfa5-ae6d-484a-8ae0-bc918afaca61

			measure 'Percentage Of Students Tested With Low Literacy In Grade BL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with Low Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "BL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: a36eda9a-1aaa-41d6-913e-4ebcc7e571b2

			measure 'Number Of Students Tested with High Numeracy In Grade' =
					
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					
						VAR __GradesData =
						SELECTCOLUMNS(
							'ASER CIV Data',
							"@Cycle ID", 'ASER CIV Data'[Cycle ID],
							"@Grade", RELATED( Grades[Grade] ),
					        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
							"@Students At Level", 'ASER CIV Data'[Students At Level]
						)
					
					    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 6)
					
					RETURN SUMX( __FilteredTable, [@Students At Level] )
				formatString: 0
				lineageTag: a2cf9272-e7db-4400-87ff-c1009e77cb46

			measure 'Percentage Of Students Tested With High Numeracy In Grade BL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with High Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "BL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 001a5102-7096-4460-89e3-c4da2e95658c

			measure 'Percentage Of Students Tested With High Numeracy In Grade EL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with High Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "EL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: e6cafb5c-b178-462a-a3b5-f3942aab4247

			measure 'Numeracy Improvement BL to EL (PP)' =
					
					VAR __EL = [Percentage Of Students Tested With High Numeracy In Grade EL]
					VAR __BL = [Percentage Of Students Tested With High Numeracy In Grade BL]
					RETURN __EL - __BL
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 90bd8cc0-78a0-4549-8af0-9020b7347640

			measure 'Percentage Of Students Tested With High Numeracy In Cycle' =
					
					VAR __AllStudentsTested =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    ALLSELECTED( 'ASER Cycles Data' ),
					    'ASER Cycles Data'[Subject ID] = 2
					    )
					VAR __NumberOfSudentsTestedHN =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    'Levels in Subjects'[Group Level Sort] = 6
					    )
					VAR __Percentage = DIVIDE( __NumberOfSudentsTestedHN, __AllStudentsTested )
					RETURN __Percentage
				lineageTag: 07de2dbd-1aae-4306-ba05-f8dcd2188488

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Percentage Of Students Tested With High Numeracy In Grade' = ```
					
					DIVIDE( 
					    [Number Of Students Tested with High Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 4661b9a4-6f23-4856-83d9-27f15acd5bb0

			measure 'Number Of Students Tested with Low Numeracy In Grade' =
					
					
					VAR __CurrentCycle = MAX( Cycles[Cycle ID] )
					
						VAR __GradesData =
						SELECTCOLUMNS(
							'ASER CIV Data',
							"@Cycle ID", 'ASER CIV Data'[Cycle ID],
							"@Grade", RELATED( Grades[Grade] ),
					        "@Group Level", RELATED( 'Levels in Subjects'[Group Level Sort] ),
							"@Students At Level", 'ASER CIV Data'[Students At Level]
						)
					
					    VAR __FilteredTable = FILTER( __GradesData, [@Cycle ID] = __CurrentCycle  && [@Group Level] = 4)
					
					RETURN SUMX( __FilteredTable, [@Students At Level] )
				formatString: 0
				lineageTag: 7b8873f5-05ca-4796-a7b1-9fdb4f258ba0

			measure 'Percentage Of Students Tested With Low Numeracy In Cycle' =
					
					VAR __AllStudentsTested =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    ALLSELECTED( 'ASER Cycles Data' ),
					    'ASER Cycles Data'[Subject ID] = 2
					    )
					VAR __NumberOfSudentsTestedLN =
					CALCULATE(
					    [Number Of Students Tested In Cycle],
					    'Levels in Subjects'[Group Level Sort] = 3
					    )
					VAR __Percentage = DIVIDE( __NumberOfSudentsTestedLN, __AllStudentsTested )
					RETURN __Percentage
				formatString: 0.0
				lineageTag: 05d1e7fb-1438-4e8b-982e-13274aa1161f

			measure 'Percentage Of Students Tested With Low Numeracy In Grade' = ```
					
					DIVIDE( 
					    [Number Of Students Tested with Low Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 6d2a5faa-4cf3-46a7-bd1d-41d31d8b4a13

			measure 'Percentage Of Students Tested With Low Numeracy In Grade BL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with Low Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "BL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: c03f20e5-6c17-498f-bf5c-16f5b2cee833

			measure 'Percentage Of Students Tested With Low Numeracy In Grade EL' = ```
					
					CALCULATE (DIVIDE( 
					    [Number Of Students Tested with Low Numeracy In Grade],
					    [Number Of Students Tested In Grade]
					    ), Cycles[Cycle] = "EL" )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 3f005491-75a7-4af6-994a-abfd439986c8

			measure 'Numeracy Difficulty Reduction BL to EL (PP)' =
					
					VAR __EL = [Percentage Of Students Tested With Low Numeracy In Grade EL]
					VAR __BL = [Percentage Of Students Tested With Low Numeracy In Grade BL]
					RETURN __BL - __EL
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: aa0fab98-392c-4b0c-93a3-e07b66114535

			measure 'Percentage Of Students Tested With Low Literacy In Grade' = ```
					
					DIVIDE( 
					    [Number Of Students Tested with Low Literacy In Grade],
					    [Number Of Students Tested In Grade]
					    )
					```
				formatString: 0.0\ %;-0.0\ %;0.0\ %
				lineageTag: 16eb3db3-45d0-4e40-b785-cc7aad0904e1

			measure 'Selected Cycle' = MAX( Cycles[Cycle Name] )
				lineageTag: 825df335-d53b-4f76-ba13-9c005806ccdd

			measure 'Compared To Cycle' =
					
					VAR __CurrentCycleID = MAX( Cycles[Cycle ID] )
					VAR __CurrentCycle = MAX( Cycles[Cycle Name] )
					VAR __ComparedToID = __CurrentCycleID - 'Cycles interval'[Valeur Cycles Interval]
					VAR __ComparedToName = LOOKUPVALUE( Cycles[Cycle Name], Cycles[Cycle ID], __ComparedToID)
					
					RETURN __ComparedToName
				lineageTag: 063a0961-39b6-44c8-8f64-9217198fd396

			measure 'Compared To Cycle ID' = MAX( 'Compared To Cycles'[Cycle ID] )
				formatString: 0
				lineageTag: ce606d40-11ec-402f-b244-5a91620fb5cf

			measure 'Selected Cycle ID' = MAX( 'Cycles'[Cycle ID] )
				formatString: 0
				lineageTag: 42af7bb4-205a-401d-a27b-782b9f869bb9

			measure 'Cycle Comparison Revelance Test' =
					
					VAR __CycleDiff = [Selected Cycle ID] - [Compared To Cycle ID]
					VAR __ComparisonValidityTest = IF( __CycleDiff >= 1, 1, 0 )
					RETURN __ComparisonValidityTest
				formatString: 0
				lineageTag: 863f31d6-d01c-43c9-97f5-d47f1aa66918

			partition Mesures = m
				mode: import
				source =
						let
						    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
						    #"Colonnes supprimées" = Table.RemoveColumns(Source,{"Colonne 1"})
						in
						    #"Colonnes supprimées"

			annotation PBI_ResultType = Table

		table 'ASER Cycles Data'
			lineageTag: 18a17507-c61a-4fcb-a27f-989c1212532f

			column Period
				dataType: string
				lineageTag: 08228b31-5b19-4f6d-b6e4-a722481d3836
				summarizeBy: none
				sourceColumn: Period

				annotation SummarizationSetBy = Automatic

			column 'Cycle ID'
				dataType: int64
				formatString: 0
				lineageTag: 3bd2432b-ab4a-42d2-a24f-1b115e8a74bf
				summarizeBy: none
				sourceColumn: Cycle ID

				annotation SummarizationSetBy = Automatic

			column 'Subject ID'
				dataType: int64
				formatString: 0
				lineageTag: 155aac7a-fe26-4843-a0a0-71e7b1687a54
				summarizeBy: count
				sourceColumn: Subject ID

				annotation SummarizationSetBy = Automatic

			column 'Level ID'
				dataType: int64
				formatString: 0
				lineageTag: ac99df48-a606-48bc-9247-e0ab163bcbde
				summarizeBy: none
				sourceColumn: Level ID

				annotation SummarizationSetBy = Automatic

			column 'DRENAET ID'
				dataType: int64
				formatString: 0
				lineageTag: 708d21e6-a347-413d-9ba7-1d12489a5b8e
				summarizeBy: count
				sourceColumn: DRENAET ID

				annotation SummarizationSetBy = Automatic

			column 'IEPP ID'
				dataType: int64
				formatString: 0
				lineageTag: 6697cda7-9585-4eb4-95b5-6270f5f77f9a
				summarizeBy: count
				sourceColumn: IEPP ID

				annotation SummarizationSetBy = Automatic

			column 'School ID'
				dataType: int64
				formatString: 0
				lineageTag: 6e2eea45-0afd-43bd-b349-465e3962b27f
				summarizeBy: none
				sourceColumn: School ID

				annotation SummarizationSetBy = Automatic

			column 'Students In School'
				dataType: double
				lineageTag: 7983a425-f1b1-41ae-ae3e-083030b53ae0
				summarizeBy: sum
				sourceColumn: Students In School

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Boys Tested In School'
				dataType: double
				lineageTag: 2bc63a26-c2a4-4d30-8cda-1cfeca4b3fb2
				summarizeBy: sum
				sourceColumn: Boys Tested In School

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Girls Tested In School'
				dataType: double
				lineageTag: 2d9579d6-1739-4980-b8f0-f9e06703ad70
				summarizeBy: sum
				sourceColumn: Girls Tested In School

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Teacher Male In School'
				dataType: double
				lineageTag: 90dd3ae3-4a8b-4108-a2ea-a403f4f7679d
				summarizeBy: sum
				sourceColumn: Teacher Male In School

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Teacher Female In School'
				dataType: double
				lineageTag: 2e2457c8-e4a4-460e-b302-a794f81bab3e
				summarizeBy: sum
				sourceColumn: Teacher Female In School

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Students At Level'
				dataType: double
				lineageTag: 24c1853c-4d26-4536-8916-ccb380358ddb
				summarizeBy: sum
				sourceColumn: Students At Level

				annotation SummarizationSetBy = Automatic

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column 'Entry Date'
				dataType: dateTime
				formatString: Long Date
				lineageTag: eea07afa-83e8-4b50-83d8-d1276931652c
				summarizeBy: none
				sourceColumn: Entry Date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			partition 'ASER Cycles Data' = m
				mode: import
				source =
						let
						    Source = #"ASER CIV Data",
						    #"Lignes groupées" = Table.Group(Source, {"Period", "Cycle ID", "Subject ID", "Level ID", "DRENAET ID", "IEPP ID", "School ID"}, {{"Students In School", each List.Sum([Students In Class]), type nullable number}, {"Boys Tested In School", each List.Sum([Boys Tested In Class]), type nullable number}, {"Girls Tested In School", each List.Sum([Girls Tested In Class]), type nullable number}, {"Teacher Male In School", each List.Max([Teacher Male In School]), type nullable number}, {"Teacher Female In School", each List.Max([Teacher Female In School]), type nullable number}, {"Students At Level", each List.Sum([Students At Level]), type number}, {"Entry Date", each List.Max([Entry Date]), type nullable date}})
						in
						    #"Lignes groupées"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table Schools
			lineageTag: 6a0c48f1-cfb1-412e-902a-b24dbefd0d7d

			column DRENAET
				dataType: string
				lineageTag: dbe3955f-3885-4400-b8d6-4e0f7a80b869
				summarizeBy: none
				sourceColumn: DRENAET

				annotation SummarizationSetBy = Automatic

			column IEPP
				dataType: string
				lineageTag: 74213b48-b5da-40d3-ad9d-69f91140dc57
				summarizeBy: none
				sourceColumn: IEPP

				annotation SummarizationSetBy = Automatic

			column School
				dataType: string
				lineageTag: 56c4aac3-912c-4295-a469-6c9bf9cdae8d
				summarizeBy: none
				sourceColumn: School

				annotation SummarizationSetBy = Automatic

			column 'School ID'
				dataType: int64
				formatString: 0
				lineageTag: ac8989ac-b59e-46b1-bf30-e918e11a73fa
				summarizeBy: none
				sourceColumn: School ID

				annotation SummarizationSetBy = Automatic

			partition Schools = m
				mode: import
				source =
						let
						    Source = Table.Combine({#"Old Data", #"New Data"}),
						    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
						    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
						    #"Autres colonnes supprimées" = Table.SelectColumns(#"Valeur remplacée",{"DRENAET", "IEPP", "School", "Grade"}),
						    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
						    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 0, 1, Int64.Type),
						    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "Grade ID"}}),
						    #"Requêtes fusionnées" = Table.NestedJoin(#"Colonnes renommées", {"DRENAET"}, #"DRENAETs and Donors", {"DRENAET"}, "DRENAETs and Donors", JoinKind.LeftOuter),
						    #"DRENAETs and Donors développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "DRENAETs and Donors", {"Donor"}, {"Donor"}),
						    #"Autres colonnes supprimées1" = Table.SelectColumns(#"DRENAETs and Donors développé",{"DRENAET", "IEPP", "School"}),
						    #"Doublons supprimés1" = Table.Distinct(#"Autres colonnes supprimées1"),
						    #"Index ajouté1" = Table.AddIndexColumn(#"Doublons supprimés1", "Index", 0, 1, Int64.Type),
						    #"Colonnes renommées1" = Table.RenameColumns(#"Index ajouté1",{{"Index", "School ID"}})
						in
						    #"Colonnes renommées1"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		table 'Cycles interval'
			lineageTag: b34c730b-c264-4aa7-8a8d-716fb62668a4

			measure 'Valeur Cycles Interval' = SELECTEDVALUE('Cycles interval'[Cycles Interval], 1)
				formatString: 0
				lineageTag: 07adeb8e-4291-4989-b79e-bbc9a0346a03

			column 'Cycles Interval'
				formatString: 0
				lineageTag: eb6fc780-20a5-4d69-8f13-7434931bb1f3
				summarizeBy: none
				sourceColumn: [Value]

				extendedProperty ParameterMetadata = {"version":0}

				annotation SummarizationSetBy = User

			partition 'Cycles interval' = calculated
				mode: import
				source = GENERATESERIES(1, 5, 1)

			annotation PBI_Id = 7408f001186f4868b53db12d3417c2b4

		table 'Compared To Cycles'
			lineageTag: ff9b4cf5-9621-4b4e-b655-ba26f6cf805f

			column 'Cycle ID'
				dataType: int64
				formatString: 0
				lineageTag: d26f6060-dd43-4c54-9b9d-8c1ed8b8571e
				summarizeBy: count
				sourceColumn: Cycle ID

				annotation SummarizationSetBy = Automatic

			column 'Cycle Name'
				dataType: string
				lineageTag: af0e7078-acd4-49de-be2e-27b55f6f24d4
				summarizeBy: none
				sourceColumn: Cycle Name

				annotation SummarizationSetBy = Automatic

			partition 'Compared To Cycles' = m
				mode: import
				source =
						let
						    Source = Cycles,
						    #"Autres colonnes supprimées" = Table.SelectColumns(Source,{"Cycle ID", "Cycle Name"})
						in
						    #"Autres colonnes supprimées"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		relationship AutoDetected_5b318c4c-725d-4f59-a8bf-cc2baf97c8c3
			fromColumn: 'ASER CIV Data'.'Grade ID'
			toColumn: Grades.'Grade ID'

		relationship AutoDetected_f34f51e3-fb32-4e3c-8dc6-18e7b08cf6d9
			fromColumn: 'ASER CIV Data'.'Cycle ID'
			toColumn: Cycles.'Cycle ID'

		relationship AutoDetected_f063efa2-131c-4be8-8b3f-a3571619a31b
			fromColumn: 'ASER CIV Data'.'Level ID'
			toColumn: 'Levels in Subjects'.'Level ID'

		relationship d9062aef-b932-8c85-997b-bbd4d62d7c81
			fromColumn: 'ASER CIV Data'.'Entry Date'
			toColumn: 'Entry Calendar'.Date

		relationship AutoDetected_3e76a00b-ccaf-417b-a681-ee665b1e652c
			fromColumn: 'ASER Cycles Data'.'Cycle ID'
			toColumn: Cycles.'Cycle ID'

		relationship AutoDetected_825f7c96-80d4-47ef-85de-6baa8015b204
			fromColumn: 'ASER Cycles Data'.'Level ID'
			toColumn: 'Levels in Subjects'.'Level ID'

		relationship 1d750ce0-05be-8698-19b8-e5d44a069abf
			fromColumn: 'ASER Cycles Data'.'Entry Date'
			toColumn: 'Entry Calendar'.Date

		relationship AutoDetected_bd3d627d-7123-46e6-940a-1f70425ee73e
			fromColumn: 'ASER Cycles Data'.'School ID'
			toColumn: Schools.'School ID'

		cultureInfo fr-FR

			linguisticMetadata = {"Version":"4.1.0","Language":"en-US","Entities":{"ASER_CIV_data":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data"}},"State":"Generated","Terms":[{"ASER CIV data":{"State":"Generated"}},{"data":{"State":"Generated","Weight":0.97}},{"CIV data":{"State":"Generated","Weight":0.97}},{"aser civ information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser civ fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser civ info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser civ statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"civ information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"civ fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"civ info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"civ statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"aser civ document":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"aser civ figure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"ASER_CIV_data.student_in_class":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Students In Class"}},"State":"Generated","Terms":[{"student in class":{"State":"Generated"}},{"class":{"State":"Generated","Weight":0.97}},{"in class":{"State":"Generated","Weight":0.97}},{"student":{"State":"Generated","Weight":0.97}},{"in classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"in category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"in genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"in course":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"in grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"in lecture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"in lesson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.boy_tested_in_class":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Boys Tested In Class"}},"State":"Generated","Terms":[{"boy tested in class":{"State":"Generated"}},{"boy tested in classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"boy tested in category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"boy tested in genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"boy tested in course":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"boy tested in grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"boy tested in lecture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"boy tested in lesson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"boy tested in period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"boy tested in rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"lad tested in class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"ASER_CIV_data.girl_tested_in_class":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Girls Tested In Class"}},"State":"Generated","Terms":[{"girl tested in class":{"State":"Generated"}},{"girl tested in classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"girl tested in category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"girl tested in genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"girl tested in course":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"girl tested in grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"girl tested in lecture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"girl tested in lesson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"girl tested in period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"girl tested in rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"lassie tested in class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"ASER_CIV_data.student_tested_in_class":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Students Tested In Class"}},"State":"Generated","Terms":[{"student tested in class":{"State":"Generated"}},{"student tested in classification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"student tested in category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"student tested in genre":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.617}},{"student tested in course":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"student tested in grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"student tested in lecture":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"student tested in lesson":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"student tested in period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"student tested in rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.599}},{"scholar tested in class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}}]},"ASER_CIV_data.teacher_male_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Teacher Male In School"}},"State":"Generated","Terms":[{"teacher male in school":{"State":"Generated"}},{"in school":{"State":"Generated","Weight":0.97}},{"male in school":{"State":"Generated","Weight":0.97}},{"male":{"State":"Generated","Weight":0.97}},{"teacher male":{"State":"Generated","Weight":0.97}},{"in seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"teacher bloke in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher boy in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher fella in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher gentleman in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"in university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"ASER_CIV_data.teacher_female_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Teacher Female In School"}},"State":"Generated","Terms":[{"teacher female in school":{"State":"Generated"}},{"in school":{"State":"Generated","Weight":0.97}},{"female in school":{"State":"Generated","Weight":0.97}},{"female":{"State":"Generated","Weight":0.97}},{"teacher female":{"State":"Generated","Weight":0.97}},{"in seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"teacher lady in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher woman in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"in university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in institute":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lady in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"ASER_CIV_data.student_at_level":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Students At Level"}},"State":"Generated","Terms":[{"student at level":{"State":"Generated"}},{"student":{"State":"Generated","Weight":0.97}},{"student at quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"student at threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"student at amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"scholar at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"pupil at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"schoolboy at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"ASER_CIV_data.grade_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Grade ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"grade ID":{"State":"Generated"}},{"grade identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Cycle ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"cycle ID":{"State":"Generated"}},{"cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.level_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Level ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"level ID":{"State":"Generated"}},{"level identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quantity id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"threshold id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"amount id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"point id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tier id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"ASER_CIV_data.entry_date":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Entry Date"}},"State":"Generated","Terms":[{"entry date":{"State":"Generated"}},{"date":{"State":"Generated","Weight":0.7}},{"entry moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"entry period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"ASER_CIV_data.school_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"School ID"}},"State":"Generated","Terms":[{"school ID":{"State":"Generated"}},{"school identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.drenaet_id":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"DRENAET ID"}},"State":"Generated","Terms":[{"drenaet id":{"State":"Generated"}},{"drenaet identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.iepp_id":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"IEPP ID"}},"State":"Generated","Terms":[{"iepp id":{"State":"Generated"}},{"iepp identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_CIV_data.test":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"test"}},"State":"Generated","Terms":[{"test":{"State":"Generated"}},{"examination":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"exam":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"investigation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"analysis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"quiz":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"trial":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"check":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"experiment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"assay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"ASER_CIV_data.period":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Period"}},"State":"Generated","Terms":[{"period":{"State":"Generated"}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"ASER_CIV_data.subject_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER CIV Data","ConceptualProperty":"Subject ID"}},"State":"Generated","Terms":[{"subject ID":{"State":"Generated"}},{"subject identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"grade":{"Definition":{"Binding":{"ConceptualEntity":"Grades"}},"State":"Generated","Terms":[{"grade":{"State":"Generated"}},{"evaluation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"score":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"rating":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ranking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"status":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"caliber":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"position":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"grade.drenaet":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"DRENAET"}},"State":"Generated","Terms":[{"drenaet":{"State":"Generated"}}]},"grade.iepp":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"IEPP"}},"State":"Generated","Terms":[{"iepp":{"State":"Generated"}}]},"grade.school":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"School"}},"State":"Generated","Terms":[{"school":{"State":"Generated"}},{"seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"institute":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"coterie":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"brotherhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"sisterhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"grade.grade":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"Grade"}},"State":"Generated","Terms":[{"grade":{"State":"Generated"}},{"evaluation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"score":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"mark":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"rating":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"ranking":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"status":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"caliber":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"degree":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"position":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"grade.grade_ID":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"Grade ID"}},"State":"Generated","Terms":[{"grade ID":{"State":"Generated"}},{"ID":{"State":"Generated","Weight":0.97}},{"grade identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grade credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Identifier"},"grade.donor":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"Donor"}},"State":"Generated","Terms":[{"donor":{"State":"Generated"}},{"giver":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"contributor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"benefactor":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"patron":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"supporter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"subscriber":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"presenter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"grade.school_ID":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"School ID"}},"State":"Generated","Terms":[{"school ID":{"State":"Generated"}},{"school identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"grade.drenaet_id":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"DRENAET ID"}},"State":"Generated","Terms":[{"drenaet id":{"State":"Generated"}},{"drenaet identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"grade.iepp_id":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"IEPP ID"}},"State":"Generated","Terms":[{"iepp id":{"State":"Generated"}},{"iepp identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"cycle":{"Definition":{"Binding":{"ConceptualEntity":"Cycles"}},"State":"Generated","Terms":[{"cycle":{"State":"Generated"}},{"series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"rotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"succession":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"progression":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"set":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"round":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"run":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"cycle.cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"Cycles","ConceptualProperty":"Cycle ID"}},"State":"Generated","Terms":[{"cycle ID":{"State":"Generated"}},{"ID":{"State":"Generated","Weight":0.97}},{"cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Identifier"},"cycle.cycle":{"Definition":{"Binding":{"ConceptualEntity":"Cycles","ConceptualProperty":"Cycle"}},"State":"Generated","Terms":[{"cycle":{"State":"Generated"}},{"series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"rotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"succession":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"progression":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"sequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"set":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"round":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"run":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"cycle.period":{"Definition":{"Binding":{"ConceptualEntity":"Cycles","ConceptualProperty":"Period"}},"State":"Generated","Terms":[{"period":{"State":"Generated"}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"cycle.cycle_name":{"Definition":{"Binding":{"ConceptualEntity":"Cycles","ConceptualProperty":"Cycle Name"}},"State":"Generated","Terms":[{"cycle name":{"State":"Generated"}},{"name":{"State":"Generated","Weight":0.97}},{"cycle nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Name"},"level_in_subjects":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects"}},"State":"Generated","Terms":[{"level in subjects":{"State":"Generated"}},{"level in subject":{"Type":"Noun","State":"Generated","Weight":0.78}},{"subjects":{"State":"Generated","Weight":0.97}},{"subject":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"in subjects":{"State":"Generated","Weight":0.97}},{"in subject":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"quantity in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"threshold in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"amount in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"grade in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"point in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"rank in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"tier in subject":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"in topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in substance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"level_in_subjects.level":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Level"}},"State":"Generated","Terms":[{"level":{"State":"Generated"}},{"threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"level_in_subjects.subject":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Subject"}},"State":"Generated","Terms":[{"subject":{"State":"Generated"}},{"topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"substance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"theme":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"focus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"question":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"issue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"matter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"business":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"text":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"specialty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"level_in_subjects.level_ID":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Level ID"}},"State":"Generated","Terms":[{"level ID":{"State":"Generated"}},{"level identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quantity id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"threshold id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"amount id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"point id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tier id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"level_in_subjects.subject_ID":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Subject ID"}},"State":"Generated","Terms":[{"subject ID":{"State":"Generated"}},{"subject identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"entry_calendar":{"Definition":{"Binding":{"ConceptualEntity":"Entry Calendar"}},"State":"Generated","Terms":[{"entry calendar":{"State":"Generated"}},{"calendar":{"State":"Generated","Weight":0.97}},{"entry almanac":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"entry datebook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"entry agenda":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"entry logbook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"entry diary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"almanac":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"datebook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"agenda":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"logbook":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"diary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}}]},"entry_calendar.date":{"Definition":{"Binding":{"ConceptualEntity":"Entry Calendar","ConceptualProperty":"Date"}},"State":"Generated","Terms":[{"date":{"State":"Generated"}},{"moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}}],"SemanticType":"Time"},"mesure":{"Definition":{"Binding":{"ConceptualEntity":"Mesures"}},"State":"Generated","Terms":[{"mesure":{"State":"Generated","Weight":0.87}}]},"mesure.number_of_DRENAETs":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of DRENAETs"}},"State":"Generated","Terms":[{"number of DRENAETs":{"State":"Generated"}},{"quantity of drenaet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.769}},{"amount of drenaet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"count of drenaet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"number of drenaet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"no of drenaet":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"mesure.number_of_IEPPs":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of IEPPs"}},"State":"Generated","Terms":[{"number of IEPPs":{"State":"Generated"}},{"quantity of iepp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.769}},{"amount of iepp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"count of iepp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"number of iepp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"no of iepp":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"mesure.number_of_schools":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Schools"}},"State":"Generated","Terms":[{"number of schools":{"State":"Generated"}},{"quantity of school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.769}},{"amount of school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"count of school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"number of school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"no of school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"mesure.number_of_schools_tested":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Schools Tested"}},"State":"Generated","Terms":[{"number of schools tested":{"State":"Generated"}},{"quantity of school tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.786}},{"amount of school tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"count of school tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"number of school tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"no of school tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}}]},"mesure.number_of_students":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students"}},"State":"Generated","Terms":[{"number of students":{"State":"Generated"}},{"quantity of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.769}},{"amount of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"count of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"number of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.746}},{"no of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"mesure.entity__number_of_students":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"_Number Of Students"}},"State":"Generated","Terms":[{"_number of students":{"State":"Generated"}},{"_ quantity of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.786}},{"_ amount of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"_ count of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"_ number of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"_ no of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}}]},"mesure.percentage_of_students":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students"}},"State":"Generated","Terms":[{"percentage of students":{"State":"Generated"}},{"ratio of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"measurement of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"calculation of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"fraction of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"proportion of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"part of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"section of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"entitlement of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"take of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}},{"profit of student":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.468}}]},"mesure.number_of_students_tested":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested"}},"State":"Generated","Terms":[{"number of students tested":{"State":"Generated"}},{"quantity of student tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.786}},{"amount of student tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"count of student tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"number of student tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"no of student tested":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}}]},"mesure.number_of_students_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students In Cycle"}},"State":"Generated","Terms":[{"number of students in cycle":{"State":"Generated"}},{"quantity of student in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.8}},{"amount of student in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"count of student in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"number of student in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"no of student in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}}]},"mesure.number_of_students_tested_BL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested BL"}},"State":"Generated","Terms":[{"number of students tested BL":{"State":"Generated"}},{"quantity of student tested bl":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.8}},{"amount of student tested bl":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"count of student tested bl":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"number of student tested bl":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"no of student tested bl":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}}]},"mesure.number_of_students_v2":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students v2"}},"State":"Generated","Terms":[{"number of students v2":{"State":"Generated"}},{"quantity of student v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.786}},{"amount of student v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"count of student v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"number of student v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"no of student v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}}]},"mesure.number_of_students_tested_v2":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested v2"}},"State":"Generated","Terms":[{"number of students tested v2":{"State":"Generated"}},{"quantity of student tested v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.8}},{"amount of student tested v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"count of student tested v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"number of student tested v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.776}},{"no of student tested v2":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.757}}]},"mesure.mesure":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Mesure"}},"State":"Generated","Terms":[{"mesure":{"State":"Generated"}}]},"mesure.number_of_students_tested_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested In Cycle"}},"State":"Generated","Terms":[{"number of students tested in cycle":{"State":"Generated"}},{"Students tested After":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.number_of_students_reached_in_program":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Reached In Program"}},"State":"Generated","Terms":[{"number of students reached in program":{"State":"Generated"}},{"Pupils":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_change_rate_of_students_tested":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Change Rate Of Students Tested"}},"State":"Generated","Terms":[{"percentage change rate of students tested":{"State":"Generated"}},{"Percentage change Rate":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.number_of_students_tested_in_previous_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested In Previous Cycle"}},"State":"Generated","Terms":[{"number of students tested in previous cycle":{"State":"Generated"}},{"Students tested Before":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.cycles_compared":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Cycles Compared"}},"State":"Generated","Terms":[{"cycles compared":{"State":"Generated"}},{"series compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"rotation compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"succession compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"progression compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"sequence compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"set compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"round compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"phase compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"run compared":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"mesure.boys_tested_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Boys Tested In Cycle"}},"State":"Generated","Terms":[{"boys tested in cycle":{"State":"Generated"}},{"lad tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"schoolboy tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"son tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"youngster tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"child tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teenager tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"youths tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teen-ager tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"Boys":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.girls_tested_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Girls Tested In Cycle"}},"State":"Generated","Terms":[{"girls tested in cycle":{"State":"Generated"}},{"lassie tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teenager tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mademoiselle tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"lass tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"schoolgirl tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"youngster tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"child tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teen-ager tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"miss tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"adolescent tested in cycle":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"Girls":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"ASER_cycles_data":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data"}},"State":"Generated","Terms":[{"ASER cycles data":{"State":"Generated"}},{"ASER cycle data":{"Type":"Noun","State":"Generated","Weight":0.78}},{"data":{"State":"Generated","Weight":0.97}},{"cycles data":{"State":"Generated","Weight":0.97}},{"cycle data":{"Type":"Noun","State":"Generated","Weight":0.7566}},{"aser cycle information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser cycle fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser cycle info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"aser cycle statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"cycle information":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle fact":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle info":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle statistic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"aser cycle document":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}},{"aser cycle figure":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"ASER_cycles_data.period":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Period"}},"State":"Generated","Terms":[{"period":{"State":"Generated"}},{"era":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"epoch":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"age":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"stage":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}},{"phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.452}}]},"ASER_cycles_data.cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Cycle ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"cycle ID":{"State":"Generated"}},{"cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_cycles_data.subject_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Subject ID"}},"State":"Generated","Terms":[{"subject ID":{"State":"Generated"}},{"subject identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"subject credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_cycles_data.level_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Level ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"level ID":{"State":"Generated"}},{"level identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"level credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"quantity id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"threshold id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"amount id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"point id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tier id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}}]},"ASER_cycles_data.drenaet_id":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"DRENAET ID"}},"State":"Generated","Terms":[{"drenaet id":{"State":"Generated"}},{"drenaet identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"drenaet credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_cycles_data.iepp_id":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"IEPP ID"}},"State":"Generated","Terms":[{"iepp id":{"State":"Generated"}},{"iepp identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"iepp credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_cycles_data.school_ID":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"School ID"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"school ID":{"State":"Generated"}},{"school identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"ASER_cycles_data.student_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Students In School"}},"State":"Generated","Terms":[{"student in school":{"State":"Generated"}},{"in school":{"State":"Generated","Weight":0.97}},{"student":{"State":"Generated","Weight":0.97}},{"scholar in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"pupil in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"schoolboy in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"schoolgirl in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"schoolchild in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"learner in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"in seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"ASER_cycles_data.boy_tested_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Boys Tested In School"}},"State":"Generated","Terms":[{"boy tested in school":{"State":"Generated"}},{"lad tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"schoolboy tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"son tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"youngster tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"child tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teenager tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teen-ager tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"youth tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"ASER_cycles_data.girl_tested_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Girls Tested In School"}},"State":"Generated","Terms":[{"girl tested in school":{"State":"Generated"}},{"lassie tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teenager tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"mademoiselle tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"lass tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"schoolgirl tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"youngster tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"child tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"teen-ager tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"miss tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"adolescent tested in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"ASER_cycles_data.teacher_male_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Teacher Male In School"}},"State":"Generated","Terms":[{"teacher male in school":{"State":"Generated"}},{"in school":{"State":"Generated","Weight":0.97}},{"male in school":{"State":"Generated","Weight":0.97}},{"male":{"State":"Generated","Weight":0.97}},{"teacher male":{"State":"Generated","Weight":0.97}},{"in seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"teacher bloke in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher boy in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher fella in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher gentleman in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"in university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"ASER_cycles_data.teacher_female_in_school":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Teacher Female In School"}},"State":"Generated","Terms":[{"teacher female in school":{"State":"Generated"}},{"in school":{"State":"Generated","Weight":0.97}},{"female in school":{"State":"Generated","Weight":0.97}},{"female":{"State":"Generated","Weight":0.97}},{"teacher female":{"State":"Generated","Weight":0.97}},{"in seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"in department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"teacher lady in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"teacher woman in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.489}},{"in university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"in institute":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"lady in school":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"ASER_cycles_data.student_at_level":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Students At Level"}},"State":"Generated","Terms":[{"student at level":{"State":"Generated"}},{"student":{"State":"Generated","Weight":0.97}},{"student at quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"student at threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"student at amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"student at tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"scholar at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"pupil at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"schoolboy at level":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}}]},"ASER_cycles_data.entry_date":{"Definition":{"Binding":{"ConceptualEntity":"ASER Cycles Data","ConceptualProperty":"Entry Date"}},"State":"Generated","Terms":[{"entry date":{"State":"Generated"}},{"date":{"State":"Generated","Weight":0.7}},{"entry moment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"entry period":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"SemanticType":"Time"},"school":{"Definition":{"Binding":{"ConceptualEntity":"Schools"}},"State":"Generated","Terms":[{"school":{"State":"Generated"}},{"seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"institute":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"coterie":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"brotherhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"sisterhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"school.drenaet":{"Definition":{"Binding":{"ConceptualEntity":"Schools","ConceptualProperty":"DRENAET"}},"State":"Generated","Terms":[{"drenaet":{"State":"Generated"}}]},"school.iepp":{"Definition":{"Binding":{"ConceptualEntity":"Schools","ConceptualProperty":"IEPP"}},"State":"Generated","Terms":[{"iepp":{"State":"Generated"}}]},"school.school":{"Definition":{"Binding":{"ConceptualEntity":"Schools","ConceptualProperty":"School"}},"State":"Generated","Terms":[{"school":{"State":"Generated"}},{"school name":{"State":"Generated"}},{"seminary":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"conservatory":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"faculty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"department":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"university":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"college":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"institute":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"coterie":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"brotherhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}},{"sisterhood":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}],"NameType":"Name"},"school.school_ID":{"Definition":{"Binding":{"ConceptualEntity":"Schools","ConceptualProperty":"School ID"}},"State":"Generated","Terms":[{"school ID":{"State":"Generated"}},{"ID":{"State":"Generated","Weight":0.97}},{"school identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"school credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}],"NameType":"Identifier"},"cycles_interval":{"Definition":{"Binding":{"ConceptualEntity":"Cycles interval"}},"State":"Generated","Terms":[{"cycles interval":{"State":"Generated","Weight":0.87}},{"cycle interval":{"Type":"Noun","State":"Generated","Weight":0.6786}},{"interval":{"State":"Generated","Weight":0.8439}},{"cycle intermission":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle interlude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"intermission":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"interlude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"cycle break":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle pause":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle recess":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle rest":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle wait":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle interim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"cycles_interval.cycles_interval":{"Definition":{"Binding":{"ConceptualEntity":"Cycles interval","ConceptualProperty":"Cycles Interval"}},"State":"Generated","Terms":[{"cycles interval":{"State":"Generated"}},{"cycle interval":{"Type":"Noun","State":"Generated","Weight":0.78}},{"interval":{"State":"Generated","Weight":0.97}},{"cycle intermission":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle interlude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"intermission":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"interlude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"cycle break":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle pause":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle recess":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle rest":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle wait":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle interim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"cycles_interval.valeur_cycles_interval":{"Definition":{"Binding":{"ConceptualEntity":"Cycles interval","ConceptualProperty":"Valeur Cycles Interval"}},"State":"Generated","Terms":[{"valeur cycles interval":{"State":"Generated"}},{"valeur cycle intermission":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"valeur cycle interlude":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"valeur cycle break":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle pause":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle recess":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle rest":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle wait":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle interim":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"valeur cycle hiatus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}},{"valeur cycle separation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.482}}]},"grade.grade_sort":{"Definition":{"Binding":{"ConceptualEntity":"Grades","ConceptualProperty":"Grade Sort"}},"State":"Generated","Terms":[{"grade sort":{"State":"Generated"}},{"grade category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"grade genus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"grade species":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"grade variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"grade nature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"grade kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"grade class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"grade type":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"grade ilk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"grade order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"cycle.cycle_sort":{"Definition":{"Binding":{"ConceptualEntity":"Cycles","ConceptualProperty":"Cycle Sort"}},"State":"Generated","Terms":[{"cycle sort":{"State":"Generated"}},{"cycle category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle genus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle species":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle nature":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"cycle kind":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle class":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle type":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle ilk":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"cycle order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"level_in_subjects.level_sort":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Level Sort"}},"State":"Generated","Terms":[{"level sort":{"State":"Generated"}},{"quantity sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"threshold sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.6}},{"amount sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"point sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"rank sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"tier sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.582}},{"level category":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"level genus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"level species":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"level variety":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}}]},"level_in_subjects.grouped_level":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Grouped Level"}},"State":"Generated","Terms":[{"grouped level":{"State":"Generated"}},{"grouped quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grouped threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grouped amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"level_in_subjects.group_level_sort":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","ConceptualProperty":"Group Level Sort"}},"State":"Generated","Terms":[{"group level sort":{"State":"Generated"}},{"category level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"organization level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"group quantity sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"group threshold sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.609}},{"bracket level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"class level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"crew level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"team level sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"group amount sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}},{"group grade sort":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.591}}]},"level_in_subjects.subject_hierarchy":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","Hierarchy":"Subject Hierarchy"}},"State":"Generated","Terms":[{"subject hierarchy":{"State":"Generated"}},{"hierarchy":{"State":"Generated","Weight":0.97}},{"subject ladder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"subject grading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"subject order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"subject pyramid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"ladder":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"grading":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"order":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"pyramid":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}}]},"level_in_subjects.subject_hierarchy.subject":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","Hierarchy":"Subject Hierarchy","HierarchyLevel":"Subject"}},"State":"Generated","Terms":[{"subject":{"State":"Generated"}},{"topic":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"substance":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.491}},{"theme":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"focus":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"question":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"issue":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"matter":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"business":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"text":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.476}},{"specialty":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.466}}]},"level_in_subjects.subject_hierarchy.grouped_level":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","Hierarchy":"Subject Hierarchy","HierarchyLevel":"Grouped Level"}},"State":"Generated","Terms":[{"grouped level":{"State":"Generated"}},{"grouped quantity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grouped threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"grouped amount":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped grade":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped rank":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"grouped tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"level_in_subjects.subject_hierarchy.level":{"Definition":{"Binding":{"ConceptualEntity":"Levels in Subjects","Hierarchy":"Subject Hierarchy","HierarchyLevel":"Level"}},"State":"Generated","Terms":[{"level":{"State":"Generated"}},{"threshold":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.736}},{"point":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}},{"tier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.714}}]},"mesure.percentage_of_students_tested_with_high_Literacy_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Literacy In Cycle"}},"State":"Generated","Terms":[{"percentage of students tested with high Literacy in cycle":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Literacy In Grade"}},"State":"Generated","Terms":[{"percentage of students tested with high Literacy in grade":{"State":"Generated"}}]},"mesure.number_of_students_tested_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested In Grade"}},"State":"Generated","Terms":[{"number of students tested in grade":{"State":"Generated"}}]},"mesure.number_of_students_tested_with_high_Literacy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested with High Literacy In Grade"}},"State":"Generated","Terms":[{"number of students tested with high Literacy in grade":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_BL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Literacy In Grade BL"}},"State":"Generated","Terms":[{"percentage of students tested with high Literacy in grade BL":{"State":"Generated"}},{"Can read at least a simple para at BL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_EL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Literacy In Grade EL"}},"State":"Generated","Terms":[{"percentage of students tested with high Literacy in grade EL":{"State":"Generated"}},{"Can read at least a simple para at EL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.Literacy_Improvement_BL_to_EL_PP":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Literacy Improvement BL to EL (PP)"}},"State":"Generated","Terms":[{"Literacy Improvement BL to EL (PP)":{"State":"Generated"}},{"Literacy Improvement BL to EL":{"State":"Generated","Weight":0.75}},{"HL change (PP)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Increase from Baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.number_of_students_tested_with_low_Literacy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested with Low Literacy In Grade"}},"State":"Generated","Terms":[{"number of students tested with low Literacy in grade":{"State":"Generated"}}]},"mesure.Literacy_difficulty_reduction_BL_to_EL_PP":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Literacy Difficulty Reduction BL to EL (PP)"}},"State":"Generated","Terms":[{"Literacy difficulty reduction BL to EL (PP)":{"State":"Generated"}},{"Literacy difficulty reduction BL to EL":{"State":"Generated","Weight":0.75}},{"LL change (PP)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Decrease from baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_ML":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Literacy In Grade ML"}},"State":"Generated","Terms":[{"percentage of students tested with low Literacy in grade ML":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_EL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Literacy In Grade EL"}},"State":"Generated","Terms":[{"percentage of students tested with low Literacy in grade EL":{"State":"Generated"}},{"Cannot read words at EL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Endline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_BL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Literacy In Grade BL"}},"State":"Generated","Terms":[{"percentage of students tested with low Literacy in grade BL":{"State":"Generated"}},{"Cannot read words at BL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.number_of_students_tested_with_high_numeracy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested with High Numeracy In Grade"}},"State":"Generated","Terms":[{"number of students tested with high numeracy in grade":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_BL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Numeracy In Grade BL"}},"State":"Generated","Terms":[{"percentage of students tested with high numeracy in grade BL":{"State":"Generated"}},{"Can do 2x2 substraction at BL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_EL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Numeracy In Grade EL"}},"State":"Generated","Terms":[{"percentage of students tested with high numeracy in grade EL":{"State":"Generated"}},{"Can do 2x2 substraction at EL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.numeracy_Improvement_BL_to_EL_PP":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Numeracy Improvement BL to EL (PP)"}},"State":"Generated","Terms":[{"numeracy Improvement BL to EL (PP)":{"State":"Generated"}},{"numeracy Improvement BL to EL":{"State":"Generated","Weight":0.75}},{"HN change (PP)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Increase from baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_high_numeracy_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Numeracy In Cycle"}},"State":"Generated","Terms":[{"percentage of students tested with high numeracy in cycle":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With High Numeracy In Grade"}},"State":"Generated","Terms":[{"percentage of students tested with high numeracy in grade":{"State":"Generated"}}]},"mesure.number_of_students_tested_with_low_numeracy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Number Of Students Tested with Low Numeracy In Grade"}},"State":"Generated","Terms":[{"number of students tested with low numeracy in grade":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_low_numeracy_in_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Numeracy In Cycle"}},"State":"Generated","Terms":[{"percentage of students tested with low numeracy in cycle":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Numeracy In Grade"}},"State":"Generated","Terms":[{"percentage of students tested with low numeracy in grade":{"State":"Generated"}}]},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_BL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Numeracy In Grade BL"}},"State":"Generated","Terms":[{"percentage of students tested with low numeracy in grade BL":{"State":"Generated"}},{"Cannot recognize 2-digit at BL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_EL":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Numeracy In Grade EL"}},"State":"Generated","Terms":[{"percentage of students tested with low numeracy in grade EL":{"State":"Generated"}},{"Cannot recognize 2-digit at EL":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Endline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.numeracy_difficulty_reduction_BL_to_EL_PP":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Numeracy Difficulty Reduction BL to EL (PP)"}},"State":"Generated","Terms":[{"numeracy difficulty reduction BL to EL (PP)":{"State":"Generated"}},{"numeracy difficulty reduction BL to EL":{"State":"Generated","Weight":0.75}},{"LN change (PP)":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}},{"Decrease from baseline":{"State":"Suggested","Source":{"Type":"External","Agent":"PowerBI.VisualColumnRename"},"Weight":0.9}}]},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Percentage Of Students Tested With Low Literacy In Grade"}},"State":"Generated","Terms":[{"percentage of students tested with low Literacy in grade":{"State":"Generated"}}]},"mesure.selected_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Selected Cycle"}},"State":"Generated","Terms":[{"selected cycle":{"State":"Generated"}},{"selected series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"selected rotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"selected succession":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"selected progression":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.5}},{"selected sequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"selected set":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"selected round":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"selected phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}},{"selected run":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.485}}]},"mesure.compared_to_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Compared To Cycle"}},"State":"Generated","Terms":[{"compared to cycle":{"State":"Generated"}},{"compared to series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to rotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to succession":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to progression":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to sequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to set":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to round":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to run":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"mesure.compared_to_cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Compared To Cycle ID"}},"State":"Generated","Terms":[{"compared to cycle ID":{"State":"Generated"}},{"compared to cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"compared to cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"compared to cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.771}},{"compared to cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.748}},{"compared to series id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"compared to rotation id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"compared to succession id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"compared to progression id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"compared to sequence id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"compared to set id":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"mesure.selected_cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Selected Cycle ID"}},"State":"Generated","Terms":[{"selected cycle ID":{"State":"Generated"}},{"selected cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"selected cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"selected cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.762}},{"selected cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.739}}]},"mesure.cycle_comparison_revelance_test":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"Cycle Comparison Revelance Test"}},"State":"Generated","Terms":[{"cycle comparison revelance test":{"State":"Generated"}},{"cycle comparison revelance examination":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cycle comparison revelance exam":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cycle comparison revelance assessment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cycle comparison revelance investigation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cycle comparison revelance analysis":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.514}},{"cycle comparison revelance quiz":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cycle comparison revelance trial":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cycle comparison revelance check":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cycle comparison revelance experiment":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}},{"cycle comparison revelance assay":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.499}}]},"compared_to_cycle":{"Definition":{"Binding":{"ConceptualEntity":"Compared To Cycles"}},"State":"Generated","Terms":[{"compared to cycle":{"State":"Generated"}},{"compared to series":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to rotation":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to succession":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to progression":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.508}},{"compared to sequence":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to set":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to round":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to phase":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}},{"compared to run":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.492}}]},"compared_to_cycle.cycle_ID":{"Definition":{"Binding":{"ConceptualEntity":"Compared To Cycles","ConceptualProperty":"Cycle ID"}},"State":"Generated","Terms":[{"cycle ID":{"State":"Generated"}},{"cycle identification":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identity":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle identifier":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.75}},{"cycle credential":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"compared_to_cycle.cycle_name":{"Definition":{"Binding":{"ConceptualEntity":"Compared To Cycles","ConceptualProperty":"Cycle Name"}},"State":"Generated","Terms":[{"cycle name":{"State":"Generated"}},{"cycle nickname":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle title":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle label":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}},{"cycle tag":{"Type":"Noun","State":"Suggested","Source":{"Agent":"Thesaurus"},"Weight":0.727}}]},"mesure.entity__Literacy_Improvement_BL_to_EL_PP_FormatString":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"_Literacy Improvement BL to EL (PP) FormatString"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"_Literacy Improvement BL to EL (PP) FormatString":{"State":"Generated"}}]},"mesure.entity__Literacy_difficulty_reduction_BL_to_EL_PP_FormatString":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"_Literacy Difficulty Reduction BL to EL (PP) FormatString"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"_Literacy difficulty reduction BL to EL (PP) FormatString":{"State":"Generated"}}]},"mesure.entity__numeracy_Improvement_BL_to_EL_PP_FormatString":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"_Numeracy Improvement BL to EL (PP) FormatString"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"_numeracy Improvement BL to EL (PP) FormatString":{"State":"Generated"}}]},"mesure.entity__numeracy_difficulty_reduction_BL_to_EL_PP_FormatString":{"Definition":{"Binding":{"ConceptualEntity":"Mesures","ConceptualProperty":"_Numeracy Difficulty Reduction BL to EL (PP) FormatString"}},"State":"Generated","Visibility":{"Value":"Hidden"},"Terms":[{"_numeracy difficulty reduction BL to EL (PP) FormatString":{"State":"Generated"}}]}},"Relationships":{"ASER_cycles_data_has_cycle":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"cycle":{"Target":{"Entity":"cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"cycle"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_cycles"},{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"ASER_cycles_data"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_ASER_cycles_data"}]},"ASER_CIV_data_has_entry_calendar":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"entry_calendar":{"Target":{"Entity":"entry_calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"entry_calendar"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_entry_calendars"},{"Attribute":{"Subject":{"Role":"entry_calendar"},"Object":{"Role":"ASER_CIV_data"}},"State":"Generated","Weight":0.99,"ID":"entry_calendars_have_ASER_CIV_data"}]},"ASER_CIV_data_has_level_in_subjects":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"level_in_subjects"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_level_in_subjects"},{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"ASER_CIV_data"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_ASER_CIV_data"}]},"ASER_CIV_data_has_cycle":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"cycle":{"Target":{"Entity":"cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"cycle"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_cycles"},{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"ASER_CIV_data"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_ASER_CIV_data"}]},"ASER_CIV_data_has_grade":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"grade":{"Target":{"Entity":"grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"grade"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_grades"},{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"ASER_CIV_data"}},"State":"Generated","Weight":0.99,"ID":"grades_have_ASER_CIV_data"}]},"compared_to_cycle_has_cycle_name":{"Binding":{"ConceptualEntity":"Compared To Cycles"},"State":"Generated","Roles":{"compared_to_cycle":{"Target":{"Entity":"compared_to_cycle"}},"compared_to_cycle.cycle_name":{"Target":{"Entity":"compared_to_cycle.cycle_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"compared_to_cycle"},"Object":{"Role":"compared_to_cycle.cycle_name"}},"State":"Generated","Weight":0.99,"ID":"compared_to_cycle_have_cycle_names"}]},"compared_to_cycle_has_cycle_ID":{"Binding":{"ConceptualEntity":"Compared To Cycles"},"State":"Generated","Roles":{"compared_to_cycle":{"Target":{"Entity":"compared_to_cycle"}},"compared_to_cycle.cycle_ID":{"Target":{"Entity":"compared_to_cycle.cycle_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"compared_to_cycle"},"Object":{"Role":"compared_to_cycle.cycle_ID"}},"State":"Generated","Weight":0.99,"ID":"compared_to_cycle_have_cycle_ID"}]},"cycle_has_mesure_cycle_comparison_revelance_test":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.cycle_comparison_revelance_test":{"Target":{"Entity":"mesure.cycle_comparison_revelance_test"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.cycle_comparison_revelance_test"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycle_comparison_revelance_test"}]},"compared_to_cycle_has_mesure_cycle_comparison_revelance_test":{"Binding":{"ConceptualEntity":"Compared To Cycles"},"State":"Generated","Roles":{"compared_to_cycle":{"Target":{"Entity":"compared_to_cycle"}},"mesure.cycle_comparison_revelance_test":{"Target":{"Entity":"mesure.cycle_comparison_revelance_test"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"compared_to_cycle"},"Object":{"Role":"mesure.cycle_comparison_revelance_test"}},"State":"Generated","Weight":0.99,"ID":"compared_to_cycle_have_cycle_comparison_revelance_test"}]},"cycle_has_mesure_selected_cycle_ID":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.selected_cycle_ID":{"Target":{"Entity":"mesure.selected_cycle_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.selected_cycle_ID"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_selected_cycle_ID"}]},"compared_to_cycle_has_mesure_compared_to_cycle_ID":{"Binding":{"ConceptualEntity":"Compared To Cycles"},"State":"Generated","Roles":{"compared_to_cycle":{"Target":{"Entity":"compared_to_cycle"}},"mesure.compared_to_cycle_ID":{"Target":{"Entity":"mesure.compared_to_cycle_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"compared_to_cycle"},"Object":{"Role":"mesure.compared_to_cycle_ID"}},"State":"Generated","Weight":0.99,"ID":"compared_to_cycle_have_compared_to_cycle_ID"}]},"cycles_interval_has_mesure_compared_to_cycle":{"Binding":{"ConceptualEntity":"Cycles interval"},"State":"Generated","Roles":{"cycles_interval":{"Target":{"Entity":"cycles_interval"}},"mesure.compared_to_cycle":{"Target":{"Entity":"mesure.compared_to_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycles_interval"},"Object":{"Role":"mesure.compared_to_cycle"}},"State":"Generated","Weight":0.99,"ID":"cycles_intervals_have_compared_to_cycle"},{"Verb":{"Verbs":[{"compare":{"State":"Generated"}}],"Object":{"Role":"cycles_interval"},"PrepositionalPhrases":[{"Prepositions":[{"to":{"State":"Generated"}}],"Object":{"Role":"mesure.compared_to_cycle"}}]},"State":"Generated","Weight":0.95,"ID":"cycles_intervals_are_compared_to_compared_to_cycle"},{"Verb":{"Verbs":[{"compare":{"State":"Generated"}}],"IndirectObject":{"Role":"mesure.compared_to_cycle"},"Object":{"Role":"cycles_interval"}},"State":"Generated","Weight":0.75,"ID":"compared_to_cycle_are_compared_cycles_intervals"}]},"cycle_has_mesure_compared_to_cycle":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.compared_to_cycle":{"Target":{"Entity":"mesure.compared_to_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.compared_to_cycle"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_compared_to_cycle"},{"Verb":{"Verbs":[{"compare":{"State":"Generated"}}],"Object":{"Role":"cycle"},"PrepositionalPhrases":[{"Prepositions":[{"to":{"State":"Generated"}}],"Object":{"Role":"mesure.compared_to_cycle"}}]},"State":"Generated","Weight":0.95,"ID":"cycles_are_compared_to_compared_to_cycle"},{"Verb":{"Verbs":[{"compare":{"State":"Generated"}}],"IndirectObject":{"Role":"mesure.compared_to_cycle"},"Object":{"Role":"cycle"}},"State":"Generated","Weight":0.75,"ID":"compared_to_cycle_are_compared_cycles"}]},"cycle_has_mesure_selected_cycle":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.selected_cycle":{"Target":{"Entity":"mesure.selected_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.selected_cycle"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_selected_cycle"}]},"mesure_has_percentage_of_students_tested_with_low_Literacy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_Literacy_in_grade"}]},"mesure_has_numeracy_difficulty_reduction_BL_to_EL_PP":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.numeracy_difficulty_reduction_BL_to_EL_PP":{"Target":{"Entity":"mesure.numeracy_difficulty_reduction_BL_to_EL_PP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.numeracy_difficulty_reduction_BL_to_EL_PP"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_numeracy_difficulty_reduction_BL_to_EL_PP"}]},"mesure_has_percentage_of_students_tested_with_low_numeracy_in_grade_EL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_EL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_EL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_EL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_numeracy_in_grade_EL"}]},"mesure_has_percentage_of_students_tested_with_low_numeracy_in_grade_BL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_BL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade_BL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_numeracy_in_grade_BL"}]},"mesure_has_percentage_of_students_tested_with_low_numeracy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_numeracy_in_grade":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_numeracy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_numeracy_in_grade"}]},"mesure_has_percentage_of_students_tested_with_low_numeracy_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_numeracy_in_cycle":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_numeracy_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_numeracy_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_numeracy_in_cycle"}]},"mesure_has_number_of_students_tested_with_low_numeracy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_with_low_numeracy_in_grade":{"Target":{"Entity":"mesure.number_of_students_tested_with_low_numeracy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_with_low_numeracy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_with_low_numeracy_in_grade"}]},"mesure_has_percentage_of_students_tested_with_high_numeracy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_numeracy_in_grade"}]},"mesure_has_percentage_of_students_tested_with_high_numeracy_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_numeracy_in_cycle":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_numeracy_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_numeracy_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_numeracy_in_cycle"}]},"mesure_has_numeracy_Improvement_BL_to_EL_PP":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.numeracy_Improvement_BL_to_EL_PP":{"Target":{"Entity":"mesure.numeracy_Improvement_BL_to_EL_PP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.numeracy_Improvement_BL_to_EL_PP"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_numeracy_Improvement_BL_to_EL_PP"}]},"mesure_has_percentage_of_students_tested_with_high_numeracy_in_grade_EL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_EL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_EL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_EL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_numeracy_in_grade_EL"}]},"mesure_has_percentage_of_students_tested_with_high_numeracy_in_grade_BL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_BL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_numeracy_in_grade_BL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_numeracy_in_grade_BL"}]},"mesure_has_number_of_students_tested_with_high_numeracy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_with_high_numeracy_in_grade":{"Target":{"Entity":"mesure.number_of_students_tested_with_high_numeracy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_with_high_numeracy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_with_high_numeracy_in_grade"}]},"mesure_has_percentage_of_students_tested_with_low_Literacy_in_grade_BL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_BL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_BL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_Literacy_in_grade_BL"}]},"mesure_has_percentage_of_students_tested_with_low_Literacy_in_grade_EL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_EL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_EL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_EL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_Literacy_in_grade_EL"}]},"mesure_has_percentage_of_students_tested_with_low_Literacy_in_grade_ML":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_ML":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_ML"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_low_Literacy_in_grade_ML"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_low_Literacy_in_grade_ML"}]},"mesure_has_Literacy_difficulty_reduction_BL_to_EL_PP":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.Literacy_difficulty_reduction_BL_to_EL_PP":{"Target":{"Entity":"mesure.Literacy_difficulty_reduction_BL_to_EL_PP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.Literacy_difficulty_reduction_BL_to_EL_PP"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_Literacy_difficulty_reduction_BL_to_EL_PP"}]},"mesure_has_number_of_students_tested_with_low_Literacy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_with_low_Literacy_in_grade":{"Target":{"Entity":"mesure.number_of_students_tested_with_low_Literacy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_with_low_Literacy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_with_low_Literacy_in_grade"}]},"mesure_has_Literacy_Improvement_BL_to_EL_PP":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.Literacy_Improvement_BL_to_EL_PP":{"Target":{"Entity":"mesure.Literacy_Improvement_BL_to_EL_PP"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.Literacy_Improvement_BL_to_EL_PP"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_Literacy_Improvement_BL_to_EL_PP"}]},"mesure_has_percentage_of_students_tested_with_high_Literacy_in_grade_EL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_EL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_EL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_EL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_Literacy_in_grade_EL"}]},"mesure_has_percentage_of_students_tested_with_high_Literacy_in_grade_BL":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_BL":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade_BL"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_Literacy_in_grade_BL"}]},"mesure_has_number_of_students_tested_with_high_Literacy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_with_high_Literacy_in_grade":{"Target":{"Entity":"mesure.number_of_students_tested_with_high_Literacy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_with_high_Literacy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_with_high_Literacy_in_grade"}]},"mesure_has_number_of_students_tested_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_in_grade":{"Target":{"Entity":"mesure.number_of_students_tested_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_in_grade"}]},"mesure_has_percentage_of_students_tested_with_high_Literacy_in_grade":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_Literacy_in_grade":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_Literacy_in_grade"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_Literacy_in_grade"}]},"mesure_has_percentage_of_students_tested_with_high_Literacy_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_of_students_tested_with_high_Literacy_in_cycle":{"Target":{"Entity":"mesure.percentage_of_students_tested_with_high_Literacy_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_of_students_tested_with_high_Literacy_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_of_students_tested_with_high_Literacy_in_cycle"}]},"level_in_subjects_has_subject_hierarchy":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.subject_hierarchy":{"Target":{"Entity":"level_in_subjects.subject_hierarchy"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.subject_hierarchy"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_subject_hierarchies"}]},"level_in_subjects_has_group_level_sort":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.group_level_sort":{"Target":{"Entity":"level_in_subjects.group_level_sort"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.group_level_sort"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_group_level_sorts"}]},"level_in_subjects_has_grouped_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.grouped_level":{"Target":{"Entity":"level_in_subjects.grouped_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.grouped_level"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_grouped_levels"}]},"level_in_subjects_has_level_sort":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.level_sort":{"Target":{"Entity":"level_in_subjects.level_sort"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.level_sort"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_level_sorts"}]},"cycle_has_cycle_sort":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"cycle.cycle_sort":{"Target":{"Entity":"cycle.cycle_sort"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"cycle.cycle_sort"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycle_sorts"}]},"grade_has_grade_sort":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.grade_sort":{"Target":{"Entity":"grade.grade_sort"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.grade_sort"}},"State":"Generated","Weight":0.99,"ID":"grades_have_grade_sorts"}]},"cycles_interval_has_valeur_cycles_interval":{"Binding":{"ConceptualEntity":"Cycles interval"},"State":"Generated","Roles":{"cycles_interval":{"Target":{"Entity":"cycles_interval"}},"cycles_interval.valeur_cycles_interval":{"Target":{"Entity":"cycles_interval.valeur_cycles_interval"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycles_interval"},"Object":{"Role":"cycles_interval.valeur_cycles_interval"}},"State":"Generated","Weight":0.99,"ID":"cycles_intervals_have_valeur_cycles_interval"}]},"cycles_interval_has_cycles_interval":{"Binding":{"ConceptualEntity":"Cycles interval"},"State":"Generated","Roles":{"cycles_interval":{"Target":{"Entity":"cycles_interval"}},"cycles_interval.cycles_interval":{"Target":{"Entity":"cycles_interval.cycles_interval"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycles_interval"},"Object":{"Role":"cycles_interval.cycles_interval"}},"State":"Generated","Weight":0.99,"ID":"cycles_intervals_have_cycles_intervals"}]},"school_has_school_ID":{"Binding":{"ConceptualEntity":"Schools"},"State":"Generated","Roles":{"school":{"Target":{"Entity":"school"}},"school.school_ID":{"Target":{"Entity":"school.school_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"school"},"Object":{"Role":"school.school_ID"}},"State":"Generated","Weight":0.99,"ID":"schools_have_school_ID"},{"Name":{"Subject":{"Role":"school"},"Name":{"Role":"school.school_ID"}},"State":"Generated","Weight":0.99,"ID":"school_ID_are_names_IDs_of_schools"}]},"school_has_school":{"Binding":{"ConceptualEntity":"Schools"},"State":"Generated","Roles":{"school":{"Target":{"Entity":"school"}},"school.school":{"Target":{"Entity":"school.school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"school"},"Object":{"Role":"school.school"}},"State":"Generated","Weight":0.99,"ID":"schools_have_schools"},{"Name":{"Subject":{"Role":"school"},"Name":{"Role":"school.school"}},"State":"Generated","Weight":0.99,"ID":"schools_are_names_IDs_of_schools"}]},"school_has_iepp":{"Binding":{"ConceptualEntity":"Schools"},"State":"Generated","Roles":{"school":{"Target":{"Entity":"school"}},"school.iepp":{"Target":{"Entity":"school.iepp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"school"},"Object":{"Role":"school.iepp"}},"State":"Generated","Weight":0.99,"ID":"schools_have_iepps"}]},"school_has_drenaet":{"Binding":{"ConceptualEntity":"Schools"},"State":"Generated","Roles":{"school":{"Target":{"Entity":"school"}},"school.drenaet":{"Target":{"Entity":"school.drenaet"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"school"},"Object":{"Role":"school.drenaet"}},"State":"Generated","Weight":0.99,"ID":"schools_have_drenaets"}]},"ASER_cycles_data_has_entry_date":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.entry_date":{"Target":{"Entity":"ASER_cycles_data.entry_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.entry_date"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_entry_dates"}]},"ASER_cycles_data_has_student_at_level":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.student_at_level":{"Target":{"Entity":"ASER_cycles_data.student_at_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.student_at_level"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_student_at_level"}]},"ASER_cycles_data_has_teacher_female_in_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.teacher_female_in_school":{"Target":{"Entity":"ASER_cycles_data.teacher_female_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.teacher_female_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_teacher_female_in_school"}]},"ASER_cycles_data_has_teacher_male_in_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.teacher_male_in_school":{"Target":{"Entity":"ASER_cycles_data.teacher_male_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.teacher_male_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_teacher_male_in_school"}]},"ASER_cycles_data_has_girl_tested_in_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.girl_tested_in_school":{"Target":{"Entity":"ASER_cycles_data.girl_tested_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.girl_tested_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_girl_tested_in_school"}]},"ASER_cycles_data_has_boy_tested_in_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.boy_tested_in_school":{"Target":{"Entity":"ASER_cycles_data.boy_tested_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.boy_tested_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_boy_tested_in_school"}]},"ASER_cycles_data_has_student_in_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.student_in_school":{"Target":{"Entity":"ASER_cycles_data.student_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.student_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_student_in_school"}]},"ASER_cycles_data_has_iepp_id":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.iepp_id":{"Target":{"Entity":"ASER_cycles_data.iepp_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.iepp_id"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_iepp_ids"}]},"ASER_cycles_data_has_drenaet_id":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.drenaet_id":{"Target":{"Entity":"ASER_cycles_data.drenaet_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.drenaet_id"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_drenaet_ids"}]},"ASER_cycles_data_has_subject_ID":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.subject_ID":{"Target":{"Entity":"ASER_cycles_data.subject_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.subject_ID"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_subject_ID"}]},"ASER_cycles_data_has_period":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"ASER_cycles_data.period":{"Target":{"Entity":"ASER_cycles_data.period"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"ASER_cycles_data.period"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_periods"}]},"mesure_has_girls_tested_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.girls_tested_in_cycle":{"Target":{"Entity":"mesure.girls_tested_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.girls_tested_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_girls_tested_in_cycle"}]},"mesure_has_boys_tested_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.boys_tested_in_cycle":{"Target":{"Entity":"mesure.boys_tested_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.boys_tested_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_boys_tested_in_cycle"}]},"cycles_interval_has_mesure_cycles_compared":{"Binding":{"ConceptualEntity":"Cycles interval"},"State":"Generated","Roles":{"cycles_interval":{"Target":{"Entity":"cycles_interval"}},"mesure.cycles_compared":{"Target":{"Entity":"mesure.cycles_compared"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycles_interval"},"Object":{"Role":"mesure.cycles_compared"}},"State":"Generated","Weight":0.99,"ID":"cycles_intervals_have_cycles_compared"}]},"cycle_has_mesure_cycles_compared":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.cycles_compared":{"Target":{"Entity":"mesure.cycles_compared"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.cycles_compared"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycles_compared"}]},"mesure_has_number_of_students_tested_in_previous_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_in_previous_cycle":{"Target":{"Entity":"mesure.number_of_students_tested_in_previous_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_in_previous_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_in_previous_cycle"}]},"mesure_has_percentage_change_rate_of_students_tested":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.percentage_change_rate_of_students_tested":{"Target":{"Entity":"mesure.percentage_change_rate_of_students_tested"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.percentage_change_rate_of_students_tested"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_percentage_change_rate_of_students_tested"}]},"ASER_CIV_data_has_mesure_number_of_students_reached_in_program":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.number_of_students_reached_in_program":{"Target":{"Entity":"mesure.number_of_students_reached_in_program"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.number_of_students_reached_in_program"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_number_of_students_reached_in_program"}]},"mesure_has_number_of_students_tested_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_in_cycle":{"Target":{"Entity":"mesure.number_of_students_tested_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_in_cycle"}]},"mesure_has_mesure":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.mesure":{"Target":{"Entity":"mesure.mesure"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.mesure"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_mesure"}]},"mesure_has_number_of_students_tested_v2":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_tested_v2":{"Target":{"Entity":"mesure.number_of_students_tested_v2"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_tested_v2"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_tested_v2"}]},"mesure_has_number_of_students_v2":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_v2":{"Target":{"Entity":"mesure.number_of_students_v2"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_v2"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_v2"}]},"level_in_subjects_has_mesure_number_of_students_tested_BL":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"mesure.number_of_students_tested_BL":{"Target":{"Entity":"mesure.number_of_students_tested_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"mesure.number_of_students_tested_BL"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_number_of_students_tested_BL"}]},"cycle_has_mesure_number_of_students_tested_BL":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.number_of_students_tested_BL":{"Target":{"Entity":"mesure.number_of_students_tested_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.number_of_students_tested_BL"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_number_of_students_tested_BL"}]},"ASER_CIV_data_has_mesure_number_of_students_tested_BL":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.number_of_students_tested_BL":{"Target":{"Entity":"mesure.number_of_students_tested_BL"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.number_of_students_tested_BL"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_number_of_students_tested_BL"}]},"mesure_has_number_of_students_in_cycle":{"Binding":{"ConceptualEntity":"Mesures"},"State":"Generated","Roles":{"mesure":{"Target":{"Entity":"mesure"}},"mesure.number_of_students_in_cycle":{"Target":{"Entity":"mesure.number_of_students_in_cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"mesure"},"Object":{"Role":"mesure.number_of_students_in_cycle"}},"State":"Generated","Weight":0.99,"ID":"mesures_have_number_of_students_in_cycle"}]},"cycle_has_mesure_number_of_students_tested":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.number_of_students_tested":{"Target":{"Entity":"mesure.number_of_students_tested"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.number_of_students_tested"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_number_of_students_tested"}]},"ASER_CIV_data_has_mesure_number_of_students_tested":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.number_of_students_tested":{"Target":{"Entity":"mesure.number_of_students_tested"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.number_of_students_tested"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_number_of_students_tested"}]},"cycle_has_mesure_percentage_of_students":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.percentage_of_students":{"Target":{"Entity":"mesure.percentage_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.percentage_of_students"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_percentage_of_students"}]},"ASER_CIV_data_has_mesure_percentage_of_students":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.percentage_of_students":{"Target":{"Entity":"mesure.percentage_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.percentage_of_students"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_percentage_of_students"}]},"cycle_has_mesure_entity__number_of_students":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.entity__number_of_students":{"Target":{"Entity":"mesure.entity__number_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.entity__number_of_students"}},"State":"Generated","Weight":0.99,"ID":"cycles_have__number_of_students"}]},"ASER_CIV_data_has_mesure_entity__number_of_students":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.entity__number_of_students":{"Target":{"Entity":"mesure.entity__number_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.entity__number_of_students"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have__number_of_students"}]},"cycle_has_mesure_number_of_students":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"mesure.number_of_students":{"Target":{"Entity":"mesure.number_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"mesure.number_of_students"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_number_of_students"}]},"ASER_CIV_data_has_mesure_number_of_students":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.number_of_students":{"Target":{"Entity":"mesure.number_of_students"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.number_of_students"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_number_of_students"}]},"ASER_CIV_data_has_mesure_number_of_schools_tested":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"mesure.number_of_schools_tested":{"Target":{"Entity":"mesure.number_of_schools_tested"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"mesure.number_of_schools_tested"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_number_of_schools_tested"}]},"grade_has_mesure_number_of_schools":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"mesure.number_of_schools":{"Target":{"Entity":"mesure.number_of_schools"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"mesure.number_of_schools"}},"State":"Generated","Weight":0.99,"ID":"grades_have_number_of_schools"}]},"grade_has_mesure_number_of_IEPPs":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"mesure.number_of_IEPPs":{"Target":{"Entity":"mesure.number_of_IEPPs"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"mesure.number_of_IEPPs"}},"State":"Generated","Weight":0.99,"ID":"grades_have_number_of_IEPPs"}]},"grade_has_mesure_number_of_DRENAETs":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"mesure.number_of_DRENAETs":{"Target":{"Entity":"mesure.number_of_DRENAETs"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"mesure.number_of_DRENAETs"}},"State":"Generated","Weight":0.99,"ID":"grades_have_number_of_DRENAETs"}]},"entry_calendar_has_date":{"Binding":{"ConceptualEntity":"Entry Calendar"},"State":"Generated","Roles":{"entry_calendar":{"Target":{"Entity":"entry_calendar"}},"entry_calendar.date":{"Target":{"Entity":"entry_calendar.date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"entry_calendar"},"Object":{"Role":"entry_calendar.date"}},"State":"Generated","Weight":0.99,"ID":"entry_calendars_have_dates"}]},"level_in_subjects_has_subject_ID":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.subject_ID":{"Target":{"Entity":"level_in_subjects.subject_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.subject_ID"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_subject_ID"}]},"level_in_subjects_has_level_ID":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.level_ID":{"Target":{"Entity":"level_in_subjects.level_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.level_ID"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_level_ID"}]},"level_in_subjects_has_subject":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.subject":{"Target":{"Entity":"level_in_subjects.subject"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.subject"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_subjects"}]},"level_in_subjects_has_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}},"level_in_subjects.level":{"Target":{"Entity":"level_in_subjects.level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"level_in_subjects.level"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_levels"}]},"cycle_has_cycle_name":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"cycle.cycle_name":{"Target":{"Entity":"cycle.cycle_name"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"cycle.cycle_name"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycle_names"},{"Name":{"Subject":{"Role":"cycle"},"Name":{"Role":"cycle.cycle_name"}},"State":"Generated","Weight":0.99,"ID":"cycle_names_are_names_IDs_of_cycles"}]},"cycle_has_period":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"cycle.period":{"Target":{"Entity":"cycle.period"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"cycle.period"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_periods"}]},"cycle_has_cycle":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"cycle.cycle":{"Target":{"Entity":"cycle.cycle"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"cycle.cycle"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycles"}]},"cycle_has_cycle_ID":{"Binding":{"ConceptualEntity":"Cycles"},"State":"Generated","Roles":{"cycle":{"Target":{"Entity":"cycle"}},"cycle.cycle_ID":{"Target":{"Entity":"cycle.cycle_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"cycle"},"Object":{"Role":"cycle.cycle_ID"}},"State":"Generated","Weight":0.99,"ID":"cycles_have_cycle_ID"},{"Name":{"Subject":{"Role":"cycle"},"Name":{"Role":"cycle.cycle_ID"}},"State":"Generated","Weight":0.99,"ID":"cycle_ID_are_names_IDs_of_cycles"}]},"grade_has_iepp_id":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.iepp_id":{"Target":{"Entity":"grade.iepp_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.iepp_id"}},"State":"Generated","Weight":0.99,"ID":"grades_have_iepp_ids"}]},"grade_has_drenaet_id":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.drenaet_id":{"Target":{"Entity":"grade.drenaet_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.drenaet_id"}},"State":"Generated","Weight":0.99,"ID":"grades_have_drenaet_ids"}]},"grade_has_school_ID":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.school_ID":{"Target":{"Entity":"grade.school_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.school_ID"}},"State":"Generated","Weight":0.99,"ID":"grades_have_school_ID"}]},"grade_has_donor":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.donor":{"Target":{"Entity":"grade.donor"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.donor"}},"State":"Generated","Weight":0.99,"ID":"grades_have_donors"},{"Verb":{"Subject":{"Role":"grade.donor"},"Verbs":[{"don":{"State":"Generated"}}],"Object":{"Role":"grade"}},"State":"Generated","Weight":0.75,"ID":"donors_don_grades"},{"Attribute":{"Subject":{"Role":"grade.donor"},"Object":{"Role":"grade"}},"State":"Generated","Weight":0.99,"ID":"donors_have_grades"}]},"grade_has_grade_ID":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.grade_ID":{"Target":{"Entity":"grade.grade_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.grade_ID"}},"State":"Generated","Weight":0.99,"ID":"grades_have_grade_ID"},{"Name":{"Subject":{"Role":"grade"},"Name":{"Role":"grade.grade_ID"}},"State":"Generated","Weight":0.99,"ID":"grade_ID_are_names_IDs_of_grades"}]},"grade_has_grade":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.grade":{"Target":{"Entity":"grade.grade"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.grade"}},"State":"Generated","Weight":0.99,"ID":"grades_have_grades"}]},"grade_has_school":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.school":{"Target":{"Entity":"grade.school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.school"}},"State":"Generated","Weight":0.99,"ID":"grades_have_schools"}]},"grade_has_iepp":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.iepp":{"Target":{"Entity":"grade.iepp"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.iepp"}},"State":"Generated","Weight":0.99,"ID":"grades_have_iepps"}]},"grade_has_drenaet":{"Binding":{"ConceptualEntity":"Grades"},"State":"Generated","Roles":{"grade":{"Target":{"Entity":"grade"}},"grade.drenaet":{"Target":{"Entity":"grade.drenaet"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"grade"},"Object":{"Role":"grade.drenaet"}},"State":"Generated","Weight":0.99,"ID":"grades_have_drenaets"}]},"ASER_CIV_data_has_subject_ID":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.subject_ID":{"Target":{"Entity":"ASER_CIV_data.subject_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.subject_ID"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_subject_ID"}]},"ASER_CIV_data_has_period":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.period":{"Target":{"Entity":"ASER_CIV_data.period"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.period"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_periods"}]},"ASER_CIV_data_has_test":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.test":{"Target":{"Entity":"ASER_CIV_data.test"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.test"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_tests"}]},"ASER_CIV_data_has_iepp_id":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.iepp_id":{"Target":{"Entity":"ASER_CIV_data.iepp_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.iepp_id"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_iepp_ids"}]},"ASER_CIV_data_has_drenaet_id":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.drenaet_id":{"Target":{"Entity":"ASER_CIV_data.drenaet_id"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.drenaet_id"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_drenaet_ids"}]},"ASER_CIV_data_has_school_ID":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.school_ID":{"Target":{"Entity":"ASER_CIV_data.school_ID"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.school_ID"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_school_ID"}]},"ASER_CIV_data_has_entry_date":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.entry_date":{"Target":{"Entity":"ASER_CIV_data.entry_date"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.entry_date"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_entry_dates"}]},"ASER_CIV_data_has_student_at_level":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.student_at_level":{"Target":{"Entity":"ASER_CIV_data.student_at_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.student_at_level"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_student_at_level"}]},"ASER_CIV_data_has_teacher_female_in_school":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.teacher_female_in_school":{"Target":{"Entity":"ASER_CIV_data.teacher_female_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.teacher_female_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_teacher_female_in_school"}]},"ASER_CIV_data_has_teacher_male_in_school":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.teacher_male_in_school":{"Target":{"Entity":"ASER_CIV_data.teacher_male_in_school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.teacher_male_in_school"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_teacher_male_in_school"}]},"ASER_CIV_data_has_student_tested_in_class":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.student_tested_in_class":{"Target":{"Entity":"ASER_CIV_data.student_tested_in_class"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.student_tested_in_class"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_student_tested_in_class"}]},"ASER_CIV_data_has_girl_tested_in_class":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.girl_tested_in_class":{"Target":{"Entity":"ASER_CIV_data.girl_tested_in_class"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.girl_tested_in_class"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_girl_tested_in_class"}]},"ASER_CIV_data_has_boy_tested_in_class":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.boy_tested_in_class":{"Target":{"Entity":"ASER_CIV_data.boy_tested_in_class"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.boy_tested_in_class"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_boy_tested_in_class"}]},"ASER_CIV_data_has_student_in_class":{"Binding":{"ConceptualEntity":"ASER CIV Data"},"State":"Generated","Roles":{"ASER_CIV_data":{"Target":{"Entity":"ASER_CIV_data"}},"ASER_CIV_data.student_in_class":{"Target":{"Entity":"ASER_CIV_data.student_in_class"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_CIV_data"},"Object":{"Role":"ASER_CIV_data.student_in_class"}},"State":"Generated","Weight":0.99,"ID":"ASER_CIV_data_have_student_in_class"}]},"ASER_cycles_data_has_level_in_subjects":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"level_in_subjects":{"Target":{"Entity":"level_in_subjects"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"level_in_subjects"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_level_in_subjects"},{"Attribute":{"Subject":{"Role":"level_in_subjects"},"Object":{"Role":"ASER_cycles_data"}},"State":"Generated","Weight":0.99,"ID":"level_in_subjects_have_ASER_cycles_data"}]},"ASER_cycles_data_has_entry_calendar":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"entry_calendar":{"Target":{"Entity":"entry_calendar"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"entry_calendar"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_entry_calendars"},{"Attribute":{"Subject":{"Role":"entry_calendar"},"Object":{"Role":"ASER_cycles_data"}},"State":"Generated","Weight":0.99,"ID":"entry_calendars_have_ASER_cycles_data"}]},"ASER_cycles_data_has_school":{"Binding":{"ConceptualEntity":"ASER Cycles Data"},"State":"Generated","Roles":{"ASER_cycles_data":{"Target":{"Entity":"ASER_cycles_data"}},"school":{"Target":{"Entity":"school"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"ASER_cycles_data"},"Object":{"Role":"school"}},"State":"Generated","Weight":0.99,"ID":"ASER_cycles_data_have_schools"},{"Attribute":{"Subject":{"Role":"school"},"Object":{"Role":"ASER_cycles_data"}},"State":"Generated","Weight":0.99,"ID":"schools_have_ASER_cycles_data"}]},"level_in_subjects_subject_hierarchy_has_subject":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects.subject_hierarchy":{"Target":{"Entity":"level_in_subjects.subject_hierarchy"}},"level_in_subjects.subject_hierarchy.subject":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.subject"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy"},"Object":{"Role":"level_in_subjects.subject_hierarchy.subject"}},"State":"Generated","Weight":0.99,"ID":"subject_hierarchies_have_subjects"}]},"level_in_subjects_subject_hierarchy_has_grouped_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects.subject_hierarchy":{"Target":{"Entity":"level_in_subjects.subject_hierarchy"}},"level_in_subjects.subject_hierarchy.grouped_level":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.grouped_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy"},"Object":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"}},"State":"Generated","Weight":0.99,"ID":"subject_hierarchies_have_grouped_levels"}]},"level_in_subjects_subject_hierarchy_has_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects.subject_hierarchy":{"Target":{"Entity":"level_in_subjects.subject_hierarchy"}},"level_in_subjects.subject_hierarchy.level":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy"},"Object":{"Role":"level_in_subjects.subject_hierarchy.level"}},"State":"Generated","Weight":0.99,"ID":"subject_hierarchies_have_levels"}]},"level_in_subjects_subject_hierarchy_subject_has_level_in_subjects_subject_hierarchy_grouped_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects.subject_hierarchy.subject":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.subject"}},"level_in_subjects.subject_hierarchy.grouped_level":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.grouped_level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.subject"},"Object":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"}},"State":"Generated","Weight":0.99,"ID":"subjects_have_grouped_levels"},{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"},"Object":{"Role":"level_in_subjects.subject_hierarchy.subject"}},"State":"Generated","Weight":0.99,"ID":"grouped_levels_have_subjects"},{"Preposition":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"level_in_subjects.subject_hierarchy.subject"}},"State":"Generated","Weight":0.99,"ID":"grouped_levels_are_in_subjects"}]},"level_in_subjects_subject_hierarchy_grouped_level_has_level_in_subjects_subject_hierarchy_level":{"Binding":{"ConceptualEntity":"Levels in Subjects"},"State":"Generated","Roles":{"level_in_subjects.subject_hierarchy.grouped_level":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.grouped_level"}},"level_in_subjects.subject_hierarchy.level":{"Target":{"Entity":"level_in_subjects.subject_hierarchy.level"}}},"Phrasings":[{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"},"Object":{"Role":"level_in_subjects.subject_hierarchy.level"}},"State":"Generated","Weight":0.99,"ID":"grouped_levels_have_levels"},{"Attribute":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.level"},"Object":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"}},"State":"Generated","Weight":0.99,"ID":"levels_have_grouped_levels"},{"Preposition":{"Subject":{"Role":"level_in_subjects.subject_hierarchy.level"},"Prepositions":[{"in":{"State":"Generated"}}],"Object":{"Role":"level_in_subjects.subject_hierarchy.grouped_level"}},"State":"Generated","Weight":0.99,"ID":"levels_are_in_grouped_levels"}]}},"Agents":{"Internal":{"Version":"1.1.0"}}}
				contentType: json

		expression Paramètre1 = #"Exemple de fichier" meta [IsParameterQuery=true, BinaryIdentifier=#"Exemple de fichier", Type="Binary", IsParameterQueryRequired=true]
			lineageTag: 0d0598cb-5473-4bbb-a2f0-c2e02d4b0b63
			queryGroup: 'Transformer le fichier à partir de From 24_25 (2)\Requêtes d''assistance'

			annotation PBI_ResultType = Binary

		expression 'Transformer l''exemple de fichier' =
				let
				    Source = Excel.Workbook(Paramètre1, null, true),
				    ASER_Sheet = Source{[Item="ASER",Kind="Sheet"]}[Data]
				in
				    ASER_Sheet
			lineageTag: ada244f1-8141-4aa7-834d-d203885d4522
			queryGroup: 'Transformer le fichier à partir de From 24_25 (2)'

			annotation PBI_ResultType = Table

		expression 'Exemple de fichier' =
				let
				    Source = Folder.Files("C:\2026 04 Formation TaRL\ASER_Data\From 24_25"),
				    Navigation1 = Source{0}[Content]
				in
				    Navigation1
			lineageTag: 39cb1ec9-a4fe-4338-a9b6-6edf2b7162f8
			queryGroup: 'Transformer le fichier à partir de From 24_25 (2)\Requêtes d''assistance'

			annotation PBI_ResultType = Binary

		expression 'Transformer le fichier' =
				let
				    Source = (Paramètre1 as binary) => let
				    Source = Excel.Workbook(Paramètre1, null, true),
				    ASER_Sheet = Source{[Item="ASER",Kind="Sheet"]}[Data]
				in
				    ASER_Sheet
				in
				    Source
			mAttributes: [ FunctionQueryBinding = "{""exemplarFormulaName"":""Transformer l\u0027exemple de fichier""}" ]
			lineageTag: a566f16d-b64e-4193-9ad6-381f9645f47a
			queryGroup: 'Transformer le fichier à partir de From 24_25 (2)\Requêtes d''assistance'

			annotation PBI_ResultType = Function

			annotation PBI_NavigationStepName = Navigation

		expression fx_ComparaisonColonnes =
				(Table1 as table, Table2 as table, Alias_Table1 as text, Alias_Table2 as text) =>
				let
				    // Récupérer les noms des colonnes des deux tables
				    Columns1 = Table.ColumnNames(Table1),
				    Columns2 = Table.ColumnNames(Table2),
				
				    // Trier les noms des colonnes des deux tables
				    SortedColumns1 = List.Sort(Columns1),
				    SortedColumns2 = List.Sort(Columns2),
				
				    // Comparer les colonnes (vérifie noms + ordre des colonnes)
				    SameColumns = SortedColumns1 = SortedColumns2,
				    TestResult = if SameColumns then "Les deux tables ont les mêmes colonnes" else "Il existe des colonnes divergentes entre les 2 tables",
				
				    // Détection des colonnes présentes dans Table1 mais absentes de Table2
				    MissingInTable2 = List.Difference(SortedColumns1, SortedColumns2),
				    Table1_MissingColumns = Table.FromList(MissingInTable2, Splitter.SplitByNothing(), {"Colonne"}),
				    ExistsInTable1 = Table.AddColumn(Table1_MissingColumns, "Présente dans la table", each Alias_Table1 ),
				    NotInTable2 = Table.AddColumn(ExistsInTable1, "Mais pas dans la table", each Alias_Table2 ),
				
				    // Détection des colonnes présentes dans Table2 mais absentes de Table1
				    MissingInTable1 = List.Difference(SortedColumns2, SortedColumns1),
				    Table2_MissingColumns = Table.FromList(MissingInTable1, Splitter.SplitByNothing(), {"Colonne"}),
				    ExistsInTable2 = Table.AddColumn(Table2_MissingColumns, "Présente dans la table", each Alias_Table2 ),
				    NotInTable1 = Table.AddColumn(ExistsInTable2, "Mais pas dans la table", each Alias_Table1 ),
				    // Fusion des résultats
				    DiffColumns = Table.Combine({NotInTable2, NotInTable1}),
				    // NEW : Ajout dans le record d'un champ donnant le nombre de lignes de la table des écarts
				    NonMatchingCount = Table.RowCount(DiffColumns),
				
				    Result = [
				              Test vérification = TestResult,
				              Nombre de colonnes divergentes = NonMatchingCount,
				              Vérifier les colonnes divergentes = DiffColumns
				              ]
				
				in
				    Result
			lineageTag: 54f22b0a-3e68-4240-ad00-06825af29573

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Function

		expression 'New Data' =
				let
				    Source = Folder.Files("C:\2026 04 Formation TaRL\ASER_Data\From 24_25"),
				    #"Fichiers masqués filtrés1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Appeler une fonction personnalisée1" = Table.AddColumn(#"Fichiers masqués filtrés1", "Transformer le fichier", each #"Transformer le fichier"([Content])),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Appeler une fonction personnalisée1", {"Name", "Source.Name"}),
				    #"Autres colonnes supprimées1" = Table.SelectColumns(#"Colonnes renommées1", {"Source.Name", "Transformer le fichier"}),
				    #"Colonne de tables développée1" = Table.ExpandTableColumn(#"Autres colonnes supprimées1", "Transformer le fichier", Table.ColumnNames(#"Transformer le fichier"(#"Exemple de fichier"))),
				    #"Fractionner la colonne par délimiteur" = Table.SplitColumn(#"Colonne de tables développée1", "Source.Name", Splitter.SplitTextByDelimiter("_", QuoteStyle.Csv), {"Source.Name.1", "Source.Name.2"}),
				    #"Fractionner la colonne par délimiteur1" = Table.SplitColumn(#"Fractionner la colonne par délimiteur", "Source.Name.2", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, true), {"Source.Name.2.1", "Source.Name.2.2"}),
				    #"Fractionner la colonne par délimiteur2" = Table.SplitColumn(#"Fractionner la colonne par délimiteur1", "Source.Name.2.2", Splitter.SplitTextByDelimiter(".", QuoteStyle.Csv), {"Source.Name.2.2.1", "Source.Name.2.2.2"}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Fractionner la colonne par délimiteur2",{"Source.Name.2.1", "Source.Name.2.2.1", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28"}),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Autres colonnes supprimées", [PromoteAllScalars=true]),
				    #"Colonnes renommées" = Table.RenameColumns(#"En-têtes promus",{{"2024-2025", "Period"}, {"BL", "Cycle"}, {"DATE DE SAISIE", "Entry Date"}, {"REGIONS", "Region"}, {"inspections", "IEPP"}, {"SECTEUR PEDAGOGIQUE", "Sector"}, {"ECOLE", "School"}, {"COURS", "Grade"}, {"NOMBRE TOTAL ELEVES DANS LA CLASSE", "Students In Class"}, {"ELEVES GARCONS TESTES", "Boys Tested"}, {"ELEVES FILLES TESTES", "Girls Tested"}, {"ELEVE TOTAL TESTES", "Total Tested"}, {"DEBUTANT LECTURE", "Beginner L"}, {"LETTRES", "Letter"}, {"MOTS", "Word"}, {"PARAGRAPHES", "Paragraph"}, {"HISTOIRE", "Story"}, {"COMPREHENSION", "Comprehension"}, {"DEBUTANT MATH", "Beginner N"}, {"1 CHIFFRE", "1-Digit"}, {"2 CHIFFRES", "2-Digit"}, {"SOUSTRACTION", "Substraction"}, {"DIVISION", "Division"}, {"ENSEIGNANT HOMME PNAPASS DANS ECOLE", "Teacher Male"}, {"ENSEIGNANT FEMME PNAPASS DANS ECOLE", "Teacher Female"}, {"DRENA", "DRENAET"}}),
				    #"Autres colonnes supprimées2" = Table.SelectColumns(#"Colonnes renommées",{"Period", "Cycle", "Entry Date", "Region", "DRENAET", "IEPP", "Sector", "School", "Grade", "Students In Class", "Boys Tested", "Girls Tested", "Total Tested", "Beginner L", "Letter", "Word", "Paragraph", "Story", "Comprehension", "Beginner N", "1-Digit", "2-Digit", "Substraction", "Division", "Teacher Male", "Teacher Female"}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Autres colonnes supprimées2",{{"Period", type text}, {"Cycle", type text}, {"Entry Date", type datetime}, {"Region", type text}, {"DRENAET", type text}, {"IEPP", type text}, {"Sector", type text}, {"School", type text}, {"Grade", type text}, {"Students In Class", Int64.Type}, {"Boys Tested", Int64.Type}, {"Girls Tested", Int64.Type}, {"Total Tested", Int64.Type}, {"Beginner L", Int64.Type}, {"Letter", Int64.Type}, {"Word", Int64.Type}, {"Paragraph", Int64.Type}, {"Story", Int64.Type}, {"Comprehension", Int64.Type}, {"Beginner N", Int64.Type}, {"1-Digit", Int64.Type}, {"2-Digit", Int64.Type}, {"Substraction", Int64.Type}, {"Division", Int64.Type}, {"Teacher Male", Int64.Type}, {"Teacher Female", Int64.Type}}),
				    #"Lignes filtrées" = Table.SelectRows(#"Type modifié", each ([Region] <> "REGIONS")),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Lignes filtrées",{{"Entry Date", type date}}),
				    #"Colonnes renommées2" = Table.RenameColumns(#"Type modifié1",{{"Total Tested", "Students Tested"}})
				in
				    #"Colonnes renommées2"
			lineageTag: 052ac18e-e178-4066-b7dc-70cbe9696c52

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression ASER_2021-2022 =
				let
				    Source = Excel.Workbook(File.Contents("C:\2026 04 Formation TaRL\ASER_Data\Before 24_25\ASER Data_2021-2022.xlsx"), null, true),
				    ASER_Sheet = Source{[Item="ASER",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(ASER_Sheet, [PromoteAllScalars=true])
				in
				    #"En-têtes promus"
			lineageTag: eadbc1b8-e0c2-4a97-b99b-8c8cf448b027
			queryGroup: 'Sources Old Data'

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression ASER_2022-2023 =
				let
				    Source = Excel.Workbook(File.Contents("C:\2026 04 Formation TaRL\ASER_Data\Before 24_25\ASER Data_2022-2023.xlsx"), null, true),
				    ASER_Sheet = Source{[Item="ASER",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(ASER_Sheet, [PromoteAllScalars=true])
				in
				    #"En-têtes promus"
			lineageTag: b34597f1-bd0a-4830-b8c0-d374a0cb4012
			queryGroup: 'Sources Old Data'

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression ASER_2023-2024 =
				let
				    Source = Excel.Workbook(File.Contents("C:\2026 04 Formation TaRL\ASER_Data\Before 24_25\ASER Data_2023-2024.xlsx"), null, true),
				    ASER_Sheet = Source{[Item="ASER",Kind="Sheet"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(ASER_Sheet, [PromoteAllScalars=true])
				in
				    #"En-têtes promus"
			lineageTag: d92bbcaf-e3f7-4cbb-8c67-083fac3f599c
			queryGroup: 'Sources Old Data'

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'Old Data' =
				let
				    Source = Table.Combine({#"ASER_2021-2022", #"ASER_2022-2023", #"ASER_2023-2024"}),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"DRENAET", type text}, {"IEPP", type text}, {"School", type text}, {"Cycle", type text}, {"Grade", type text}, {"Students In Class", Int64.Type}, {"Boys Tested", Int64.Type}, {"Girls Tested", Int64.Type}, {"Beginner L", Int64.Type}, {"Letter", Int64.Type}, {"Word", Int64.Type}, {"Paragraph", Int64.Type}, {"Story", Int64.Type}, {"Beginner N", Int64.Type}, {"1-Digit", Int64.Type}, {"2-Digit", Int64.Type}, {"Substraction", Int64.Type}, {"Division", Int64.Type}, {"Comprehension", Int64.Type}, {"Entry Date", type date}, {"Region", type text}, {"Sector", type text}, {"Students Tested", Int64.Type}, {"Period", type text}, {"Teacher Male", Int64.Type}, {"Teacher Female", Int64.Type}})
				in
				    #"Type modifié"
			lineageTag: bad010f8-9b9f-4161-af72-a0a4c3e45d52

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression 'DRENAETs and Donors' =
				let
				    Source = Excel.Workbook(File.Contents("C:\2026 04 Formation TaRL\ASER_Data\Donor and DRENAET.xlsx"), null, true),
				    Tableau1_Table = Source{[Item="Tableau1",Kind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(Tableau1_Table,{{"DRENAET", type text}, {"Donors", type text}}),
				    #"Index ajouté" = Table.AddIndexColumn(#"Type modifié", "Index", 0, 1, Int64.Type),
				    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "DRENAET ID"}, {"Donors", "Donor"}})
				in
				    #"Colonnes renommées"
			lineageTag: 7164e3e1-cb21-4b60-ad6c-7505e1b31b86

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		expression IEPPs =
				let
				    Source = Table.Combine({#"Old Data", #"New Data"}),
				    #"Texte en majuscules" = Table.TransformColumns(Source,{{"DRENAET", Text.Upper, type text}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Texte en majuscules","DRENA ","",Replacer.ReplaceText,{"DRENAET"}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Valeur remplacée",{"DRENAET", "IEPP", "School", "Grade"}),
				    #"Doublons supprimés" = Table.Distinct(#"Autres colonnes supprimées"),
				    #"Index ajouté" = Table.AddIndexColumn(#"Doublons supprimés", "Index", 0, 1, Int64.Type),
				    #"Colonnes renommées" = Table.RenameColumns(#"Index ajouté",{{"Index", "Grade ID"}}),
				    #"Requêtes fusionnées" = Table.NestedJoin(#"Colonnes renommées", {"DRENAET"}, #"DRENAETs and Donors", {"DRENAET"}, "DRENAETs and Donors", JoinKind.LeftOuter),
				    #"DRENAETs and Donors développé" = Table.ExpandTableColumn(#"Requêtes fusionnées", "DRENAETs and Donors", {"Donor"}, {"Donor"}),
				    #"Requêtes fusionnées1" = Table.NestedJoin(#"DRENAETs and Donors développé", {"DRENAET", "IEPP", "School"}, Schools, {"DRENAET", "IEPP", "School"}, "Schools", JoinKind.LeftOuter),
				    #"Schools développé" = Table.ExpandTableColumn(#"Requêtes fusionnées1", "Schools", {"School ID"}, {"School ID"}),
				    #"Autres colonnes supprimées1" = Table.SelectColumns(#"Schools développé",{"DRENAET", "IEPP"}),
				    #"Doublons supprimés1" = Table.Distinct(#"Autres colonnes supprimées1"),
				    #"Index ajouté1" = Table.AddIndexColumn(#"Doublons supprimés1", "Index", 0, 1, Int64.Type),
				    #"Colonnes renommées1" = Table.RenameColumns(#"Index ajouté1",{{"Index", "IEPP ID"}})
				in
				    #"Colonnes renommées1"
			lineageTag: 01df9dd4-bf23-4dc0-a0a6-02dd78e9f02e

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		queryGroup 'Transformer le fichier à partir de From 24_25 (2)'

			annotation PBI_QueryGroupOrder = 0

		queryGroup 'Transformer le fichier à partir de From 24_25 (2)\Requêtes d''assistance'

			annotation PBI_QueryGroupOrder = 0

		queryGroup 'Sources Old Data'

			annotation PBI_QueryGroupOrder = 2

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["fx_ComparaisonColonnes","New Data","Paramètre1","Transformer l'exemple de fichier","Exemple de fichier","Transformer le fichier","ASER_2021-2022","ASER_2022-2023","ASER_2023-2024","Old Data","ASER CIV Data","Grades","Cycles","Levels in Subjects","DRENAETs and Donors","Schools","IEPPs","Mesures","ASER Cycles Data","Compared To Cycles"]

		annotation PBI_ProTooling = ["DaxQueryView_Desktop","TMDLView_Desktop"]

