createOrReplace

	ref table Mesures

		measure '_# Of Students Reached In Program' =
				
				VAR __BaseTable =
				    SUMMARIZE (
				        'ASER CIV Data',
				        Cycles[Period],
				        'ASER CIV Data'[Cycle ID],
				        'ASER CIV Data'[School ID],
				        'ASER CIV Data'[Grade ID],
				        "@Effectif", MAX ( 'ASER CIV Data'[Students In Class] )
				    )
				
				VAR __TotalParCycle =
				    GROUPBY (
				        __BaseTable,
				        Cycles[Period],
				        'ASER CIV Data'[Cycle ID],
				        "@TotalCycle", SUMX ( CURRENTGROUP (), [@Effectif] )
				    )
				
				RETURN
				    MAXX ( __TotalParCycle, [@TotalCycle] )
			formatString: #,0
			displayFolder: 2. Program specific KPIs
			lineageTag: 24fd0b70-42c6-4753-ba54-2d4d41e7d508

